[gamevals.dbtable]
thieving_pickpocket = 65480
thieving_stall = 65481
thieving_coin_pouch = 65482

[gamevals.dbrow]
thieving_man = 62400
thieving_woman = 62401
thieving_citizen = 62402
thieving_farmer = 62403
thieving_male_h_a_m_member = 62404
thieving_female_h_a_m_member = 62405
thieving_h_a_m_member = 62406
thieving_warrior_woman = 62407
thieving_warrior = 62408
thieving_workman = 62409
thieving_villager = 62410
thieving_rogue = 62411
thieving_cave_goblin = 62412
thieving_master_farmer = 62413
thieving_guard = 62414
thieving_fremennik_citizen = 62415
thieving_bearded_pollnivnian_bandit = 62416
thieving_wealthy_citizen = 62417
thieving_desert_bandit = 62418
thieving_knight_of_ardougne = 62419
thieving_knight_of_varlamore = 62420
thieving_pollnivnian_bandit = 62421
thieving_watchman = 62422
thieving_menaphite_thug = 62423
thieving_paladin = 62424
thieving_gnome = 62425
thieving_hero = 62426
thieving_vyre = 62427
thieving_elf = 62428
thieving_tzhaar_hur = 62429
cakethiefstall_thieving = 62450
tea_stall_thieving = 62451
silkthiefstall_thieving = 62452
furthiefstall_thieving = 62453
silverthiefstall_thieving = 62454
spicethiefstall_thieving = 62455
gemthiefstall_thieving = 62456
rag_market_stall_thieving = 62457
seed_stall_thieving = 62458
thieving_coin_pouch_citizen = 62460
thieving_coin_pouch_farmer = 62461
thieving_coin_pouch_ham = 62462
thieving_coin_pouch_warrior = 62463
thieving_coin_pouch_rogue = 62464
thieving_coin_pouch_cavegoblin = 62465
thieving_coin_pouch_guard = 62466
thieving_coin_pouch_fremennik = 62467
thieving_coin_pouch_bandit2 = 62468
thieving_coin_pouch_varlamore_wealthy = 62469
thieving_coin_pouch_desertbandit = 62470
thieving_coin_pouch_knight = 62471
thieving_coin_pouch_bandit = 62472
thieving_coin_pouch_watchman = 62473
thieving_coin_pouch_menaphite = 62474
thieving_coin_pouch_paladin = 62475
thieving_coin_pouch_gnome = 62476
thieving_coin_pouch_hero = 62477
thieving_coin_pouch_vyre = 62478
thieving_coin_pouch_elf = 62479

[gamevals.synth]
thieving_stunned = 2727
