[gamevals.dbtable]
food=65510
potion=65509
potion_effect=65508

[gamevals.dbrow]
shrimp=64594
anchovies=64593
sardine=64592
herring=64591
mackerel=64590
cod=64589
trout=64588
pike=64587
salmon=64586
tuna=64585
cave_eel=64584
lava_eel=64583
lobster=64582
bass=64581
swordfish=64580
swordtip_squid=64579
ixcoztic_white=64578
monkfish=64577
jumbo_squid=64576
giant_krill=64575
haddock=64574
yellowfin=64573
shark=64572
halibut=64571
sea_turtle=64570
manta_ray=64569
dark_crab=64568
bluefin=64567
marlin=64566
cavefish=64565
tetra=64564
anglerfish=64563

bread=64562
peach=64561
onion=64560
potato=64559
cabbage=64558
banana=64557
tomato=64556
cheese=64555
lemon=64554
orange=64553
lime=64552
pineapple=64551
dwellberries=64550
jangerberries=64549
caerula_berries=64548
strawberry=64547
watermelon_slice=64546
papaya_fruit=64545
dragonfruit=64544
chocolate_bar=64543
edible_seaweed=64542

cooked_chicken=64541
cooked_meat=64540
ugthanki_kebab=64539
kebab=64538
locust_meat=64537
roe=64536
stew=64535
spicy_stew=64534
cooked_rabbit=64533
cooked_mystery_meat=64532
scrambled_egg=64531
caviar=64530
baguette=64529
giant_frog_legs=64528
cooked_chompy=64527
choc_ice=64526
pumpkin=64525
easter_egg=64524
cooked_oomlie=64523
cooked_sweetcorn=64522
roast_bird_meat=64521
roast_rabbit=64520
roast_beast_meat=64519
thin_snail_meat=64518
lean_snail_meat=64517
fat_snail_meat=64516
spider_on_stick=64515
spider_on_shaft=64514
cooked_jubbly=64513
cooked_wild_kebbit=64512
cooked_larupia=64511
cooked_barb_tailed_kebbit=64510
cooked_graahk=64509
cooked_kyatt=64508
cooked_dashing_kebbit=64507
cooked_fennec_fox=64506

potato_with_cheese=64505
tuna_potato=64504
curry=64503
baked_potato=64502
potato_with_butter=64501
chilli_potato=64500
egg_potato=64499
mushroom_potato=64498
bowl_of_chilli_con_carne=64497
egg_and_tomato=64496
mushroom_and_onion=64495
tuna_and_corn=64494
bat_shish=64493
green_gloop_soup=64492
frog_spawn_gumbo=64491
fried_mushrooms=64490
sauteed_mushrooms=64489
cave_eel_sushi=64488
frog_burger=64487
red_crab_meat=64486
blue_crab_meat=64485
rainbow_crab_meat=64484

jug_of_wine=64483
beer=64482
asgarnian_ale=64481
wizards_mind_bomb=64480
greenmans_ale=64479
dragon_bitter=64478
dwarven_stout=64477
cider=64476
axemans_folly=64475
chefs_delight=64474
slayers_respite=64473
grog=64472
vodka=64471
whisky=64470
gin=64469
brandy=64468
keg_of_beer=64467
kovacs_grog=64466
moonlight_mead=64465
fruit_blast=64464
premade_fruit_blast=64463
pineapple_punch=64462
premade_pineapple_punch=64461
short_green_guy=64460
premade_short_green_guy=64459
blurberry_special=64458
premade_blurberry_special=64457
drunk_dragon=64456
premade_drunk_dragon=64455
wizard_blizzard=64454
premade_wizard_blizzard=64453
chocolate_saturday=64452
premade_chocolate_saturday=64451

cake=64450
chocolate_cake=64449
redberry_pie=64448
meat_pie=64447
garden_pie=64446
fish_pie=64445
apple_pie=64444
botanical_pie=64443
mushroom_pie=64442
admiral_pie=64441
plain_pizza=64440
meat_pizza=64439
anchovy_pizza=64438
dragonfruit_pie=64437
pineapple_pizza=64436
wild_pie=64435
summer_pie=64434
toad_crunchies=64433
premade_toad_crunchies=64432
spicy_crunchies=64431
premade_spicy_crunchies=64430
worm_crunchies=64429
premade_worm_crunchies=64428
chocolate_chip_crunchies=64427
premade_chocolate_chip_crunchies=64426
fruit_batta=64425
premade_fruit_batta=64424
toad_batta=64423
premade_toad_batta=64422
worm_batta=64421
premade_worm_batta=64420
vegetable_batta=64419
premade_vegetable_batta=64418
cheese_tomato_batta=64417
premade_cheese_tomato_batta=64416
worm_hole=64415
premade_worm_hole=64414
vegetable_ball=64413
premade_vegetable_ball=64412
chocolate_bomb=64411
premade_chocolate_bomb=64410
tangled_toads_legs=64409
premade_tangled_toads_legs=64408
toads_legs=64407

crystal_paddlefish=64406
corrupted_paddlefish=64405
cooked_karambwan=64404
blighted_karambwan=64403
blighted_manta_ray=64402
blighted_anglerfish=64401
purple_sweets=64400
magic_cabbage=64399
cup_of_tea=64398
white_tree_fruit=64397
strange_fruit=64396
mint_cake=64395
rare_tuber=64394
tbone_steak=64393
moonlight_mead_keg=64392
mature_moonlight_mead=64391
mature_moonlight_mead_keg=64390

pot_of_cream=64389
sliced_banana=64388
orange_chunks=64387
orange_slices=64386
pineapple_chunks=64385
pineapple_ring=64384
lemon_chunks=64383
lemon_slices=64382
lime_chunks=64381
lime_slices=64380
king_worm=64379
equa_leaves=64378
cooked_ugthanki_meat=64377
giant_carp=64376
giant_frogspawn=64375
cooked_slimy_eel=64374
cooked_fishcake=64373
bowl_of_sweetcorn=64372
cooked_giant_crab_meat=64371
cooked_sunlight_antelope=64370
cooked_moonlight_antelope=64369
bowl_of_onion=64368
bowl_of_tomato=64367
bowl_of_chilli=64366
bowl_of_meat=64365
bowl_of_spicy_tomato=64364
onion_and_tomato=64363
spicy_meat=64362
scrambled_egg_bowl=64361
fried_onion=64360
aluft_fruit_blast=64359
aluft_pineapple_punch=64358
aluft_wizard_blizzard=64357
aluft_short_green_guy=64356
aluft_drunk_dragon=64355
aluft_chocolate_saturday=64354
aluft_blurberry_special=64353
aluft_fruit_batta=64352
aluft_toad_batta=64351
aluft_worm_batta=64350
aluft_vegetable_batta=64349
aluft_cheese_tomato_batta=64348
aluft_toad_crunchies=64347
aluft_spicy_crunchies=64346
aluft_worm_crunchies=64345
aluft_chocolate_chip_crunchies=64344
aluft_worm_hole=64343
aluft_vegetable_ball=64342
aluft_tangled_toads_legs=64341
aluft_chocolate_bomb=64340

# Potions
attack_potion=64339
antipoison=64338
strength_potion=64337
restore_potion=64336
energy_potion=64335
defence_potion=64334
agility_potion=64333
combat_potion=64332
prayer_potion=64331
super_attack=64330
superantipoison=64329
fishing_potion=64328
super_energy=64327
hunter_potion=64326
super_strength=64325
super_restore=64324
super_defence=64323
antifire=64322
super_antifire=64321
ranging_potion=64320
magic_potion=64319
zamorak_brew=64318
saradomin_brew=64317
bastion_potion=64316
battlemage_potion=64315
super_combat=64314
stamina_potion=64313
ancient_brew=64312
anti_venom_plus=64311
extended_anti_venom_plus=64310
blighted_super_restore=64309
sanfew_serum=64308
divine_super_attack=64307
divine_super_strength=64306
divine_super_defence=64305
divine_ranging=64304
divine_magic=64303
divine_bastion=64302
divine_battlemage=64301
divine_super_combat=64300

attack_mix=64299
strength_mix=64298
restore_mix=64297
energy_mix=64296
defence_mix=64295
agility_mix=64294
prayer_mix=64293
super_attack_mix=64292
superantipoison_mix=64291
fishing_mix=64290
super_energy_mix=64289
super_strength_mix=64288
super_restore_mix=64287
super_defence_mix=64286
antifire_mix=64285
ranging_mix=64284
magic_mix=64283
zamorak_mix=64282

prayer_regeneration=64281
anti_venom=64280
extended_antifire=64279
extended_super_antifire=64278
forgotten_brew=64277
menaphite_remedy=64276
guthix_rest=64275
super_fishing_potion=64274
extreme_energy_potion=64273
super_hunter_potion=64272
extended_stamina_potion=64271
extended_antifire_mix=64270
super_antifire_mix=64269
extended_super_antifire_mix=64268
armadyl_brew=64267
antipoison_mix=64266
combat_mix=64265
hunting_mix=64264
ancient_mix=64263
antidote_plus=64262
antidote_plus_plus=64261
antidote_plus_mix=64260
stamina_mix=64259
relicyms_balm=64258
relicyms_mix=64257
moonlight_potion=64256

nzone_overload=64255
nzone_absorption=64254
nzone_super_ranging=64253
nzone_super_magic=64252

cox_xerics_aid_weak=64251
cox_xerics_aid=64250
cox_xerics_aid_strong=64249
cox_revitalisation_weak=64248
cox_revitalisation=64247
cox_revitalisation_strong=64246
cox_prayer_enhance_weak=64245
cox_prayer_enhance=64244
cox_prayer_enhance_strong=64243
cox_overload_weak=64242
cox_overload=64241
cox_overload_strong=64240
cox_elder_potion_weak=64239
cox_elder_potion=64238
cox_elder_potion_strong=64237
cox_kodai_potion_weak=64236
cox_kodai_potion=64235
cox_kodai_potion_strong=64234
cox_twisted_potion_weak=64233
cox_twisted_potion=64232
cox_twisted_potion_strong=64231

toa_nectar=64230
toa_ambrosia=64229
toa_tears_of_elidinis=64228
toa_liquid_adrenaline=64227
toa_smelling_salts=64226
toa_silk_dressing=64225
toa_blessed_crystal_scarab=64224

effect_attack_boost=64223
effect_strength_boost=64222
effect_defence_boost=64221
effect_combat_boost=64220
effect_super_attack_boost=64219
effect_super_strength_boost=64218
effect_super_defence_boost=64217
effect_super_combat_boost=64216
effect_ranging_boost=64215
effect_magic_boost=64214
effect_agility_boost=64213
effect_fishing_boost=64212
effect_hunter_boost=64211
effect_prayer_regeneration=64210
effect_bastion_boost=64209
effect_battlemage_boost=64208
effect_restore_potion=64207
effect_prayer_restore=64206
effect_super_restore=64205
effect_energy_restore=64204
effect_super_energy_restore=64203
effect_stamina=64202
effect_antipoison=64201
effect_superantipoison=64200
effect_antifire=64199
effect_super_antifire=64198
effect_anti_venom_plus=64197
effect_extended_anti_venom_plus=64196
effect_sanfew_serum=64195
effect_saradomin_brew=64194
effect_zamorak_brew=64193
effect_ancient_brew=64192
effect_divine_super_attack_boost=64191
effect_divine_super_strength_boost=64190
effect_divine_super_defence_boost=64189
effect_divine_ranging_boost=64188
effect_divine_magic_boost=64187
effect_divine_bastion_boost=64186
effect_divine_battlemage_boost=64185
effect_divine_super_combat_boost=64184

effect_antidote_plus=64183
effect_antidote_plus_plus=64182
effect_nzone_overload=64181
effect_nzone_absorption=64180
effect_nzone_super_ranging=64179
effect_nzone_super_magic=64178
effect_anti_venom=64177
effect_extended_antifire=64176
effect_extended_super_antifire=64175
effect_forgotten_brew=64174
effect_menaphite_remedy=64173
effect_guthix_rest=64172
effect_sanfew_restore=64171
effect_super_fishing_boost=64170
effect_extreme_energy_restore=64169
effect_super_hunter_boost=64168
effect_extended_stamina=64167
effect_armadyl_brew=64166
effect_relicyms_balm=64165
effect_moonlight_potion=64164

effect_cox_xerics_aid_weak=64163
effect_cox_xerics_aid=64162
effect_cox_xerics_aid_strong=64161
effect_cox_revitalisation_weak=64160
effect_cox_revitalisation=64159
effect_cox_revitalisation_strong=64158
effect_cox_prayer_enhance_weak=64157
effect_cox_prayer_enhance=64156
effect_cox_prayer_enhance_strong=64155
effect_cox_overload_weak=64154
effect_cox_overload=64153
effect_cox_overload_strong=64152
effect_cox_elder_potion_weak=64151
effect_cox_elder_potion=64150
effect_cox_elder_potion_strong=64149
effect_cox_kodai_potion_weak=64148
effect_cox_kodai_potion=64147
effect_cox_kodai_potion_strong=64146
effect_cox_twisted_potion_weak=64145
effect_cox_twisted_potion=64144
effect_cox_twisted_potion_strong=64143

effect_toa_nectar=64142
effect_toa_ambrosia=64141
effect_toa_tears_of_elidinis=64140
effect_toa_liquid_adrenaline=64139
effect_toa_smelling_salts=64138
effect_toa_silk_dressing=64137
effect_toa_blessed_crystal_scarab=64136