[gamevals.dbtable]
food=65511
potion=65510
potion_effect=65509

[gamevals.dbrow]
shrimp=64596
anchovies=64595
sardine=64594
herring=64593
mackerel=64592
cod=64591
trout=64590
pike=64589
salmon=64588
tuna=64587
cave_eel=64586
lava_eel=64585
lobster=64584
bass=64583
swordfish=64582
swordtip_squid=64581
ixcoztic_white=64580
monkfish=64579
jumbo_squid=64578
giant_krill=64577
haddock=64576
yellowfin=64575
shark=64574
halibut=64573
sea_turtle=64572
manta_ray=64571
dark_crab=64570
bluefin=64569
marlin=64568
cavefish=64567
tetra=64566
anglerfish=64565

bread=64564
peach=64563
onion=64562
potato=64561
cabbage=64560
banana=64559
tomato=64558
cheese=64557
lemon=64556
orange=64555
lime=64554
pineapple=64553
dwellberries=64552
jangerberries=64551
caerula_berries=64550
strawberry=64549
watermelon_slice=64548
papaya_fruit=64547
dragonfruit=64546
chocolate_bar=64545
edible_seaweed=64544

cooked_chicken=64543
cooked_meat=64542
ugthanki_kebab=64541
kebab=64540
locust_meat=64539
roe=64538
stew=64537
spicy_stew=64536
cooked_rabbit=64535
cooked_mystery_meat=64534
scrambled_egg=64533
caviar=64532
baguette=64531
giant_frog_legs=64530
cooked_chompy=64529
choc_ice=64528
pumpkin=64527
easter_egg=64526
cooked_oomlie=64525
cooked_sweetcorn=64524
roast_bird_meat=64523
roast_rabbit=64522
roast_beast_meat=64521
thin_snail_meat=64520
lean_snail_meat=64519
fat_snail_meat=64518
spider_on_stick=64517
spider_on_shaft=64516
cooked_jubbly=64515
cooked_wild_kebbit=64514
cooked_larupia=64513
cooked_barb_tailed_kebbit=64512
cooked_graahk=64511
cooked_kyatt=64510
cooked_dashing_kebbit=64509
cooked_fennec_fox=64508

potato_with_cheese=64507
tuna_potato=64506
curry=64505
baked_potato=64504
potato_with_butter=64503
chilli_potato=64502
egg_potato=64501
mushroom_potato=64500
bowl_of_chilli_con_carne=64499
egg_and_tomato=64498
mushroom_and_onion=64497
tuna_and_corn=64496
bat_shish=64495
green_gloop_soup=64494
frog_spawn_gumbo=64493
fried_mushrooms=64492
sauteed_mushrooms=64491
cave_eel_sushi=64490
frog_burger=64489
red_crab_meat=64488
blue_crab_meat=64487
rainbow_crab_meat=64486

jug_of_wine=64485
beer=64484
asgarnian_ale=64483
wizards_mind_bomb=64482
greenmans_ale=64481
dragon_bitter=64480
dwarven_stout=64479
cider=64478
axemans_folly=64477
chefs_delight=64476
slayers_respite=64475
grog=64474
vodka=64473
whisky=64472
gin=64471
brandy=64470
keg_of_beer=64469
kovacs_grog=64468
moonlight_mead=64467
fruit_blast=64466
premade_fruit_blast=64465
pineapple_punch=64464
premade_pineapple_punch=64463
short_green_guy=64462
premade_short_green_guy=64461
blurberry_special=64460
premade_blurberry_special=64459
drunk_dragon=64458
premade_drunk_dragon=64457
wizard_blizzard=64456
premade_wizard_blizzard=64455
chocolate_saturday=64454
premade_chocolate_saturday=64453

cake=64452
chocolate_cake=64451
redberry_pie=64450
meat_pie=64449
garden_pie=64448
fish_pie=64447
apple_pie=64446
botanical_pie=64445
mushroom_pie=64444
admiral_pie=64443
plain_pizza=64442
meat_pizza=64441
anchovy_pizza=64440
dragonfruit_pie=64439
pineapple_pizza=64438
wild_pie=64437
summer_pie=64436
toad_crunchies=64435
premade_toad_crunchies=64434
spicy_crunchies=64433
premade_spicy_crunchies=64432
worm_crunchies=64431
premade_worm_crunchies=64430
chocolate_chip_crunchies=64429
premade_chocolate_chip_crunchies=64428
fruit_batta=64427
premade_fruit_batta=64426
toad_batta=64425
premade_toad_batta=64424
worm_batta=64423
premade_worm_batta=64422
vegetable_batta=64421
premade_vegetable_batta=64420
cheese_tomato_batta=64419
premade_cheese_tomato_batta=64418
worm_hole=64417
premade_worm_hole=64416
vegetable_ball=64415
premade_vegetable_ball=64414
chocolate_bomb=64413
premade_chocolate_bomb=64412
tangled_toads_legs=64411
premade_tangled_toads_legs=64410
toads_legs=64409

crystal_paddlefish=64408
corrupted_paddlefish=64407
cooked_karambwan=64406
blighted_karambwan=64405
blighted_manta_ray=64404
blighted_anglerfish=64403
purple_sweets=64402
magic_cabbage=64401
cup_of_tea=64400
white_tree_fruit=64399
strange_fruit=64398
mint_cake=64397
rare_tuber=64396
tbone_steak=64395
moonlight_mead_keg=64394
mature_moonlight_mead=64393
mature_moonlight_mead_keg=64392

pot_of_cream=64391
sliced_banana=64390
orange_chunks=64389
orange_slices=64388
pineapple_chunks=64387
pineapple_ring=64386
lemon_chunks=64385
lemon_slices=64384
lime_chunks=64383
lime_slices=64382
king_worm=64381
equa_leaves=64380
cooked_ugthanki_meat=64379
giant_carp=64378
giant_frogspawn=64377
cooked_slimy_eel=64376
cooked_fishcake=64375
bowl_of_sweetcorn=64374
cooked_giant_crab_meat=64373
cooked_sunlight_antelope=64372
cooked_moonlight_antelope=64371
bowl_of_onion=64370
bowl_of_tomato=64369
bowl_of_chilli=64368
bowl_of_meat=64367
bowl_of_spicy_tomato=64366
onion_and_tomato=64365
spicy_meat=64364
scrambled_egg_bowl=64363
fried_onion=64362
aluft_fruit_blast=64361
aluft_pineapple_punch=64360
aluft_wizard_blizzard=64359
aluft_short_green_guy=64358
aluft_drunk_dragon=64357
aluft_chocolate_saturday=64356
aluft_blurberry_special=64355
aluft_fruit_batta=64354
aluft_toad_batta=64353
aluft_worm_batta=64352
aluft_vegetable_batta=64351
aluft_cheese_tomato_batta=64350
aluft_toad_crunchies=64349
aluft_spicy_crunchies=64348
aluft_worm_crunchies=64347
aluft_chocolate_chip_crunchies=64346
aluft_worm_hole=64345
aluft_vegetable_ball=64344
aluft_tangled_toads_legs=64343
aluft_chocolate_bomb=64342

# Potions
attack_potion=64341
antipoison=64340
strength_potion=64339
restore_potion=64338
energy_potion=64337
defence_potion=64336
agility_potion=64335
combat_potion=64334
prayer_potion=64333
super_attack=64332
superantipoison=64331
fishing_potion=64330
super_energy=64329
hunter_potion=64328
super_strength=64327
super_restore=64326
super_defence=64325
antifire=64324
super_antifire=64323
ranging_potion=64322
magic_potion=64321
zamorak_brew=64320
saradomin_brew=64319
bastion_potion=64318
battlemage_potion=64317
super_combat=64316
stamina_potion=64315
ancient_brew=64314
anti_venom_plus=64313
extended_anti_venom_plus=64312
blighted_super_restore=64311
sanfew_serum=64310
divine_super_attack=64309
divine_super_strength=64308
divine_super_defence=64307
divine_ranging=64306
divine_magic=64305
divine_bastion=64304
divine_battlemage=64303
divine_super_combat=64302

attack_mix=64301
strength_mix=64300
restore_mix=64299
energy_mix=64298
defence_mix=64297
agility_mix=64296
prayer_mix=64295
super_attack_mix=64294
superantipoison_mix=64293
fishing_mix=64292
super_energy_mix=64291
super_strength_mix=64290
super_restore_mix=64289
super_defence_mix=64288
antifire_mix=64287
ranging_mix=64286
magic_mix=64285
zamorak_mix=64284

prayer_regeneration=64283
anti_venom=64282
extended_antifire=64281
extended_super_antifire=64280
forgotten_brew=64279
menaphite_remedy=64278
guthix_rest=64277
super_fishing_potion=64276
extreme_energy_potion=64275
super_hunter_potion=64274
extended_stamina_potion=64273
extended_antifire_mix=64272
super_antifire_mix=64271
extended_super_antifire_mix=64270
armadyl_brew=64269
antipoison_mix=64268
combat_mix=64267
hunting_mix=64266
ancient_mix=64265
antidote_plus=64264
antidote_plus_plus=64263
antidote_plus_mix=64262
stamina_mix=64261
relicyms_balm=64260
relicyms_mix=64259
moonlight_potion=64258

nzone_overload=64257
nzone_absorption=64256
nzone_super_ranging=64255
nzone_super_magic=64254

cox_xerics_aid_weak=64253
cox_xerics_aid=64252
cox_xerics_aid_strong=64251
cox_revitalisation_weak=64250
cox_revitalisation=64249
cox_revitalisation_strong=64248
cox_prayer_enhance_weak=64247
cox_prayer_enhance=64246
cox_prayer_enhance_strong=64245
cox_overload_weak=64244
cox_overload=64243
cox_overload_strong=64242
cox_elder_potion_weak=64241
cox_elder_potion=64240
cox_elder_potion_strong=64239
cox_kodai_potion_weak=64238
cox_kodai_potion=64237
cox_kodai_potion_strong=64236
cox_twisted_potion_weak=64235
cox_twisted_potion=64234
cox_twisted_potion_strong=64233

toa_nectar=64232
toa_ambrosia=64231
toa_tears_of_elidinis=64230
toa_liquid_adrenaline=64229
toa_smelling_salts=64227
toa_silk_dressing=64226
toa_blessed_crystal_scarab=64225

effect_attack_boost=64224
effect_strength_boost=64223
effect_defence_boost=64222
effect_combat_boost=64221
effect_super_attack_boost=64220
effect_super_strength_boost=64219
effect_super_defence_boost=64218
effect_super_combat_boost=64217
effect_ranging_boost=64216
effect_magic_boost=64215
effect_agility_boost=64214
effect_fishing_boost=64213
effect_hunter_boost=64212
effect_prayer_regeneration=64211
effect_bastion_boost=64210
effect_battlemage_boost=64209
effect_restore_potion=64208
effect_prayer_restore=64207
effect_super_restore=64206
effect_energy_restore=64205
effect_super_energy_restore=64204
effect_stamina=64203
effect_antipoison=64202
effect_superantipoison=64201
effect_antifire=64200
effect_super_antifire=64199
effect_anti_venom_plus=64198
effect_extended_anti_venom_plus=64197
effect_sanfew_serum=64196
effect_saradomin_brew=64195
effect_zamorak_brew=64194
effect_ancient_brew=64193
effect_divine_super_attack_boost=64192
effect_divine_super_strength_boost=64191
effect_divine_super_defence_boost=64190
effect_divine_ranging_boost=64189
effect_divine_magic_boost=64188
effect_divine_bastion_boost=64187
effect_divine_battlemage_boost=64186
effect_divine_super_combat_boost=64185

effect_antidote_plus=64184
effect_antidote_plus_plus=64183
effect_nzone_overload=64182
effect_nzone_absorption=64181
effect_nzone_super_ranging=64180
effect_nzone_super_magic=64179
effect_anti_venom=64178
effect_extended_antifire=64177
effect_extended_super_antifire=64176
effect_forgotten_brew=64175
effect_menaphite_remedy=64174
effect_guthix_rest=64173
effect_sanfew_restore=64172
effect_super_fishing_boost=64171
effect_extreme_energy_restore=64170
effect_super_hunter_boost=64169
effect_extended_stamina=64168
effect_armadyl_brew=64167
effect_relicyms_balm=64166
effect_moonlight_potion=64165

effect_cox_xerics_aid_weak=64164
effect_cox_xerics_aid=64163
effect_cox_xerics_aid_strong=64162
effect_cox_revitalisation_weak=64161
effect_cox_revitalisation=64160
effect_cox_revitalisation_strong=64159
effect_cox_prayer_enhance_weak=64158
effect_cox_prayer_enhance=64157
effect_cox_prayer_enhance_strong=64156
effect_cox_overload_weak=64155
effect_cox_overload=64154
effect_cox_overload_strong=64153
effect_cox_elder_potion_weak=64152
effect_cox_elder_potion=64151
effect_cox_elder_potion_strong=64150
effect_cox_kodai_potion_weak=64149
effect_cox_kodai_potion=64148
effect_cox_kodai_potion_strong=64147
effect_cox_twisted_potion_weak=64146
effect_cox_twisted_potion=64145
effect_cox_twisted_potion_strong=64144

effect_toa_nectar=64143
effect_toa_ambrosia=64142
effect_toa_tears_of_elidinis=64141
effect_toa_liquid_adrenaline=64140
effect_toa_smelling_salts=64139
effect_toa_silk_dressing=64138
effect_toa_blessed_crystal_scarab=64137
