[gamevals.varp]
toa_personal_invocations_a = 64000
toa_personal_invocations_b = 64001
toa_personal_invocations_c = 64002
toa_personal_kc_requirement = 64003
toa_retrieval_locked = 64004
toa_attempts_entry = 64005
toa_attempts_normal = 64006
toa_attempts_expert = 64007
toa_deaths_entry = 64008
toa_deaths_normal = 64009
toa_deaths_expert = 64010
toa_best_challenge_entry_1 = 64011
toa_best_challenge_entry_2 = 64012
toa_best_challenge_entry_3 = 64013
toa_best_challenge_entry_4 = 64014
toa_best_challenge_entry_5 = 64015
toa_best_challenge_entry_6 = 64016
toa_best_challenge_entry_7 = 64017
toa_best_challenge_entry_8 = 64018
toa_best_overall_entry_1 = 64019
toa_best_overall_entry_2 = 64020
toa_best_overall_entry_3 = 64021
toa_best_overall_entry_4 = 64022
toa_best_overall_entry_5 = 64023
toa_best_overall_entry_6 = 64024
toa_best_overall_entry_7 = 64025
toa_best_overall_entry_8 = 64026
toa_best_challenge_normal_1 = 64027
toa_best_challenge_normal_2 = 64028
toa_best_challenge_normal_3 = 64029
toa_best_challenge_normal_4 = 64030
toa_best_challenge_normal_5 = 64031
toa_best_challenge_normal_6 = 64032
toa_best_challenge_normal_7 = 64033
toa_best_challenge_normal_8 = 64034
toa_best_overall_normal_1 = 64035
toa_best_overall_normal_2 = 64036
toa_best_overall_normal_3 = 64037
toa_best_overall_normal_4 = 64038
toa_best_overall_normal_5 = 64039
toa_best_overall_normal_6 = 64040
toa_best_overall_normal_7 = 64041
toa_best_overall_normal_8 = 64042
toa_best_challenge_expert_1 = 64043
toa_best_challenge_expert_2 = 64044
toa_best_challenge_expert_3 = 64045
toa_best_challenge_expert_4 = 64046
toa_best_challenge_expert_5 = 64047
toa_best_challenge_expert_6 = 64048
toa_best_challenge_expert_7 = 64049
toa_best_challenge_expert_8 = 64050
toa_best_overall_expert_1 = 64051
toa_best_overall_expert_2 = 64052
toa_best_overall_expert_3 = 64053
toa_best_overall_expert_4 = 64054
toa_best_overall_expert_5 = 64055
toa_best_overall_expert_6 = 64056
toa_best_overall_expert_7 = 64057
toa_best_overall_expert_8 = 64058
toa_temp_state = 64059

[gamevals.varbit]
toa_protect_item_at_death = 64000
toa_party_tab = 64001

[gamevals.area]
toa_lobby = 60
toa_raid = 61

[gamevals.queue]
toa_death = 61

[gamevals.midi]
toa_ambience = 730
toa_boss_zebak = 736

[gamevals.synth]
toa_crondis_fill_container = 6522
toa_crondis_water_empty = 6524
toa_crondis_water_tree_02 = 6534
toa_crondis_tree_grow_02 = 6516
toa_crondis_water_lost_02 = 6529
toa_crondis_croc_spear_trap_spear_expand_04 = 6493
liquid = 2401
mory_vanstrom_orb_spawn = 4424
crocodile_attack = 386
toa_zebak_red_projectile_04 = 5823
toa_zebak_whoosh_projectile_02 = 5819
toa_zebak_redirected_jug_break_01 = 5878
toa_zebak_redirected_projectile_02 = 5896
toa_zebak_projectile_impact_01 = 5884
toa_zebak_defend_01 = 6590
fi_trollking_roar = 3405
toa_zebak_vomit_colours_projectile_10 = 5908
toa_zebak_vomit_colours_projectile_splat_03 = 5909
toa_zebak_debris_impact_01 = 5913
toa_zebak_roar_single_tremor_03 = 5888
toa_zebak_attack_hand_stomp_first_01 = 5860
toa_zebak_attack_roar_05 = 5836
toa_zebak_attack_hand_stomp_01 = 5845
toa_zebak_attack_roar_high_02 = 5904
toa_zebak_attack_roar_bass_02 = 5838
toa_zebak_attack_hand_stomp_final_01 = 5851
toa_zebak_attack_jaw_shut_01 = 5863
toa_zebak_falling_rocks_sweep_01 = 5882
toa_zebak_fallling_rocks_water_impact_01 = 5843
toa_zebak_tidal_wave_7600ms_01 = 5852
toa_zebak_death_second_floor_hit_01 = 5868
watersplash = 2496
toa_zebak_jug_break_02 = 5869

[gamevals.projanim]
toa_zebak_initial = 65535
toa_zebak_split = 65534
toa_zebak_poison_spread = 65533
toa_zebak_lob = 65532
toa_zebak_jug_splash = 65531
toa_zebak_lob_far = 65530
