[[enum]]
isServerOnly = true
id = "enum.fletching_anims"
keyType = "OBJ"
valueType = "SEQ"

[enum.values]
"obj.adamant_arrow" = "seq.human_fletching_add_arrow_tips"
"obj.adamant_dart" = "seq.human_fletching_add_dart_feathers_adamant"
"obj.amethyst_arrow" = "seq.human_fletching_add_arrow_tips"
"obj.amethyst_dart" = "seq.human_fletching_add_dart_feathers_amethyst"
"obj.barbed_bolt" = "seq.human_fletching_add_bolt_tips_bronze"
"obj.bolt" = "seq.human_fletching_add_bolt_feathers_bronze"
"obj.bronze_arrow" = "seq.human_fletching_add_arrow_tips"
"obj.bronze_dart" = "seq.human_fletching_add_dart_feathers_bronze"
"obj.dragon_arrow" = "seq.human_fletching_add_arrow_tips"
"obj.dragon_bolts" = "seq.human_fletching_add_bolt_feathers_dragon"
"obj.dragon_bolts_unenchanted_diamond" = "seq.human_fletching_add_bolt_tips_dragon"
"obj.dragon_bolts_unenchanted_dragonstone" = "seq.human_fletching_add_bolt_tips_dragon"
"obj.dragon_bolts_unenchanted_emerald" = "seq.human_fletching_add_bolt_tips_dragon"
"obj.dragon_bolts_unenchanted_jade" = "seq.human_fletching_add_bolt_tips_dragon"
"obj.dragon_bolts_unenchanted_onyx" = "seq.human_fletching_add_bolt_tips_dragon"
"obj.dragon_bolts_unenchanted_opal" = "seq.human_fletching_add_bolt_tips_dragon"
"obj.dragon_bolts_unenchanted_pearl" = "seq.human_fletching_add_bolt_tips_dragon"
"obj.dragon_bolts_unenchanted_ruby" = "seq.human_fletching_add_bolt_tips_dragon"
"obj.dragon_bolts_unenchanted_sapphire" = "seq.human_fletching_add_bolt_tips_dragon"
"obj.dragon_bolts_unenchanted_topaz" = "seq.human_fletching_add_bolt_tips_dragon"
"obj.dragon_dart" = "seq.human_fletching_add_dart_feathers_dragon"
"obj.headless_arrow" = "seq.human_fletching_add_feather"
"obj.headless_atlatl_dart" = "seq.human_fletching_add_feather"
"obj.iron_arrow" = "seq.human_fletching_add_arrow_tips"
"obj.iron_dart" = "seq.human_fletching_add_dart_feathers_iron"
"obj.longbow" = "seq.stringing_longbow"
"obj.magic_longbow" = "seq.stringing_magic_longbow"
"obj.magic_shortbow" = "seq.stringing_magic_shortbow"
"obj.maple_longbow" = "seq.stringing_maple_longbow"
"obj.maple_shortbow" = "seq.stringing_maple_shortbow"
"obj.mithril_arrow" = "seq.human_fletching_add_arrow_tips"
"obj.mithril_dart" = "seq.human_fletching_add_dart_feathers_mithril"
"obj.oak_longbow" = "seq.stringing_oak_longbow"
"obj.oak_shortbow" = "seq.stringing_oak_shortbow"
"obj.ogre_headless_arrow" = "seq.human_fletching_add_feather"
"obj.opal_bolt" = "seq.human_fletching_add_bolt_tips_bronze"
"obj.pearl_bolt" = "seq.human_fletching_add_bolt_tips_iron"
"obj.rune_arrow" = "seq.human_fletching_add_arrow_tips"
"obj.rune_dart" = "seq.human_fletching_add_dart_feathers_rune"
"obj.seeking_adamant_arrow" = "seq.human_fletching_add_arrow_tips"
"obj.seeking_amethyst_arrow" = "seq.human_fletching_add_arrow_tips"
"obj.seeking_bronze_arrow" = "seq.human_fletching_add_arrow_tips"
"obj.seeking_dragon_arrow" = "seq.human_fletching_add_arrow_tips"
"obj.seeking_headless_arrow" = "seq.human_fletching_add_feather"
"obj.seeking_iron_arrow" = "seq.human_fletching_add_arrow_tips"
"obj.seeking_mithril_arrow" = "seq.human_fletching_add_arrow_tips"
"obj.seeking_rune_arrow" = "seq.human_fletching_add_arrow_tips"
"obj.seeking_slayer_broad_arrows" = "seq.human_fletching_add_arrow_tips"
"obj.seeking_steel_arrow" = "seq.human_fletching_add_arrow_tips"
"obj.shortbow" = "seq.stringing_shortbow"
"obj.slayer_broad_arrows" = "seq.human_fletching_add_arrow_tips"
"obj.steel_arrow" = "seq.human_fletching_add_arrow_tips"
"obj.steel_dart" = "seq.human_fletching_add_dart_feathers_steel"
"obj.willow_longbow" = "seq.stringing_willow_longbow"
"obj.willow_shortbow" = "seq.stringing_willow_shortbow"
"obj.xbows_crossbow_adamantite" = "seq.xbows_stringing_crossbow_adamantite"
"obj.xbows_crossbow_blurite" = "seq.xbows_stringing_crossbow_blurite"
"obj.xbows_crossbow_bolts_adamantite" = "seq.human_fletching_add_bolt_feathers_adamant"
"obj.xbows_crossbow_bolts_adamantite_tipped_diamond" = "seq.human_fletching_add_bolt_tips_adamant"
"obj.xbows_crossbow_bolts_adamantite_tipped_ruby" = "seq.human_fletching_add_bolt_tips_adamant"
"obj.xbows_crossbow_bolts_blurite" = "seq.human_fletching_add_bolt_feathers_blurite"
"obj.xbows_crossbow_bolts_blurite_tipped_jade" = "seq.human_fletching_add_bolt_tips_blurite"
"obj.xbows_crossbow_bolts_iron" = "seq.human_fletching_add_bolt_feathers_iron"
"obj.xbows_crossbow_bolts_mithril" = "seq.human_fletching_add_bolt_feathers_mithril"
"obj.xbows_crossbow_bolts_mithril_tipped_emerald" = "seq.human_fletching_add_bolt_tips_mithril"
"obj.xbows_crossbow_bolts_mithril_tipped_sapphire" = "seq.human_fletching_add_bolt_tips_mithril"
"obj.xbows_crossbow_bolts_runite" = "seq.human_fletching_add_bolt_feathers_rune"
"obj.xbows_crossbow_bolts_runite_tipped_dragonstone" = "seq.human_fletching_add_bolt_tips_rune"
"obj.xbows_crossbow_bolts_runite_tipped_onyx" = "seq.human_fletching_add_bolt_tips_rune"
"obj.xbows_crossbow_bolts_silver" = "seq.human_fletching_add_bolt_feathers_silver"
"obj.xbows_crossbow_bolts_steel" = "seq.human_fletching_add_bolt_feathers_steel"
"obj.xbows_crossbow_bolts_steel_tipped_redtopaz" = "seq.human_fletching_add_bolt_tips_steel"
"obj.xbows_crossbow_bronze" = "seq.xbows_stringing_crossbow_bronze"
"obj.xbows_crossbow_dragon" = "seq.xbows_stringing_crossbow_dragon"
"obj.xbows_crossbow_iron" = "seq.xbows_stringing_crossbow_iron"
"obj.xbows_crossbow_mithril" = "seq.xbows_stringing_crossbow_mithril"
"obj.xbows_crossbow_runite" = "seq.xbows_stringing_crossbow_runite"
"obj.xbows_crossbow_steel" = "seq.xbows_stringing_crossbow_steel"
"obj.yew_longbow" = "seq.stringing_yew_longbow"
"obj.yew_shortbow" = "seq.stringing_yew_shortbow"
