[[inventory]]
isServerOnly = true
id = "inv.inv"
inherit = "inv.inv"

scope = "Perm"
protect = false
runWeight = true

[[inventory]]
isServerOnly = true
id = "inv.worn"
inherit = "inv.worn"

scope = "Perm"
protect = false
runWeight = true

[[inventory]]
isServerOnly = true
id = "inv.bank"
inherit = "inv.bank"

scope = "Perm"
stack = "Always"
protect = false
placeholders = true
uimBlocked = true

[[inventory]]
isServerOnly = true
id = "inv.tradeoffer"
inherit = "inv.tradeoffer"
size = 28
scope = "Perm"
protect = true

[[inventory]]
isServerOnly = true
id = "inv.skill_guide_hunting_tracking"
inherit = "inv.skill_guide_hunting_tracking"
stack = "Never"

[[inventory]]
isServerOnly = true
id = "inv.collection_transmit"
inherit = "inv.collection_transmit"
size = 2000
scope = "Perm"
stack = "Always"
protect = false

[[inventory]]
isServerOnly = true
id = "inv.poh_costume_room_armour_inv"
inherit = "inv.poh_costume_room_armour_inv"
size = 100
scope = "Perm"
stack = "Always"
protect = false

[[inventory]]
isServerOnly = true
id = "inv.poh_costume_room_capes_inv"
inherit = "inv.poh_costume_room_capes_inv"
size = 100
scope = "Perm"
stack = "Always"
protect = false

[[inventory]]
isServerOnly = true
id = "inv.poh_costume_room_magic_wardrobe_inv"
inherit = "inv.poh_costume_room_magic_wardrobe_inv"
size = 100
scope = "Perm"
stack = "Always"
protect = false

[[inventory]]
isServerOnly = true
id = "inv.poh_costume_room_holiday_items_inv"
inherit = "inv.poh_costume_room_holiday_items_inv"
size = 100
scope = "Perm"
stack = "Always"
protect = false

[[inventory]]
isServerOnly = true
id = "inv.poh_costume_room_ame_inv"
inherit = "inv.poh_costume_room_ame_inv"
size = 100
scope = "Perm"
stack = "Always"
protect = false

[[inventory]]
isServerOnly = true
id = "inv.poh_costume_room_treasure_trail_0_inv"
inherit = "inv.poh_costume_room_treasure_trail_0_inv"
size = 100
scope = "Perm"
stack = "Always"
protect = false

[[inventory]]
isServerOnly = true
id = "inv.poh_costume_room_treasure_trail_1_inv"
inherit = "inv.poh_costume_room_treasure_trail_1_inv"
size = 100
scope = "Perm"
stack = "Always"
protect = false

[[inventory]]
isServerOnly = true
id = "inv.poh_costume_room_treasure_trail_2_inv"
inherit = "inv.poh_costume_room_treasure_trail_2_inv"
size = 100
scope = "Perm"
stack = "Always"
protect = false

[[inventory]]
isServerOnly = true
id = "inv.poh_costume_room_treasure_trail_3_inv"
inherit = "inv.poh_costume_room_treasure_trail_3_inv"
size = 100
scope = "Perm"
stack = "Always"
protect = false
