[gamevals.tables]
consumable_food=1224

[gamevals.dbrows]
premade_choc_bomb_food=97097
shrimps_food=98030
cooked_chicken_food=98031
cooked_meat_food=98032
bread_food=98033
anchovies_food= 97096
herring_food=98034
mackerel_food=98035
trout_food=98036
pike_food=98037
peach_food=98038
salmon_food=98039
tuna_food=98040
jug_of_wine_food=98041
lobster_food=98042
bass_food=98043
swordfish_food=98044
ixcoztic_white_food=98045
potato_with_cheese_food=98046
monkfish_food=98047
curry_food=98048
cooked_pyre_fox_food=98049
shark_food=98050
sea_turtle_food=98051
manta_ray_food=98052
tuna_potato_food=98053
dark_crab_food=98054
anglerfish_food=98055
onion_food=98056
cake_food=98057
chocolate_cake_food=98058
redberry_pie_food=98059
meat_pie_food=98060
garden_pie_food=98061
fish_pie_food=98062
apple_pie_food=98063
botanical_pie_food=98064
mushroom_pie_food=98065
admiral_pie_food=98066
plain_pizza_food=98067
meat_pizza_food=98068
anchovy_pizza_food=98069
dragonfruit_pie_food=98070
pineapple_pizza_food=98071
wild_pie_food=98072
summer_pie_food=98073
toad_crunchies_food=98074
premade_td_crunch_food=98075
spicy_crunchies_food=98076
premade_sy_crunch_food=98077
worm_crunchies_food=98078
premade_wm_crun_food=98079
chocchip_crunchies_food=98080
premade_ch_crunch_food=98081
fruit_batta_food=98082
premade_frt_batta_food=98083
toad_batta_food=98084
premade_td_batta_food=98085
worm_batta_food=98086
premade_wm_batta_food=98087
vegetable_batta_food=98088
premade_veg_batta_food=98089
cheese_tom_batta_food=98090
premade_ct_batta_food=98091
worm_hole_food=98092
premade_worm_hole_food=98093
veg_ball_food=98094
premade_veg_ball_food=98095
chocolate_bomb_food=98096
tangled_toads_legs_food=98098
premade_ttl_food=98099
toads_legs_food=98100
crystal_paddlefish_food=98101
corrupted_paddlefish_food=98102
cooked_karambwan_food=98103
blighted_karambwan_food=98104
blighted_manta_ray_food=98105
blighted_anglerfish_food=98106
sweets_food=98107
moonlight_mead_food=98108
asgarnian_ale_food= 97038
axemans_folly_food= 97039
baguette_food= 97040
baked_potato_food= 97041
banana_food= 97042
bat_shish_food= 97043
beer_food= 97044
blue_crab_meat_food= 97045
bluefin_food= 97046
blurberry_special_food= 97047
bowl_of_chilli_con_carne_food= 97048
brandy_food= 97049
cabbage_food= 97050
caerula_berries_food= 97051
cave_eel_food= 97052
cave_eel_sushi_food= 97053
cavefish_food= 97054
caviar_food= 97055
cheese_food= 97056
chefs_delight_food= 97057
chilli_potato_food= 97058
choc_ice_food= 97059
chocolate_bar_food= 97060
chocolate_saturday_food= 97061
cider_food= 97062
cod_food= 97063
cooked_barb_tailed_kebbit_food= 97064
cooked_chompy_food= 97065
cooked_dashing_kebbit_food= 97066
cooked_graahk_food= 97067
cooked_jubbly_food= 97068
cooked_kyatt_food= 97069
cooked_larupia_food= 97070
cooked_mystery_meat_food= 97071
cooked_rabbit_food= 97072
cooked_sweetcorn_food= 97073
cooked_wild_kebbit_food= 97074
dragon_bitter_food= 97075
dragonfruit_food= 97076
drunk_dragon_food= 97077
dwarven_stout_food= 97078
dwellberries_food= 97079
easter_egg_food= 97080
edible_seaweed_food= 97081
egg_and_tomato_food= 97082
egg_potato_food= 97083
fat_snail_meat_food= 97084
fried_mushrooms_food= 97085
frog_burger_food= 97086
frog_spawn_gumbo_food= 97087
fruit_blast_food= 97088
giant_frog_legs_food= 97089
giant_krill_food= 97090
gin_food= 97091
green_gloop_soup_food= 97092
greenmans_ale_food= 97093
grog_food= 97094
haddock_food= 97095
halibut_food= 98155
jangerberries_food= 98156
jumbo_squid_food= 98157
kebab_food= 98186
keg_of_beer_food= 98210
kovacs_grog_food= 98211
lava_eel_food= 98212
lean_snail_meat_food= 98213
lemon_food= 98214
lime_food= 98215
locust_meat_food= 98216
marlin_food= 98217
mushroom_and_onion_food= 98218
mushroom_potato_food= 98219
orange_food= 98220
papaya_fruit_food= 98221
pineapple_food= 98222
pineapple_punch_food= 98223
potato_food= 98224
potato_with_butter_food= 98225
premade_blurberry_special_food= 98226
premade_choc_saturday_food= 98227
premade_drunk_dragon_food= 98228
premade_fruit_blast_food= 98229
premade_pineapple_punch_food= 98230
premade_sgg_food= 98231
premade_wizard_blizzard_food= 98232
pumpkin_food= 98233
rainbow_crab_meat_food= 98234
red_crab_meat_food= 98235
roast_beast_meat_food= 98236
roast_bird_meat_food= 98237
roast_rabbit_food= 98238
roe_food= 98239
sardine_food= 98240
sauteed_mushrooms_food= 98241
scrambled_egg_food= 98242
seasoned_sardine_food= 98243
short_green_guy_food= 98244
slayers_respite_food= 98245
spider_on_shaft_food= 98246
spider_on_stick_food= 98247
stew_food= 98248
strawberry_food= 98249
swordtip_squid_food= 98250
tetra_food= 98251
thin_snail_meat_food= 98252
tomato_food= 98253
tuna_and_corn_food= 98254
ugthanki_kebab_food= 98255
vodka_food= 98256
watermelon_slice_food= 98257
whisky_food= 98258
wizard_blizzard_food= 98259
wizards_mind_bomb_food= 98260
wrapped_oomlie_food= 98261
yellowfin_food= 98262