[gamevals.interface]
toolbelt = 15000

[gamevals.clientscript]
toolbelt_init = 45400
toolbelt_build = 45401
toolbelt_stored_for_row = 45402
toolbelt_draw = 45403
toolbelt_count_category = 45404
toolbelt_filter = 45405

[gamevals.dbtable]
toolbelt_slots = 55521

[gamevals.enum]
toolbelt_categories = 65541

[gamevals.dbrow]
toolbelt_pickaxe =64130
toolbelt_axe =64129
toolbelt_hammer =64128
toolbelt_chisel =64127
toolbelt_knife =64126
toolbelt_tinderbox =64125
toolbelt_pestle_and_mortar =64124
toolbelt_spade =64123
toolbelt_rake =64122
toolbelt_dibber =64121
toolbelt_secateurs =64120
toolbelt_gardening_trowel =64119
toolbelt_watering_can =64118
toolbelt_shears =64117
toolbelt_needle =64116
toolbelt_glassblowing_pipe =64115
toolbelt_small_net =64114
toolbelt_big_net =64113
toolbelt_fishing_rod =64112
toolbelt_fly_fishing_rod =64111
toolbelt_harpoon =64110
toolbelt_lobster_pot =64109
toolbelt_amulet_mould =64108
toolbelt_necklace_mould =64107
toolbelt_ring_mould =64106
toolbelt_bracelet_mould =64105
toolbelt_tiara_mould =64104
toolbelt_bonecrusher =64103

[gamevals.varp]
toolbelt_unlocks =65486
toolbelt_slot_0 =65480
toolbelt_slot_1 =65479
toolbelt_slot_2 =65478
toolbelt_slot_3 =65477
toolbelt_slot_4 =65476
toolbelt_slot_5 =65475
toolbelt_slot_6 =65474
toolbelt_slot_7 =65473
toolbelt_slot_8 =65472
toolbelt_slot_9 =65471
toolbelt_slot_10 =65470
toolbelt_slot_11 =65469
toolbelt_slot_12 =65468
toolbelt_slot_13 =65467
toolbelt_slot_14 =65466
toolbelt_slot_15 =65465
toolbelt_slot_16 =65464
toolbelt_slot_17 =65463
toolbelt_slot_18 =65462
toolbelt_slot_19 =65461
toolbelt_slot_20 =65460
toolbelt_slot_21 =65459
toolbelt_slot_22 =65458
toolbelt_slot_23 =65457
toolbelt_slot_24 =65456
toolbelt_slot_25 =65455
toolbelt_slot_26 =65454
toolbelt_slot_27 =65453

[gamevals.varbit]
toolbelt_slot_0 =65454
toolbelt_slot_1 =65453
toolbelt_slot_2 =65452
toolbelt_slot_3 =65451
toolbelt_slot_4 =65450
toolbelt_slot_5 =65449
toolbelt_slot_6 =65448
toolbelt_slot_7 =65447
toolbelt_slot_8 =65446
toolbelt_slot_9 =65445
toolbelt_slot_10 =65444
toolbelt_slot_11 =65443
toolbelt_slot_12 =65442
toolbelt_slot_13 =65441
toolbelt_slot_14 =65440
toolbelt_slot_15 =65439
toolbelt_slot_16 =65438
toolbelt_slot_17 =65437
toolbelt_slot_18 =65436
toolbelt_slot_19 =65435
toolbelt_slot_20 =65434
toolbelt_slot_21 =65433
toolbelt_slot_22 =65432
toolbelt_slot_23 =65431
toolbelt_slot_24 =65430
toolbelt_slot_25 =65429
toolbelt_slot_26 =65428
toolbelt_slot_27 =65427

[gamevals.sprites]
tool_belt = 21535
square_button = 21536
square_button_hover = 21537
square_button_clicked = 21538
square_button_disabled = 21539