[gamevals.dbtable]
skill_prayer=1226
prayer_blessed_bone=1227
prayer_ectofuntus_bonemeal=1228

[gamevals.queue]
prayer_ecto_collect_slime = 50
prayer_ecto_grinder = 49
prayer_libation_sacrifice = 45
prayer_make_sunfire_wine = 46
prayer_demonic_ruins_regen = 47
prayer_break_down_bone = 44
prayer_altar_sacrifice = 43
prayer_bury = 42

[gamevals.dbrow]
infernalashes=97002
abyssalashes=97003
maliciousashes=97004
vileashes=97005
fiendishashes=97006
beardedgorillabones=97007
gorillabones=97008
mediumninjamonkeybones=97009
smallninjamonkeybones=97010
largezombiemonkeybones=97011
smallzombiemonkeybones=97012
bleachedbones=97013
bonesapeatoll=97014
alansbones=97015
superiordragonbones=97016
ourgbones=97017
dagannothbones=97018
hydrabones=97019
raurgbones=97020
lavadragonbones=97021
fayrgbones=97022
drakebones=97023
dragonbones=97024
wyvernbones=97025
wyrmbones=97026
babydragonbones=97027
shaikahanbones=97028
zogrebones=97029
wyrmlingbones=97030
jogrebones=97031
bigbones=97032
batbones=97033
monkeybones=97034
burntbones=97035
wolfbones=97036
bones=97037
prayer_bb_blessed_bones=97038
prayer_bb_blessed_bat_bones=97039
prayer_bb_blessed_big_bones=97040
prayer_bb_blessed_zogre_bones=97041
prayer_bb_blessed_babywyrm_bones=97042
prayer_bb_blessed_babydragon_bones=97043
prayer_bb_blessed_strykewyrm_bones=97044
prayer_bb_blessed_wyrm_bones=97045
prayer_bb_sun_kissed_bones=97046
prayer_bb_blessed_wyvern_bones=97047
prayer_bb_blessed_dragon_bones=97048
prayer_bb_blessed_drake_bones=97049
prayer_bb_blessed_fayrg_bones=97050
prayer_bb_blessed_lava_dragon_bones=97051
prayer_bb_blessed_raurg_bones=97052
prayer_bb_blessed_frost_dragon_bones=97053
prayer_bb_blessed_hydra_bones=97054
prayer_bb_blessed_dagannoth_bones=97055
prayer_bb_blessed_ourg_bones=97056
prayer_bb_blessed_superior_dragon_bones=97057
prayer_bb_blessed_bone_statuette=97058
prayer_ecto_alan_bones=97059
prayer_ecto_bones=97060
prayer_ecto_bat_bones=97061
prayer_ecto_big_bones=97062
prayer_ecto_long_bone=97063
prayer_ecto_curved_bone=97064
prayer_ecto_burnt_bones=97065
prayer_ecto_burnt_jogre_bones=97066
prayer_ecto_babydragon_bones=97067
prayer_ecto_wyrmling_bones=97068
prayer_ecto_dragon_bones=97069
prayer_ecto_wolf_bones=97070
prayer_ecto_small_ninja_monkey_bones=97071
prayer_ecto_medium_ninja_monkey_bones=97072
prayer_ecto_gorilla_bones=97073
prayer_ecto_bearded_gorilla_bones=97074
prayer_ecto_monkey_bones=97075
prayer_ecto_small_zombie_monkey_bones=97076
prayer_ecto_large_zombie_monkey_bones=97077
prayer_ecto_ape_atoll_skeleton_bones=97078
prayer_ecto_jogre_bones=97079
prayer_ecto_zogre_bones=97080
prayer_ecto_fayrg_bones=97081
prayer_ecto_raurg_bones=97082
prayer_ecto_ourg_bones=97083
prayer_ecto_shaikahan_bones=97084
prayer_ecto_dagannoth_bones=97085
prayer_ecto_wyvern_bones=97086
prayer_ecto_lava_dragon_bones=97087
prayer_ecto_superior_dragon_bones=97088
prayer_ecto_frost_dragon_bones=97089
prayer_ecto_wyrm_bones=97090
prayer_ecto_strykewyrm_bones=97091
prayer_ecto_drake_bones=97092
prayer_ecto_hydra_bones=97093
