@file:Suppress("SpellCheckingInspection", "unused")

package org.rsmod.api.config.refs

import dev.openrune.varBit

typealias varbits = BaseVarBits

object BaseVarBits {
    val multiway_indicator = varBit("multiway_indicator")
    val singleway_plus_indicator = varBit("singleway_plus_indicator")

    val stamina_active = varBit("stamina_active")
    val stamina_duration = varBit("stamina_duration")
    val stamina_duration_extra = varBit("stamina_duration_extra")
    val buff_stamina_duration_disabled = varBit("buff_stamina_duration_disabled")

    val side_journal_tab = varBit("side_journal_tab")

    val rune_pouch_type_1 = varBit("rune_pouch_type_1")
    val rune_pouch_quantity_1 = varBit("rune_pouch_quantity_1")
    val rune_pouch_type_2 = varBit("rune_pouch_type_2")
    val rune_pouch_quantity_2 = varBit("rune_pouch_quantity_2")
    val rune_pouch_type_3 = varBit("rune_pouch_type_3")
    val rune_pouch_quantity_3 = varBit("rune_pouch_quantity_3")
    val rune_pouch_type_4 = varBit("rune_pouch_type_4")
    val rune_pouch_quantity_4 = varBit("rune_pouch_quantity_4")

    val fountain_of_rune_active = varBit("fountain_of_rune_active")
    val in_ba_game = varBit("barbassault_areaexit_pending")
    val in_lms_game = varBit("br_ingame")
    val blighted_items_allowed = varBit("blighted_items_allowed")

    val spellbook = varBit("spellbook")
    val buff_charge_spell_disabled = varBit("buff_charge_spell_disabled")
    val buff_mark_of_darkness_disabled = varBit("buff_mark_of_darkness_disabled")

    val combatlevel_transmit = varBit("combatlevel_transmit")
    val combatlevel_decimal_transmit = varBit("combatlevel_decimal_transmit")
    val autocast_set = varBit("autocast_set")
    val autocast_spell = varBit("autocast_spell")
    val autocast_defmode = varBit("autocast_defmode")

    val cutscene_status = varBit("cutscene_status")
    val fov_clamp = varBit("fov_clamp")
    val minimap_state = varBit("minimap_state")
    val gravestone_tli_hide = varBit("gravestone_tli_hide")

    val option_master_volume_saved = varBit("option_master_volume_saved")
    val option_music_saved = varBit("option_music_saved")
    val option_sounds_saved = varBit("option_sounds_saved")
    val option_areasounds_saved = varBit("option_areasounds_saved")
    val music_unlock_text_toggle = varBit("music_unlock_text_toggle")

    val music_area_mode = varBit("music_area_mode")
    val music_enableloop = varBit("music_enableloop")

    val option_brightness_remember = varBit("option_brightness_remember")
    val camera_zoom_mouse_disabled = varBit("camera_zoom_mouse_disabled")

    val chatbox_transparency = varBit("chatbox_transparency")
    val resizable_stone_arrangement = varBit("resizable_stone_arrangement")
    val skull_prevent = varBit("skull_prevent_enabled")
    val option_acceptaid = varBit("option_acceptaid")
    val has_displayname_transmitter = varBit("has_displayname_transmitter")
    val chatmodal_unclamp = varBit("chatmodal_unclamp")
    val option_hide_rooftops = varBit("option_hide_rooftops")
    val settings_hd_beta_enabled = varBit("settings_hd_beta_enabled")
    val settings_hd_beta_full_hd_or_fake_sd = varBit("settings_hd_beta_full_hd_or_fake_sd")
    val setting_hd_beta_flag = varBit("setting_hd_beta_flag")
    val option_dropwarning_on = varBit("option_dropwarning_on")
    val option_dropwarning_value = varBit("option_dropwarning_value")
    val combat_weapon_category = varBit("combat_weapon_category")
    val keybinding_esc_to_close = varBit("keybinding_esc_to_close")

    val demonslayer_main = varBit("demonslayer_main")
    val lost_tribe_progress = varBit("lost_tribe_quest")
    val kr_knightwaves_state = varBit("kr_knightwaves_state")

    val emote_glassbox = varBit("emote_glassbox")
    val emote_climbrope = varBit("emote_climbrope")
    val emote_lean = varBit("emote_lean")
    val emote_glasswall = varBit("emote_glasswall")
    val sos_emote_idea = varBit("sos_emote_idea")
    val sos_emote_stamp = varBit("sos_emote_stamp")
    val sos_emote_flap = varBit("sos_emote_flap")
    val sos_emote_doh = varBit("sos_emote_doh")
    val emote_zombie_walk = varBit("emote_zombie_walk")
    val emote_zombie_dance = varBit("emote_zombie_dance")
    val emote_terrified = varBit("emote_terrified")
    val emote_bunny_hop = varBit("emote_bunny_hop")
    val emote_drilldemon = varBit("emote_drilldemon")
    val emote_party = varBit("emote_party")
    val emote_zombie_hand = varBit("emote_zombie_hand")
    val emote_ash = varBit("emote_ash")
    val emote_musiccape = varBit("emote_musiccape")
    val emote_uri_transform = varBit("emote_uri_transform")
    val emote_hotline_bling = varBit("emote_hotline_bling")
    val emote_gangnam = varBit("emote_gangnam")
    val emote_premier_club_2018 = varBit("emote_premier_club_2018")
    val emote_flex = varBit("emote_flex")
    val emote_explore = varBit("emote_explore")
    val poh_leaguehall_outfitstand_relichunter_type =
        varBit("poh_leaguehall_outfitstand_relichunter_type")
    val emote_trick = varBit("emote_trick")

    val enabled_prayers = varBit("prayer_allactive")
    val quickprayer_active = varBit("quickprayer_active")

    val thick_skin = varBit("prayer_thickskin")
    val burst_of_strength = varBit("prayer_burstofstrength")
    val clarity_of_thought = varBit("prayer_clarityofthought")
    val rock_skin = varBit("prayer_rockskin")
    val superhuman_strength = varBit("prayer_superhumanstrength")
    val improved_reflexes = varBit("prayer_improvedreflexes")
    val rapid_restore = varBit("prayer_rapidrestore")
    val rapid_heal = varBit("prayer_rapidheal")
    val protect_item = varBit("prayer_protectitem")
    val steel_skin = varBit("prayer_steelskin")
    val ultimate_strength = varBit("prayer_ultimatestrength")
    val incredible_reflexes = varBit("prayer_incrediblereflexes")
    val protect_from_magic = varBit("prayer_protectfrommagic")
    val protect_from_missiles = varBit("prayer_protectfrommissiles")
    val protect_from_melee = varBit("prayer_protectfrommelee")
    val retribution = varBit("prayer_retribution")
    val redemption = varBit("prayer_redemption")
    val smite = varBit("prayer_smite")
    val preserve = varBit("prayer_preserve")
    val sharp_eye = varBit("prayer_sharpeye")
    val mystic_will = varBit("prayer_mysticwill")
    val hawk_eye = varBit("prayer_hawkeye")
    val mystic_lore = varBit("prayer_mysticlore")
    val eagle_eye = varBit("prayer_eagleeye")
    val mystic_might = varBit("prayer_mysticmight")
    val chivalry = varBit("prayer_chivalry")
    val piety = varBit("prayer_piety")
    val rigour = varBit("prayer_rigour")
    val augury = varBit("prayer_augury")
    val preserve_unlocked = varBit("prayer_preserve_unlocked")
    val rigour_unlocked = varBit("prayer_rigour_unlocked")
    val augury_unlocked = varBit("prayer_augury_unlocked")
    val prayer_deadeye_unlocked = varBit("prayer_deadeye_unlocked")
    val prayer_mystic_vigour_unlocked = varBit("prayer_mystic_vigour_unlocked")

    val toa_client_raid_level = varBit("toa_client_raid_level")

    val settings_hitsplat_threshold = varBit("settings_hitsplat_threshold")

    val date_ms_past_minute = varBit("date_milliseconds_past_minute")
    val date_secs_past_minute = varBit("date_seconds_past_minute")

    /* Server-side-only types */
    val music_last_id = varBit("music_last_id")
    val music_curr_area = varBit("music_curr_area")
    val music_curr_id = varBit("music_curr_id")
    val music_curr_clocks = varBit("music_curr_clocks")
    val music_curr_duration = varBit("music_curr_duration")
    val gameframe_toplevel = varBit("gameframe_toplevel")
    val improved_stamina_passive = varBit("improved_stamina_passive")
    val prayer_drain_counter = varBit("prayer_drain_counter")
    val prayer_drain_resistance = varBit("prayer_drain_resistance")
    val new_player_account = varBit("new_player_account")
    val saved_autocast_spell_staff = varBit("saved_autocast_spell_staff")
    val saved_defensive_casting_staff = varBit("saved_defensive_casting_staff")
    val saved_autocast_spell_bladed_staff = varBit("saved_autocast_spell_bladed_staff")
    val saved_defensive_casting_bladed_staff = varBit("saved_defensive_casting_bladed_staff")
    val accept_aid_restore = varBit("accept_aid_restore")
    val bank_capacity = varBit("bank_capacity")
    val coal_bag_storage_count = varBit("coal_bag_storage_count")
    val small_pouch_storage_type = varBit("small_pouch_storage_type")
    val small_pouch_storage_count = varBit("small_pouch_storage_count")
    val medium_pouch_storage_type = varBit("medium_pouch_storage_type")
    val medium_pouch_storage_count = varBit("medium_pouch_storage_count")
    val large_pouch_storage_type = varBit("large_pouch_storage_type")
    val large_pouch_storage_count = varBit("large_pouch_storage_count")
    val giant_pouch_storage_type = varBit("giant_pouch_storage_type")
    val giant_pouch_storage_count = varBit("giant_pouch_storage_count")
    val colossal_pouch_storage_type = varBit("colossal_pouch_storage_type")
    val colossal_pouch_storage_count = varBit("colossal_pouch_storage_count")
}
