@file:Suppress("SpellCheckingInspection", "unused")

package org.rsmod.api.config.refs

import dev.openrune.obj

typealias objs = BaseObjs

object BaseObjs {
    val template_for_cert = obj("template_for_cert")
    val template_for_transform = obj("template_for_transform")
    val template_for_placeholder = obj("template_for_placeholder")
    val null_item_placeholder = obj("blankobject")

    val coins = obj("coins")
    val platinum_tokens = obj("platinum")

    val bones = obj("bones")
    val snowball = obj("gublinch_snowball")

    val pot_empty = obj("pot_empty")
    val jug_empty = obj("jug_empty")
    val pack_jug_empty = obj("pack_jug_empty")
    val shears = obj("shears")
    val knife = obj("knife")
    val bucket_empty = obj("bucket_empty")
    val bucket_of_milk = obj("bucket_milk")
    val pack_bucket = obj("pack_bucket")
    val bowl_empty = obj("bowl_empty")
    val cake_tin = obj("cake_tin")
    val tinderbox = obj("tinderbox")
    val chisel = obj("chisel")
    val spade = obj("spade")
    val hammer = obj("hammer")
    val newcomer_map = obj("newcomer_map")
    val sos_security_book = obj("sos_security_book")
    val wool = obj("wool")

    val cabbage = obj("cabbage")
    val onion = obj("onion")
    val grain = obj("grain")
    val potato = obj("potato")
    val cabbage_seed = obj("cabbage_seed")
    val egg = obj("egg")

    val bobs_axe_flyer = obj("flier")
    val iron_battleaxe = obj("iron_battleaxe")
    val steel_battleaxe = obj("steel_battleaxe")
    val mithril_battleaxe = obj("mithril_battleaxe")
    val beer = obj("beer")
    val charcoal = obj("charcoal")

    val logs = obj("logs")
    val oak_logs = obj("oak_logs")
    val willow_logs = obj("willow_logs")
    val maple_logs = obj("maple_logs")
    val yew_logs = obj("yew_logs")
    val magic_logs = obj("magic_logs")
    val redwood_logs = obj("redwood_logs")
    val teak_logs = obj("teak_logs")
    val mahogany_logs = obj("mahogany_logs")
    val achey_tree_logs = obj("achey_tree_logs")
    val arctic_pine_logs = obj("arctic_pine_log")
    val juniper_logs = obj("juniper_logs")
    val bark = obj("hollow_bark")

    val coal_bag = obj("coal_bag")
    val coal_bag_open = obj("coal_bag_open")
    val rcu_pouch_small = obj("rcu_pouch_small")
    val rcu_pouch_medium = obj("rcu_pouch_medium")
    val rcu_pouch_medium_degrade = obj("rcu_pouch_medium_degrade")
    val rcu_pouch_large = obj("rcu_pouch_large")
    val rcu_pouch_large_degrade = obj("rcu_pouch_large_degrade")
    val rcu_pouch_giant = obj("rcu_pouch_giant")
    val rcu_pouch_giant_degrade = obj("rcu_pouch_giant_degrade")
    val rcu_pouch_colossal = obj("rcu_pouch_colossal")
    val rcu_pouch_colossal_degrade = obj("rcu_pouch_colossal_degrade")

    val cabbage_cape = obj("skillcape_cabbage")

    val music_cape = obj("music_cape_trimmed")
    val music_cape_t = obj("music_cape_trimmed")
    val music_hood = obj("music_cape_hood")

    val quest_point_cape = obj("skillcape_qp")
    val quest_point_cape_t = obj("skillcape_qp_trimmed")
    val quest_point_hood = obj("skillcape_qp_hood")

    val achievement_diary_cape = obj("skillcape_ad")
    val achievement_diary_cape_t = obj("skillcape_ad_trimmed")
    val achievement_diary_hood = obj("skillcape_ad_hood")

    val max_hood = obj("skillcape_max_hood")
    val max_cape_worn = obj("skillcape_max_worn")
    val max_cape_inv = obj("skillcape_max")

    val attack_skillcape = obj("skillcape_attack")
    val attack_skillcape_t = obj("skillcape_attack_trimmed")
    val attack_hood = obj("skillcape_attack_hood")

    val defence_skillcape = obj("skillcape_defence")
    val defence_skillcape_t = obj("skillcape_defence_trimmed")
    val defence_hood = obj("skillcape_defence_hood")

    val strength_skillcape = obj("skillcape_strength")
    val strength_skillcape_t = obj("skillcape_strength_trimmed")
    val strength_hood = obj("skillcape_strength_hood")

    val hitpoints_skillcape = obj("skillcape_hitpoints")
    val hitpoints_skillcape_t = obj("skillcape_hitpoints_trimmed")
    val hitpoints_hood = obj("skillcape_hitpoints_hood")

    val ranged_skillcape = obj("skillcape_ranging")
    val ranged_skillcape_t = obj("skillcape_ranging_trimmed")
    val ranged_hood = obj("skillcape_ranging_hood")

    val prayer_skillcape = obj("skillcape_prayer")
    val prayer_skillcape_t = obj("skillcape_prayer_trimmed")
    val prayer_hood = obj("skillcape_prayer_hood")

    val magic_skillcape = obj("skillcape_magic")
    val magic_skillcape_t = obj("skillcape_magic_trimmed")
    val magic_hood = obj("skillcape_magic_hood")

    val cooking_skillcape = obj("skillcape_cooking")
    val cooking_skillcape_t = obj("skillcape_cooking_trimmed")
    val cooking_hood = obj("skillcape_cooking_hood")

    val woodcutting_skillcape = obj("skillcape_woodcutting")
    val woodcutting_skillcape_t = obj("skillcape_woodcutting_trimmed")
    val woodcutting_hood = obj("skillcape_woodcutting_hood")

    val fletching_skillcape = obj("skillcape_fletching")
    val fletching_skillcape_t = obj("skillcape_fletching_trimmed")
    val fletching_hood = obj("skillcape_fletching_hood")

    val fishing_skillcape = obj("skillcape_fishing")
    val fishing_skillcape_t = obj("skillcape_fishing_trimmed")
    val fishing_hood = obj("skillcape_fishing_hood")

    val firemaking_skillcape = obj("skillcape_firemaking")
    val firemaking_skillcape_t = obj("skillcape_firemaking_trimmed")
    val firemaking_hood = obj("skillcape_firemaking_hood")

    val crafting_skillcape = obj("skillcape_crafting")
    val crafting_skillcape_t = obj("skillcape_crafting_trimmed")
    val crafting_hood = obj("skillcape_crafting_hood")

    val smithing_skillcape = obj("skillcape_smithing")
    val smithing_skillcape_t = obj("skillcape_smithing_trimmed")
    val smithing_hood = obj("skillcape_smithing_hood")

    val mining_skillcape = obj("skillcape_mining")
    val mining_skillcape_t = obj("skillcape_mining_trimmed")
    val mining_hood = obj("skillcape_mining_hood")

    val herblore_skillcape = obj("skillcape_herblore")
    val herblore_skillcape_t = obj("skillcape_herblore_trimmed")
    val herblore_hood = obj("skillcape_herblore_hood")

    val agility_skillcape = obj("skillcape_agility")
    val agility_skillcape_t = obj("skillcape_agility_trimmed")
    val agility_hood = obj("skillcape_agility_hood")

    val thieving_skillcape = obj("skillcape_thieving")
    val thieving_skillcape_t = obj("skillcape_thieving_trimmed")
    val thieving_hood = obj("skillcape_thieving_hood")

    val slayer_skillcape = obj("skillcape_slayer")
    val slayer_skillcape_t = obj("skillcape_slayer_trimmed")
    val slayer_hood = obj("skillcape_slayer_hood")

    val farming_skillcape = obj("skillcape_farming")
    val farming_skillcape_t = obj("skillcape_farming_trimmed")
    val farming_hood = obj("skillcape_farming_hood")

    val runecrafting_skillcape = obj("skillcape_runecrafting")
    val runecrafting_skillcape_t = obj("skillcape_runecrafting_trimmed")
    val runecrafting_hood = obj("skillcape_runecrafting_hood")

    val hunter_skillcape = obj("skillcape_hunting")
    val hunter_skillcape_t = obj("skillcape_hunting_trimmed")
    val hunter_hood = obj("skillcape_hunting_hood")

    val construction_skillcape = obj("skillcape_construction")
    val construction_skillcape_t = obj("skillcape_construction_trimmed")
    val construction_hood = obj("skillcape_construction_hood")

    val lumberjack_hat = obj("ramble_lumberjack_hat")
    val lumberjack_top = obj("ramble_lumberjack_top")
    val lumberjack_legs = obj("ramble_lumberjack_legs")
    val lumberjack_boots = obj("ramble_lumberjack_boots")

    val forestry_hat = obj("forestry_lumberjack_hat")
    val forestry_top = obj("forestry_lumberjack_top")
    val forestry_legs = obj("forestry_lumberjack_legs")
    val forestry_boots = obj("forestry_lumberjack_boots")

    val graceful_hood_inv = obj("graceful_hood")
    val graceful_cape_inv = obj("graceful_cape")
    val graceful_top_inv = obj("graceful_top")
    val graceful_legs_inv = obj("graceful_legs")
    val graceful_gloves_inv = obj("graceful_gloves")
    val graceful_boots_inv = obj("graceful_boots")

    val graceful_hood_worn = obj("graceful_hood_worn")
    val graceful_cape_worn = obj("graceful_cape_worn")
    val graceful_top_worn = obj("graceful_top_worn")
    val graceful_legs_worn = obj("graceful_legs_worn")
    val graceful_gloves_worn = obj("graceful_gloves_worn")
    val graceful_boots_worn = obj("graceful_boots_worn")

    val arceuus_graceful_hood_inv = obj("zeah_graceful_hood_arceuus")
    val arceuus_graceful_cape_inv = obj("zeah_graceful_cape_arceuus")
    val arceuus_graceful_top_inv = obj("zeah_graceful_top_arceuus")
    val arceuus_graceful_legs_inv = obj("zeah_graceful_legs_arceuus")
    val arceuus_graceful_gloves_inv = obj("zeah_graceful_gloves_arceuus")
    val arceuus_graceful_boots_inv = obj("zeah_graceful_boots_arceuus")

    val arceuus_graceful_hood_worn = obj("zeah_graceful_hood_arceuus_worn")
    val arceuus_graceful_cape_worn = obj("zeah_graceful_cape_arceuus_worn")
    val arceuus_graceful_top_worn = obj("zeah_graceful_top_arceuus_worn")
    val arceuus_graceful_legs_worn = obj("zeah_graceful_legs_arceuus_worn")
    val arceuus_graceful_gloves_worn = obj("zeah_graceful_gloves_arceuus_worn")
    val arceuus_graceful_boots_worn = obj("zeah_graceful_boots_arceuus_worn")

    val piscarilius_graceful_hood_inv = obj("zeah_graceful_hood_piscarilius")
    val piscarilius_graceful_cape_inv = obj("zeah_graceful_cape_piscarilius")
    val piscarilius_graceful_top_inv = obj("zeah_graceful_top_piscarilius")
    val piscarilius_graceful_legs_inv = obj("zeah_graceful_legs_piscarilius")
    val piscarilius_graceful_gloves_inv = obj("zeah_graceful_gloves_piscarilius")
    val piscarilius_graceful_boots_inv = obj("zeah_graceful_boots_piscarilius")

    val piscarilius_graceful_hood_worn = obj("zeah_graceful_hood_piscarilius_worn")
    val piscarilius_graceful_cape_worn = obj("zeah_graceful_cape_piscarilius_worn")
    val piscarilius_graceful_top_worn = obj("zeah_graceful_top_piscarilius_worn")
    val piscarilius_graceful_legs_worn = obj("zeah_graceful_legs_piscarilius_worn")
    val piscarilius_graceful_gloves_worn = obj("zeah_graceful_gloves_piscarilius_worn")
    val piscarilius_graceful_boots_worn = obj("zeah_graceful_boots_piscarilius_worn")

    val lovakengj_graceful_hood_inv = obj("zeah_graceful_hood_lovakengj")
    val lovakengj_graceful_cape_inv = obj("zeah_graceful_cape_lovakengj")
    val lovakengj_graceful_top_inv = obj("zeah_graceful_top_lovakengj")
    val lovakengj_graceful_legs_inv = obj("zeah_graceful_legs_lovakengj")
    val lovakengj_graceful_gloves_inv = obj("zeah_graceful_gloves_lovakengj")
    val lovakengj_graceful_boots_inv = obj("zeah_graceful_boots_lovakengj")

    val lovakengj_graceful_hood_worn = obj("zeah_graceful_hood_lovakengj_worn")
    val lovakengj_graceful_cape_worn = obj("zeah_graceful_cape_lovakengj_worn")
    val lovakengj_graceful_top_worn = obj("zeah_graceful_top_lovakengj_worn")
    val lovakengj_graceful_legs_worn = obj("zeah_graceful_legs_lovakengj_worn")
    val lovakengj_graceful_gloves_worn = obj("zeah_graceful_gloves_lovakengj_worn")
    val lovakengj_graceful_boots_worn = obj("zeah_graceful_boots_lovakengj_worn")

    val shayzien_graceful_hood_inv = obj("zeah_graceful_hood_shayzien")
    val shayzien_graceful_cape_inv = obj("zeah_graceful_cape_shayzien")
    val shayzien_graceful_top_inv = obj("zeah_graceful_top_shayzien")
    val shayzien_graceful_legs_inv = obj("zeah_graceful_legs_shayzien")
    val shayzien_graceful_gloves_inv = obj("zeah_graceful_gloves_shayzien")
    val shayzien_graceful_boots_inv = obj("zeah_graceful_boots_shayzien")

    val shayzien_graceful_hood_worn = obj("zeah_graceful_hood_shayzien_worn")
    val shayzien_graceful_cape_worn = obj("zeah_graceful_cape_shayzien_worn")
    val shayzien_graceful_top_worn = obj("zeah_graceful_top_shayzien_worn")
    val shayzien_graceful_legs_worn = obj("zeah_graceful_legs_shayzien_worn")
    val shayzien_graceful_gloves_worn = obj("zeah_graceful_gloves_shayzien_worn")
    val shayzien_graceful_boots_worn = obj("zeah_graceful_boots_shayzien_worn")

    val hosidius_graceful_hood_inv = obj("zeah_graceful_hood_hosidius")
    val hosidius_graceful_cape_inv = obj("zeah_graceful_cape_hosidius")
    val hosidius_graceful_top_inv = obj("zeah_graceful_top_hosidius")
    val hosidius_graceful_legs_inv = obj("zeah_graceful_legs_hosidius")
    val hosidius_graceful_gloves_inv = obj("zeah_graceful_gloves_hosidius")
    val hosidius_graceful_boots_inv = obj("zeah_graceful_boots_hosidius")

    val hosidius_graceful_hood_worn = obj("zeah_graceful_hood_hosidius_worn")
    val hosidius_graceful_cape_worn = obj("zeah_graceful_cape_hosidius_worn")
    val hosidius_graceful_top_worn = obj("zeah_graceful_top_hosidius_worn")
    val hosidius_graceful_legs_worn = obj("zeah_graceful_legs_hosidius_worn")
    val hosidius_graceful_gloves_worn = obj("zeah_graceful_gloves_hosidius_worn")
    val hosidius_graceful_boots_worn = obj("zeah_graceful_boots_hosidius_worn")

    val kourend_graceful_hood_inv = obj("zeah_graceful_hood_kourend")
    val kourend_graceful_cape_inv = obj("zeah_graceful_cape_kourend")
    val kourend_graceful_top_inv = obj("zeah_graceful_top_kourend")
    val kourend_graceful_legs_inv = obj("zeah_graceful_legs_kourend")
    val kourend_graceful_gloves_inv = obj("zeah_graceful_gloves_kourend")
    val kourend_graceful_boots_inv = obj("zeah_graceful_boots_kourend")

    val kourend_graceful_hood_worn = obj("zeah_graceful_hood_kourend_worn")
    val kourend_graceful_cape_worn = obj("zeah_graceful_cape_kourend_worn")
    val kourend_graceful_top_worn = obj("zeah_graceful_top_kourend_worn")
    val kourend_graceful_legs_worn = obj("zeah_graceful_legs_kourend_worn")
    val kourend_graceful_gloves_worn = obj("zeah_graceful_gloves_kourend_worn")
    val kourend_graceful_boots_worn = obj("zeah_graceful_boots_kourend_worn")

    val skillcape_graceful_hood_inv = obj("graceful_hood_skillcapecolour")
    val skillcape_graceful_cape_inv = obj("graceful_cape_skillcapecolour")
    val skillcape_graceful_top_inv = obj("graceful_top_skillcapecolour")
    val skillcape_graceful_legs_inv = obj("graceful_legs_skillcapecolour")
    val skillcape_graceful_gloves_inv = obj("graceful_gloves_skillcapecolour")
    val skillcape_graceful_boots_inv = obj("graceful_boots_skillcapecolour")

    val skillcape_graceful_hood_worn = obj("graceful_hood_skillcapecolour_worn")
    val skillcape_graceful_cape_worn = obj("graceful_cape_skillcapecolour_worn")
    val skillcape_graceful_top_worn = obj("graceful_top_skillcapecolour_worn")
    val skillcape_graceful_legs_worn = obj("graceful_legs_skillcapecolour_worn")
    val skillcape_graceful_gloves_worn = obj("graceful_gloves_skillcapecolour_worn")
    val skillcape_graceful_boots_worn = obj("graceful_boots_skillcapecolour_worn")

    val hallowed_graceful_hood_inv = obj("graceful_hood_hallowed")
    val hallowed_graceful_cape_inv = obj("graceful_cape_hallowed")
    val hallowed_graceful_top_inv = obj("graceful_top_hallowed")
    val hallowed_graceful_legs_inv = obj("graceful_legs_hallowed")
    val hallowed_graceful_gloves_inv = obj("graceful_gloves_hallowed")
    val hallowed_graceful_boots_inv = obj("graceful_boots_hallowed")

    val hallowed_graceful_hood_worn = obj("graceful_hood_hallowed_worn")
    val hallowed_graceful_cape_worn = obj("graceful_cape_hallowed_worn")
    val hallowed_graceful_top_worn = obj("graceful_top_hallowed_worn")
    val hallowed_graceful_legs_worn = obj("graceful_legs_hallowed_worn")
    val hallowed_graceful_gloves_worn = obj("graceful_gloves_hallowed_worn")
    val hallowed_graceful_boots_worn = obj("graceful_boots_hallowed_worn")

    val trailblazer_graceful_hood_inv = obj("graceful_hood_trailblazer")
    val trailblazer_graceful_cape_inv = obj("graceful_cape_trailblazer")
    val trailblazer_graceful_top_inv = obj("graceful_top_trailblazer")
    val trailblazer_graceful_legs_inv = obj("graceful_legs_trailblazer")
    val trailblazer_graceful_gloves_inv = obj("graceful_gloves_trailblazer")
    val trailblazer_graceful_boots_inv = obj("graceful_boots_trailblazer")

    val trailblazer_graceful_hood_worn = obj("graceful_hood_trailblazer_worn")
    val trailblazer_graceful_cape_worn = obj("graceful_cape_trailblazer_worn")
    val trailblazer_graceful_top_worn = obj("graceful_top_trailblazer_worn")
    val trailblazer_graceful_legs_worn = obj("graceful_legs_trailblazer_worn")
    val trailblazer_graceful_gloves_worn = obj("graceful_gloves_trailblazer_worn")
    val trailblazer_graceful_boots_worn = obj("graceful_boots_trailblazer_worn")

    val adventurer_graceful_hood_inv = obj("graceful_hood_adventurer")
    val adventurer_graceful_cape_inv = obj("graceful_cape_adventurer")
    val adventurer_graceful_top_inv = obj("graceful_top_adventurer")
    val adventurer_graceful_legs_inv = obj("graceful_legs_adventurer")
    val adventurer_graceful_gloves_inv = obj("graceful_gloves_adventurer")
    val adventurer_graceful_boots_inv = obj("graceful_boots_adventurer")

    val adventurer_graceful_hood_worn = obj("graceful_hood_adventurer_worn")
    val adventurer_graceful_cape_worn = obj("graceful_cape_adventurer_worn")
    val adventurer_graceful_top_worn = obj("graceful_top_adventurer_worn")
    val adventurer_graceful_legs_worn = obj("graceful_legs_adventurer_worn")
    val adventurer_graceful_gloves_worn = obj("graceful_gloves_adventurer_worn")
    val adventurer_graceful_boots_worn = obj("graceful_boots_adventurer_worn")

    val wyrm_graceful_hood_inv = obj("graceful_hood_wyrm")
    val wyrm_graceful_cape_inv = obj("graceful_cape_wyrm")
    val wyrm_graceful_top_inv = obj("graceful_top_wyrm")
    val wyrm_graceful_legs_inv = obj("graceful_legs_wyrm")
    val wyrm_graceful_gloves_inv = obj("graceful_gloves_wyrm")
    val wyrm_graceful_boots_inv = obj("graceful_boots_wyrm")

    val wyrm_graceful_hood_worn = obj("graceful_hood_wyrm_worn")
    val wyrm_graceful_cape_worn = obj("graceful_cape_wyrm_worn")
    val wyrm_graceful_top_worn = obj("graceful_top_wyrm_worn")
    val wyrm_graceful_legs_worn = obj("graceful_legs_wyrm_worn")
    val wyrm_graceful_gloves_worn = obj("graceful_gloves_wyrm_worn")
    val wyrm_graceful_boots_worn = obj("graceful_boots_wyrm_worn")

    val bronze_axe = obj("bronze_axe")
    val iron_axe = obj("iron_axe")
    val steel_axe = obj("steel_axe")
    val black_axe = obj("black_axe")
    val mithril_axe = obj("mithril_axe")
    val adamant_axe = obj("adamant_axe")
    val blessed_axe = obj("anma_axe")
    val rune_axe = obj("rune_axe")
    val gilded_axe = obj("trail_gilded_axe")
    val dragon_axe = obj("dragon_axe")
    val dragon_axe_or = obj("trailblazer_axe_no_infernal")
    val third_age_axe = obj("3a_axe")
    val infernal_axe = obj("infernal_axe")
    val infernal_axe_or = obj("trailblazer_axe")
    val crystal_axe = obj("crystal_axe")

    val bronze_pickaxe = obj("bronze_pickaxe")
    val dragon_pickaxe = obj("dragon_pickaxe")
    val dragon_pickaxe_upgraded = obj("dragon_pickaxe_pretty")
    val dragon_pickaxe_or_trailblazer = obj("trailblazer_pickaxe_no_infernal")
    val dragon_pickaxe_or_zalcano = obj("zalcano_pickaxe")
    val infernal_pickaxe = obj("infernal_pickaxe")
    val infernal_pickaxe_uncharged = obj("infernal_pickaxe_empty")
    val infernal_pickaxe_or = obj("trailblazer_pickaxe")
    val infernal_pickaxe_or_uncharged = obj("trailblazer_pickaxe_empty")
    val third_age_pickaxe = obj("3a_pickaxe")
    val crystal_pickaxe = obj("crystal_pickaxe")

    val dragon_harpoon = obj("dragon_harpoon")
    val dragon_harpoon_or = obj("trailblazer_harpoon_no_infernal")
    val infernal_harpoon = obj("infernal_harpoon")
    val infernal_harpoon_or = obj("trailblazer_harpoon")
    val infernal_harpoon_or_uncharged = obj("trailblazer_harpoon_empty")
    val crystal_harpoon = obj("crystal_harpoon")

    val shrimps = obj("shrimp")
    val raw_herring = obj("raw_herring")
    val herring = obj("herring")

    val nose_peg = obj("slayer_nosepeg")
    val facemask = obj("slayer_facemask")
    val earmuffs = obj("slayer_earmuffs")
    val spiny_helmet = obj("wallbeast_spike_helmet")
    val reinforced_goggles = obj("slayer_reinforced_goggles")
    val neitiznot_shield = obj("fremmenik_round_shield")

    val rune_pouch = obj("bh_rune_pouch")
    val rune_pouch_l = obj("bh_rune_pouch_trouver")
    val divine_rune_pouch = obj("divine_rune_pouch")
    val divine_rune_pouch_l = obj("divine_rune_pouch_trouver")

    val lms_rune_pouch = obj("br_rune_replacement")

    val air_rune = obj("airrune")
    val water_rune = obj("waterrune")
    val earth_rune = obj("earthrune")
    val fire_rune = obj("firerune")
    val mind_rune = obj("mindrune")
    val chaos_rune = obj("chaosrune")
    val death_rune = obj("chaosrune")
    val blood_rune = obj("bloodrune")
    val nature_rune = obj("naturerune")
    val law_rune = obj("lawrune")
    val smoke_rune = obj("smokerune")
    val mist_rune = obj("mistrune")
    val dust_rune = obj("dustrune")
    val steam_rune = obj("steamrune")
    val lava_rune = obj("lavarune")
    val mud_rune = obj("mudrune")
    val soul_rune = obj("soulrune")
    val sunfire_rune = obj("sunfirerune")

    val air_rune_nz = obj("nzone_airrune")
    val water_rune_nz = obj("nzone_waterrune")
    val earth_rune_nz = obj("nzone_earthrune")
    val fire_rune_nz = obj("nzone_firerune")
    val chaos_rune_nz = obj("nzone_chaosrune")
    val death_rune_nz = obj("nzone_deathrune")
    val blood_rune_nz = obj("nzone_bloodrune")

    val fake_air_rune = obj("fake_airrune")
    val fake_water_rune = obj("fake_waterrune")
    val fake_earth_rune = obj("fake_earthrune")
    val fake_fire_rune = obj("fake_firerune")
    val fake_nature_rune = obj("fake_naturerune")

    val chaos_gauntlets = obj("gauntlets_of_chaos")
    val tome_of_water = obj("tome_of_water")
    val tome_of_earth = obj("tome_of_earth")
    val tome_of_fire = obj("tome_of_fire")
    val devils_element = obj("devils_element")

    val air_staff = obj("staff_of_air")
    val air_battlestaff = obj("air_battlestaff")
    val mystic_air_staff = obj("mystic_air_staff")

    val smoke_battlestaff = obj("smoke_battlestaff")
    val mystic_smoke_staff = obj("mystic_smoke_battlestaff")
    val mist_battlestaff = obj("mist_battlestaff")
    val mystic_mist_staff = obj("mystic_mist_battlestaff")
    val dust_battlestaff = obj("dust_battlestaff")
    val mystic_dust_staff = obj("mystic_dust_battlestaff")
    val twinflame_staff = obj("twinflame_staff")

    val ancient_staff = obj("staff_of_zaros")
    val skull_sceptre_i = obj("sos_skull_sceptre_imbued")
    val ibans_staff = obj("ibanstaff")
    val ibans_staff_u = obj("ibanstaff_upgraded")
    val slayers_staff = obj("slayer_staff")
    val slayers_staff_e = obj("slayer_staff_enchanted")
    val thammarons_sceptre = obj("wild_cave_sceptre_charged")
    val thammarons_sceptre_a = obj("wild_cave_sceptre_charged_recol")
    val thammarons_sceptre_au = obj("wild_cave_sceptre_uncharged_recol")
    val accursed_sceptre = obj("wild_cave_accursed_charged")
    val accursed_sceptre_a = obj("wild_cave_accursed_charged_recol")
    val accursed_sceptre_au = obj("wild_cave_accursed_uncharged_recol")
    val staff_of_the_dead = obj("sotd")
    val toxic_staff_of_the_dead = obj("toxic_sotd_charged")
    val toxic_staff_uncharged = obj("toxic_sotd")
    val staff_of_light = obj("staff_of_light")
    val staff_of_balance = obj("staff_of_balance")
    val void_knight_mace = obj("pest_void_knight_mace")
    val void_knight_mace_l = obj("pest_void_knight_mace_trouver")
    val bryophytas_staff = obj("nature_staff_charged")
    val purging_staff = obj("purging_staff")

    val saradomin_staff = obj("saradomin_staff")
    val zamorak_staff = obj("zamorak_staff")
    val guthix_staff = obj("guthix_staff")
    val guthix_staff_rune = obj("pest_interface_staffs")

    val view_jewellery_enchantment_spells = obj("placeholder_blighted_sack_wave")
    val view_bolt_enchantment_spells = obj("50_slayer_dart")

    val spell_enchant_lvl_1 = obj("07_enchant_amulet_lvl1")
    val spell_enchant_lvl_2 = obj("27_enchant_amulet_lvl2")
    val spell_enchant_lvl_3 = obj("49_enchant_amulet_lvl3")
    val spell_enchant_lvl_4 = obj("57_enchant_amulet_lvl4")
    val spell_enchant_lvl_5 = obj("68_enchant_amulet_lvl5")
    val spell_enchant_lvl_6 = obj("87_enchant_amulet_lvl6")
    val spell_enchant_lvl_7 = obj("93_enchant_amulet_lvl7")
    val spell_bones_to_bananas = obj("15_bones_bananas")
    val spell_bones_to_peaches = obj("60_bones_peaches")
    val spell_low_alchemy = obj("21_low_alchemy")
    val spell_high_alchemy = obj("55_high_alchemy")
    val spell_superheat = obj("43_superheat_item")
    val spell_tele_grab = obj("33_tele_grab")
    val spell_monster_inspect = obj("placeholder_gathering_event_leprechaun_charm")
    val spell_chargeorb_water = obj("56_charge_water_orb")
    val spell_chargeorb_earth = obj("60_charge_earth_orb")
    val spell_chargeorb_fire = obj("63_charge_fire_orb")
    val spell_chargeorb_air = obj("66_charge_air_orb")
    val spell_charge = obj("80_charge")

    val spell_hometeleport_lumbridge = obj("48_home_teleport")
    val spell_lumbridge_teleport = obj("31_lumbridge_teleport")
    val spell_varrock_teleport = obj("25_varrock_teleport")
    val spell_falador_teleport = obj("37_falador_teleport")
    val spell_poh_teleport = obj("67_house_teleport")
    val spell_camelot_teleport = obj("45_camelot_teleport")
    val spell_kourendcastle_teleport = obj("cert_deadman_level99_lamp")
    val spell_ardougne_teleport = obj("51_ardougne_teleport")
    val spell_civitas_fortis_teleport = obj("placeholder_blighted_sack_snare")
    val spell_watchtower_teleport = obj("58_watchtower_teleport")
    val spell_trollheim_teleport = obj("61_trollheim_teleport")
    val spell_apeatoll_teleport = obj("64_ape_atoll_teleport")
    val spell_teleother_lumbridge = obj("74_teleother_lumbridge")
    val spell_teleother_falador = obj("82_teleother_falador")
    val spell_teleother_camelot = obj("90_teleother_camelot")

    val spell_tele_block = obj("85_teleport_block")
    val spell_teleport_to_target = obj("placeholder_caveorb4dot")

    val spell_crumble_undead = obj("39_crumble_undead")
    val spell_iban_blast = obj("50_iban_blast")
    val spell_magic_dart = obj("50_magic_dart")
    val spell_flames_of_zamorak = obj("60_flames_of_zamorak")
    val spell_saradomin_strike = obj("60_saradomin_strike")
    val spell_claws_of_guthix = obj("60_claws_of_guthix")

    val spell_confuse = obj("03_confuse")
    val spell_weaken = obj("11_weaken")
    val spell_curse = obj("19_curse")

    val spell_bind = obj("20_bind")
    val spell_snare = obj("50_snare")
    val spell_entangle = obj("79_entangle")

    val spell_vulnerability = obj("66_vulnerability")
    val spell_enfeeble = obj("73_enfeeble")
    val spell_stun = obj("80_stun")

    val spell_wind_strike = obj("01_wind_strike")
    val spell_water_strike = obj("05_water_strike")
    val spell_earth_strike = obj("09_earth_strike")
    val spell_fire_strike = obj("13_fire_strike")

    val spell_wind_bolt = obj("17_wind_bolt")
    val spell_water_bolt = obj("23_water_bolt")
    val spell_earth_bolt = obj("29_earth_bolt")
    val spell_fire_bolt = obj("35_fire_bolt")

    val spell_wind_blast = obj("41_wind_blast")
    val spell_water_blast = obj("47_water_blast")
    val spell_earth_blast = obj("53_earth_blast")
    val spell_fire_blast = obj("59_fire_blast")

    val spell_wind_wave = obj("62_wind_wave")
    val spell_water_wave = obj("65_water_wave")
    val spell_earth_wave = obj("70_earth_wave")
    val spell_fire_wave = obj("75_fire_wave")

    val spell_wind_surge = obj("81_wind_surge")
    val spell_water_surge = obj("85_water_surge")
    val spell_earth_surge = obj("90_earth_surge")
    val spell_fire_surge = obj("95_fire_surge")

    val spell_hometeleport_edgeville = obj("01_zaros_home_tele")
    val spell_paddewwa_teleport = obj("54_paddewwa_teleport")
    val spell_senntisten_teleport = obj("60_senntisten_teleport")
    val spell_kharyllyl_teleport = obj("66_kharyllyl_teleport")
    val spell_lassar_teleport = obj("72_lassar_teleport")
    val spell_dareeyak_teleport = obj("78_dareeyak_teleport")
    val spell_carrallagar_teleport = obj("84_carrallagar_teleport")
    val spell_annakarl_teleport = obj("90_annakarl_teleport")
    val spell_ghorrock_teleport = obj("96_ghorrock_teleport")

    val spell_smoke_rush = obj("50_smoke_rush")
    val spell_smoke_burst = obj("62_smoke_burst")
    val spell_smoke_blitz = obj("74_smoke_blitz")
    val spell_smoke_barrage = obj("86_smoke_barrage")

    val spell_shadow_rush = obj("52_shadow_rush")
    val spell_shadow_burst = obj("64_shadow_burst")
    val spell_shadow_blitz = obj("76_shadow_blitz")
    val spell_shadow_barrage = obj("88_shadow_barrage")

    val spell_blood_rush = obj("56_blood_rush")
    val spell_blood_burst = obj("68_blood_burst")
    val spell_blood_blitz = obj("80_blood_blitz")
    val spell_blood_barrage = obj("92_blood_barrage")

    val spell_ice_rush = obj("58_ice_rush")
    val spell_ice_burst = obj("70_ice_burst")
    val spell_ice_blitz = obj("82_ice_blitz")
    val spell_ice_barrage = obj("94_ice_barrage")

    val spell_hometeleport_lunar = obj("01_lunar_home_tele")
    val spell_moonclan_teleport = obj("69_tele_moonclan")
    val spell_moonclan_telegroup = obj("70_tele_moonclan_group")
    val spell_zmi_teleport = obj("71_tele_zmialtar")
    val spell_waterbirth_teleport = obj("72_tele_waterbirth")
    val spell_waterbirth_telegroup = obj("73_tele_waterbirth_group")
    val spell_barboutpost_teleport = obj("75_tele_barb_outpost")
    val spell_barboutpost_telegroup = obj("76_tele_barb_outpost_group")
    val spell_portkhazard_teleport = obj("78_tele_port_khazard")
    val spell_portkhazard_telegroup = obj("79_tele_port_khazard_group")
    val spell_fishguild_teleport = obj("85_tele_fish_guild")
    val spell_fishguard_telegroup = obj("86_tele_fish_guild_group")
    val spell_catherby_teleport = obj("87_tele_catherby")
    val spell_catherby_telegroup = obj("88_tele_catherby_group")
    val spell_lunarghorrock_teleport = obj("89_tele_ghorrock")
    val spell_lunarghorrock_telegroup = obj("90_tele_ghorrock_group")

    val spell_bake_pie = obj("65_bake_pie")
    val spell_geomancy = obj("watering_can_dummy")
    val spell_cure_plant = obj("66_cure_plant")
    val spell_monster_examine = obj("66_monster_examine")
    val spell_npc_contact = obj("67_npc_contact")
    val spell_cure_other = obj("68_cure_other")
    val spell_humidify = obj("68_humidify")
    val spell_cure_me = obj("71_cure_me")
    val spell_hunter_kit = obj("71_hunter_kit")
    val spell_cure_group = obj("74_cure_group")
    val spell_stat_spy = obj("75_stat_spy")
    val spell_spin_flax = obj("76_spin_flax")
    val spell_superglass = obj("77_superglass")
    val spell_tan_leather = obj("leather")
    val spell_dream = obj("79_dream")
    val spell_string_jewelry = obj("80_string_jewelry")
    val spell_res_pot_share = obj("81_res_pot_share")
    val spell_magic_imbue = obj("82_magic_imbue")
    val spell_treat_soil = obj("83_treat_soil")
    val spell_statboost_pot_share = obj("84_statboost_pot_share")
    val spell_plank_make = obj("86_plank_make")
    val spell_recharge_dragonstone = obj("caveorb4dot")
    val spell_energy_transfer = obj("91_energy_transfer")
    val spell_heal_other = obj("92_heal_other")
    val spell_vengeance_other = obj("93_vengeance_other")
    val spell_vengeance = obj("94_vengeance")
    val spell_heal_group = obj("95_heal_group")
    val spell_spellbook_swap = obj("96_spellbook_swap")

    val spell_hometeleport_arceuus = obj("deadman_level99_lamp")
    val spell_arceuuslibrary_teleport = obj("br_mithril_platebody")
    val spell_draynormanor_teleport = obj("br_mithril_platelegs")
    val spell_battlefront_teleport = obj("23_teleport_battlefront")
    val spell_mindaltar_teleport = obj("br_greendhide_body")
    val spell_respawn_teleport = obj("poh_guide_guildtrophy")
    val spell_salvegrave_teleport = obj("br_greendhide_chaps")
    val spell_fenkenstrainscastle_teleport = obj("br_moonclan_body")
    val spell_westardougne_teleport = obj("br_moonclan_legs")
    val spell_harmonyisland_teleport = obj("br_xeric_body")
    val spell_cemetery_teleport = obj("br_xeric_legs")
    val spell_barrows_teleport = obj("br_air_staff")
    val spell_arceuusapeatoll_teleport = obj("br_dragon_helm")

    val spell_degrime = obj("placeholder_skillpethunter_black")
    val spell_resurrect_crops = obj("br_swordfish")

    val spell_basic_reanimation = obj("easter_helper")
    val spell_adept_reanimation = obj("cert_chompy_bird_obj")
    val spell_expert_reanimation = obj("evil_bob_amulet_of_manspeak")
    val spell_master_reanimation = obj("magictraining_guardianstatue")

    val spell_ghostly_grasp = obj("dmm_ref_hat")
    val spell_skeletal_grasp = obj("dmm_ref_torso")
    val spell_undead_grasp = obj("dmm_ref_legs")

    val spell_shadow_veil = obj("placeholder_skillpethunter_grey")
    val spell_dark_lure = obj("placeholder_snakepet_orange")
    val spell_vile_vigour = obj("placeholder_snakepet_blue")

    val spell_lesser_corruption = obj("zanarischoir_dummy")
    val spell_greater_corruption = obj("skillcape_ardy_hood_firecape")

    val spell_mark_of_darkness = obj("br_bass")
    val spell_ward_of_arceuus = obj("placeholder_skillcape_ardy_hood_firecape")
    val spell_death_charge = obj("placeholder_vetion_pet2")

    val spell_demonic_offering = obj("placeholder_skillpethunter_gold")
    val spell_sinister_offering = obj("poh_temp_limestonebrick")

    val spell_inferior_demonbane = obj("br_mithril_scimitar")
    val spell_superior_demonbane = obj("br_willow_bow")
    val spell_dark_demonbane = obj("br_adamant_scimitar")

    val spell_resurrect_lesser_ghost = obj("osb8_monkey_cow")
    val spell_resurrect_lesser_skeleton = obj("osb8_monkey_bob")
    val spell_resurrect_lesser_zombie = obj("osb8_monkey_donie")

    val spell_resurrect_superior_ghost = obj("osb8_bamboo")
    val spell_resurrect_superior_skeleton = obj("osb8_monkey_unicorn")
    val spell_resurrect_superior_zombie = obj("osb8_monkey_sheep")

    val spell_resurrect_greater_ghost = obj("osb8_monkey_trap")
    val spell_resurrect_greater_skeleton = obj("osb8_monkey_aereck")
    val spell_resurrect_greater_zombie = obj("osb8_unicorn_horn")

    val blighted_ancient_ice_sack = obj("blighted_sack_icebarrage")
    val blighted_entangle_sack = obj("blighted_sack_entangle")
    val blighted_teleport_spell_sack = obj("blighted_sack_teleblock")
    val blighted_vengeance_sack = obj("blighted_sack_vengeance")
    val blighted_surge_sack = obj("blighted_sack_surge")

    val chinchoma = obj("chinchompa_captured")
    val red_chinchoma = obj("chinchompa_big_captured")
    val black_chinchompa = obj("chinchompa_black")

    val bronze_arrow = obj("bronze_arrow")
    val adamant_arrow = obj("adamant_arrow")
    val rune_arrow = obj("rune_arrow")
    val dragon_arrow = obj("dragon_arrow")

    val runite_bolts = obj("xbows_crossbow_bolts_runite")

    val avas_accumulator = obj("anma_50_reward")
    val avas_assembler = obj("avas_assembler")

    val shortbow = obj("shortbow")
    val magic_shortbow = obj("magic_shortbow")

    val dark_bow = obj("darkbow")
    val dark_bow_green = obj("darkbow_green")
    val dark_bow_blue = obj("darkbow_blue")
    val dark_bow_yellow = obj("darkbow_yellow")
    val dark_bow_white = obj("darkbow_white")
    val dark_bow_bh = obj("bh_darkbow_imbue")

    val armadyl_helmet = obj("armadyl_helmet")
    val armadyl_chestplate = obj("armadyl_chestplate")
    val armadyl_chainskirt = obj("armadyl_skirt")

    val bandos_chestplate = obj("bandos_chestplate")
    val bandos_tassets = obj("bandos_skirt")

    val pegasian_boots = obj("pegasian_boots")
    val primordial_boots = obj("primordial_boots")
    val eternal_boots = obj("eternal_boots")

    val berserker_ring = obj("berzerker_ring")
    val archers_ring_i = obj("nzone_ranger_ring")
    val seers_ring_i = obj("nzone_seer_ring")
    val brimstone_ring = obj("brimstone_ring")
    val ring_of_endurance = obj("ring_of_endurance")

    val ultor_ring = obj("ultor_ring")
    val venator_ring = obj("venator_ring")
    val magus_ring = obj("magus_ring")

    val amulet_of_fury = obj("enchanted_onyx_amulet")
    val necklace_of_anguish = obj("zenyte_necklace_enchanted")
    val occult_necklace = obj("occult_necklace")
    val amulet_of_glory_4 = obj("amulet_of_glory_4")
    val tormented_bracelet = obj("zenyte_bracelet_enchanted")
    val regen_bracelet = obj("jewl_bracelet_regen")
    val lightbearer = obj("lightbearer")

    val imbued_saradomin_cape = obj("ma2_saradomin_cape")
    val infinity_boots = obj("magictraining_infinityboots")

    val black_dhide_body = obj("black_dragonhide_body")
    val black_dhide_chaps = obj("black_dragonhide_chaps")
    val snakeskin_boots = obj("snakeskin_boots")
    val rune_platebody = obj("rune_platebody")
    val rune_platelegs = obj("rune_platelegs")
    val armadyl_godsword = obj("ags")
    val dragonfire_ward = obj("dragonfire_ward")
    val helm_of_neitiznot = obj("fris_kingly_helm")
    val fire_cape = obj("tzhaar_cape_fire")
    val infernal_cape = obj("infernal_cape")
    val abyssal_whip = obj("abyssal_whip")
    val fighter_torso = obj("barbassault_penance_fighter_torso")
    val dragon_defender = obj("dragon_parryingdagger")
    val barrows_gloves = obj("hundred_gauntlets_level_10")
    val dragon_boots = obj("dragon_boots")
    val rune_kiteshield = obj("rune_kiteshield")
    val dragon_claws = obj("dragon_claws")
    val dragon_longsword = obj("dragon_longsword")
    val saradomin_blessed_sword = obj("blessed_saradomin_sword")
    val crystal_shield = obj("crystal_shield")

    val crystal_bow = obj("crystal_bow")
    val bow_of_faerdhinen = obj("bow_of_faerdhinen")
    val bow_of_faerdhinen_c_hefin = obj("bow_of_faerdhinen_infinite")
    val bow_of_faerdhinen_c_ithell = obj("bow_of_faerdhinen_infinite_ithell")
    val bow_of_faerdhinen_c_iorwerth = obj("bow_of_faerdhinen_infinite_iorwerth")
    val bow_of_faerdhinen_c_trahaearn = obj("bow_of_faerdhinen_infinite_trahaearn")
    val bow_of_faerdhinen_c_cadarn = obj("bow_of_faerdhinen_infinite_cadarn")
    val bow_of_faerdhinen_c_crwys = obj("bow_of_faerdhinen_infinite_crwys")
    val bow_of_faerdhinen_c_meilyr = obj("bow_of_faerdhinen_infinite_meilyr")
    val bow_of_faerdhinen_c_amlodd = obj("bow_of_faerdhinen_infinite_amlodd")

    val crystal_helm_hefin = obj("crystal_helmet_hefin")
    val crystal_helm_ithell = obj("crystal_helmet_ithell")
    val crystal_helm_iorwerth = obj("crystal_helmet_iorwerth")
    val crystal_helm_trahaearn = obj("crystal_helmet_trahaearn")
    val crystal_helm_cadarn = obj("crystal_helmet_cadarn")
    val crystal_helm_crwys = obj("crystal_helmet_crwys")
    val crystal_helm_meilyr = obj("crystal_helmet")
    val crystal_helm_amlodd = obj("crystal_helmet_amlodd")

    val crystal_body_hefin = obj("crystal_chestplate_hefin")
    val crystal_body_ithell = obj("crystal_chestplate_ithell")
    val crystal_body_iorwerth = obj("crystal_chestplate_iorwerth")
    val crystal_body_trahaearn = obj("crystal_chestplate_trahaearn")
    val crystal_body_cadarn = obj("crystal_chestplate_cadarn")
    val crystal_body_crwys = obj("crystal_chestplate_crwys")
    val crystal_body_meilyr = obj("crystal_chestplate")
    val crystal_body_amlodd = obj("crystal_chestplate_amlodd")

    val crystal_legs_hefin = obj("crystal_platelegs_hefin")
    val crystal_legs_ithell = obj("crystal_platelegs_ithell")
    val crystal_legs_iorwerth = obj("crystal_platelegs_iorwerth")
    val crystal_legs_trahaearn = obj("crystal_platelegs_trahaearn")
    val crystal_legs_cadarn = obj("crystal_platelegs_cadarn")
    val crystal_legs_crwys = obj("crystal_platelegs_crwys")
    val crystal_legs_meilyr = obj("crystal_platelegs")
    val crystal_legs_amlodd = obj("crystal_platelegs_amlodd")

    val soulreaper_axe = obj("soulreaper")
    val amulet_of_avarice = obj("wild_cave_amulet")
    val salve_amulet = obj("crystalshard_necklace")
    val salve_amulet_i = obj("nzone_salve_amulet")
    val salve_amulet_e = obj("lotr_crystalshard_necklace_upgrade")
    val salve_amulet_ei = obj("nzone_salve_amulet_e")
    val berserker_necklace = obj("jewl_beserker_necklace")
    val berserker_necklace_or = obj("jewl_beserker_necklace_ornament")

    val bone_dagger = obj("dttd_bone_dagger")
    val bone_dagger_poison = obj("dttd_bone_dagger_p")
    val bone_dagger_poison_plus = obj("dttd_bone_dagger_p+")
    val bone_dagger_poison_plus_plus = obj("dttd_bone_dagger_p++")
    val bone_spear = obj("cave_goblin_bone_spear")
    val bone_club = obj("cave_goblin_bone_club")
    val bone_crossbow = obj("dttd_bone_crossbow")
    val bone_bolts = obj("dttd_bone_crossbow_bolt")

    val arclight = obj("arclight")
    val silverlight = obj("agrith_silverlight_dyed")
    val burning_claws = obj("bone_claws")
    val obsidian_helmet = obj("obsidian_helmet")
    val obsidian_platebody = obj("obsidian_platebody")
    val obsidian_platelegs = obj("obsidian_platelegs")
    val toktz_xil_ek = obj("tzhaar_knife")
    val toktz_xil_ak = obj("tzhaar_splitsword")
    val tzhaar_ket_em = obj("tzhaar_mace")
    val tzhaar_ket_om = obj("tzhaar_maul")
    val tzhaar_ket_om_t = obj("tzhaar_maul_t")
    val dragon_hunter_lance = obj("dragonhunter_lance")
    val dragon_hunter_wand = obj("dragonhunter_wand")
    val dragon_hunter_crossbow = obj("dragonhunter_xbow")
    val dragon_hunter_crossbow_t = obj("dragonhunter_xbow_vorkath")
    val dragon_hunter_crossbow_b = obj("dragonhunter_xbow_kbd")
    val barronite_mace = obj("barronite_mace")
    val barronite_mace_l = obj("barronite_mace_trouver")
    val viggoras_chainmace = obj("wild_cave_chainmace_charged")
    val ursine_chainmace = obj("wild_cave_ursine_charged")
    val craws_bow = obj("wild_cave_bow_charged")
    val webweaver_bow = obj("wild_cave_webweaver_charged")
    val leafbladed_sword = obj("leafbladed_sword")
    val leafbladed_spear = obj("slayer_leafbladed_spear")
    val leafbladed_battleaxe = obj("leafbladed_battleaxe")
    val colossal_blade = obj("giants_foundry_colossal_blade")
    val gadderhammer = obj("gadderanks_warhammer")
    val elysian_spirit_shield = obj("elysian")
    val dinhs_bulwark = obj("dinhs_bulwark")
    val dinhs_blazing_bulwark = obj("dinhs_bulwark_ornament")
    val osmumtens_fang = obj("osmumtens_fang")
    val osmumtens_fang_or = obj("osmumtens_fang_ornament")
    val amulet_of_rancour = obj("amulet_of_rancour")
    val radas_blessing_4 = obj("zeah_blessing_elite")
    val ferocious_gloves = obj("ferocious_gloves")
    val ghrazi_rapier = obj("ghrazi_rapier")

    val tumekens_shadow_uncharged = obj("tumekens_shadow_uncharged")
    val tumekens_shadow = obj("tumekens_shadow")
    val twisted_bow = obj("twisted_bow")
    val scythe_of_vitur = obj("scythe_of_vitur")

    val scorching_bow = obj("scorching_bow")
    val blue_moon_spear = obj("frostmoon_spear")

    val bone_mace = obj("rat_bone_mace")
    val bone_shortbow = obj("rat_bone_bow")

    val inquisitors_great_helm = obj("inquisitors_helm")
    val inquisitors_hauberk = obj("inquisitors_body")
    val inquisitors_plateskirt = obj("inquisitors_skirt")
    val inquisitors_mace = obj("inquisitors_mace")

    val justiciar_faceguard = obj("justiciar_faceguard")
    val justiciar_chestguard = obj("justiciar_chestguard")
    val justiciar_legguards = obj("justiciar_leg_guards")

    val torva_full_helm = obj("torva_helm")
    val torva_platebody = obj("torva_chest")
    val torva_platelegs = obj("torva_legs")

    val virtus_mask = obj("virtus_mask")
    val virtus_robe_top = obj("virtus_top")
    val virtus_robe_bottom = obj("virtus_legs")

    val echo_virtus_mask = obj("virtus_mask_ornament")
    val echo_virtus_robe_top = obj("virtus_top_ornament")
    val echo_virtus_robe_bottom = obj("virtus_legs_ornament")

    val ancestral_hat = obj("ancestral_hat")
    val ancestral_robe_top = obj("ancestral_robe_top")
    val ancestral_robe_bottom = obj("ancestral_robe_bottom")

    val keris = obj("contact_keris")
    val keris_p = obj("contact_keris_p")
    val keris_p_plus = obj("contact_keris_p+")
    val keris_p_plus_plus = obj("contact_keris_p++")
    val keris_partisan = obj("keris_partisan")
    val keris_partisan_of_breaching = obj("keris_partisan_breach")
    val keris_partisan_of_corruption = obj("keris_partisan_corruption")
    val keris_partisan_of_the_sun = obj("keris_partisan_sun")

    val void_mage_helm = obj("game_pest_mage_helm")
    val void_ranger_helm = obj("game_pest_archer_helm")
    val void_melee_helm = obj("game_pest_melee_helm")
    val void_top = obj("pest_void_knight_top")
    val void_robe = obj("pest_void_knight_robes")
    val void_gloves = obj("pest_void_knight_gloves")
    val elite_void_top = obj("elite_void_knight_top")
    val elite_void_robe = obj("elite_void_knight_robes")

    val void_mage_helm_l = obj("game_pest_mage_helm_trouver")
    val void_ranger_helm_l = obj("game_pest_archer_helm_trouver")
    val void_melee_helm_l = obj("game_pest_melee_helm_trouver")
    val void_top_l = obj("pest_void_knight_top_trouver")
    val void_robe_l = obj("pest_void_knight_robes_trouver")
    val void_gloves_l = obj("pest_void_knight_gloves_trouver")
    val elite_void_top_l = obj("elite_void_knight_top_trouver")
    val elite_void_robe_l = obj("elite_void_knight_robes_trouver")

    val void_mage_helm_or = obj("league_3_void_mage_helm")
    val void_ranger_helm_or = obj("league_3_void_range_helm")
    val void_melee_helm_or = obj("league_3_void_melee_helm")
    val void_top_or = obj("league_3_void_knight_top")
    val void_robe_or = obj("league_3_void_knight_robes")
    val void_gloves_or = obj("league_3_void_knight_gloves")
    val elite_void_top_or = obj("league_3_void_knight_top_elite")
    val elite_void_robe_or = obj("league_3_void_knight_robes_elite")

    val void_mage_helm_l_or = obj("league_3_void_mage_helm_trouver")
    val void_ranger_helm_l_or = obj("league_3_void_range_helm_trouver")
    val void_melee_helm_l_or = obj("league_3_void_melee_helm_trouver")
    val void_top_l_or = obj("league_3_void_knight_top_trouver")
    val void_robe_l_or = obj("league_3_void_knight_robes_trouver")
    val void_gloves_l_or = obj("league_3_void_knight_gloves_trouver")
    val elite_void_top_l_or = obj("league_3_void_knight_top_elite_trouver")
    val elite_void_robe_l_or = obj("league_3_void_knight_robes_elite_trouver")

    val dharoks_helm_100 = obj("barrows_dharok_head_100")
    val dharoks_helm_75 = obj("barrows_dharok_head_75")
    val dharoks_helm_50 = obj("barrows_dharok_head_50")
    val dharoks_helm_25 = obj("barrows_dharok_head_25")

    val dharoks_platebody_100 = obj("barrows_dharok_body_100")
    val dharoks_platebody_75 = obj("barrows_dharok_body_75")
    val dharoks_platebody_50 = obj("barrows_dharok_body_50")
    val dharoks_platebody_25 = obj("barrows_dharok_body_25")

    val dharoks_platelegs_100 = obj("barrows_dharok_legs_100")
    val dharoks_platelegs_75 = obj("barrows_dharok_legs_75")
    val dharoks_platelegs_50 = obj("barrows_dharok_legs_50")
    val dharoks_platelegs_25 = obj("barrows_dharok_legs_25")

    val dharoks_greataxe_100 = obj("barrows_dharok_weapon_100")
    val dharoks_greataxe_75 = obj("barrows_dharok_weapon_75")
    val dharoks_greataxe_50 = obj("barrows_dharok_weapon_50")
    val dharoks_greataxe_25 = obj("barrows_dharok_weapon_25")

    val torags_helm_100 = obj("barrows_torag_head_100")
    val torags_helm_75 = obj("barrows_torag_head_75")
    val torags_helm_50 = obj("barrows_torag_head_50")
    val torags_helm_25 = obj("barrows_torag_head_25")

    val torags_platebody_100 = obj("barrows_torag_body_100")
    val torags_platebody_75 = obj("barrows_torag_body_75")
    val torags_platebody_50 = obj("barrows_torag_body_50")
    val torags_platebody_25 = obj("barrows_torag_body_25")

    val torags_platelegs_100 = obj("barrows_torag_legs_100")
    val torags_platelegs_75 = obj("barrows_torag_legs_75")
    val torags_platelegs_50 = obj("barrows_torag_legs_50")
    val torags_platelegs_25 = obj("barrows_torag_legs_25")

    val torags_hammers_100 = obj("barrows_torag_weapon_100")
    val torags_hammers_75 = obj("barrows_torag_weapon_75")
    val torags_hammers_50 = obj("barrows_torag_weapon_50")
    val torags_hammers_25 = obj("barrows_torag_weapon_25")

    val veracs_helm_100 = obj("barrows_verac_head_100")
    val veracs_helm_75 = obj("barrows_verac_head_75")
    val veracs_helm_50 = obj("barrows_verac_head_50")
    val veracs_helm_25 = obj("barrows_verac_head_25")

    val veracs_brassard_100 = obj("barrows_verac_body_100")
    val veracs_brassard_75 = obj("barrows_verac_body_75")
    val veracs_brassard_50 = obj("barrows_verac_body_50")
    val veracs_brassard_25 = obj("barrows_verac_body_25")

    val veracs_plateskirt_100 = obj("barrows_verac_legs_100")
    val veracs_plateskirt_75 = obj("barrows_verac_legs_75")
    val veracs_plateskirt_50 = obj("barrows_verac_legs_50")
    val veracs_plateskirt_25 = obj("barrows_verac_legs_25")

    val veracs_flail_100 = obj("barrows_verac_weapon_100")
    val veracs_flail_75 = obj("barrows_verac_weapon_75")
    val veracs_flail_50 = obj("barrows_verac_weapon_50")
    val veracs_flail_25 = obj("barrows_verac_weapon_25")

    val ahrims_hood_100 = obj("barrows_ahrim_head_100")
    val ahrims_hood_75 = obj("barrows_ahrim_head_75")
    val ahrims_hood_50 = obj("barrows_ahrim_head_50")
    val ahrims_hood_25 = obj("barrows_ahrim_head_25")

    val ahrims_robetop_100 = obj("barrows_ahrim_body_100")
    val ahrims_robetop_75 = obj("barrows_ahrim_body_75")
    val ahrims_robetop_50 = obj("barrows_ahrim_body_50")
    val ahrims_robetop_25 = obj("barrows_ahrim_body_25")

    val ahrims_robeskirt_100 = obj("barrows_ahrim_legs_100")
    val ahrims_robeskirt_75 = obj("barrows_ahrim_legs_75")
    val ahrims_robeskirt_50 = obj("barrows_ahrim_legs_50")
    val ahrims_robeskirt_25 = obj("barrows_ahrim_legs_25")

    val ahrims_staff_100 = obj("barrows_ahrim_weapon_100")
    val ahrims_staff_75 = obj("barrows_ahrim_weapon_75")
    val ahrims_staff_50 = obj("barrows_ahrim_weapon_50")
    val ahrims_staff_25 = obj("barrows_ahrim_weapon_25")

    val amulet_of_the_damned_full = obj("damned_amulet")

    val efaritays_aid = obj("vampyre_ring")

    val woodcutting_icon = obj("tree_icon_dummy")
    val bank_icon = obj("bank_icon_dummy")
    val furnace_icon = obj("furnace_icon_dummy")
    val mining_icon = obj("mining_tutor_icon_dummy")
    val smithing_icon = obj("smithing_tutor_icon_dummy")
}
