@file:Suppress("SpellCheckingInspection", "unused")

package org.rsmod.api.config.refs

import org.rsmod.api.type.refs.spot.SpotanimReferences

typealias spotanims = BaseSpotanims

object BaseSpotanims : SpotanimReferences() {
    val osb8_skillcape_banana_spotanim = spotAnim("osb8_skillcape_banana_spotanim")
    val smokepuff = spotAnim("smokepuff")
    val sp_attackglow_red = spotAnim("sp_attackglow_red")

    val hw07_arm_from_the_ground_spotanim = spotAnim("hw07_arm_from_the_ground_spotanim")
    val skillcape_diary_spotanim = spotAnim("skillcape_diary_spotanim")
    val trollromance_heart = spotAnim("trollromance_heart")
    val poh_absorb_tablet_magic = spotAnim("poh_absorb_tablet_magic")
    val emote_lightbulb_spot = spotAnim("emote_lightbulb_spot")
    val emote_duststamp_spot = spotAnim("emote_duststamp_spot")
    val skillcapes_fletching_bow_spotanim = spotAnim("skillcapes_fletching_bow_spotanim")
    val skillcapes_magic_spotanim = spotAnim("skillcapes_magic_spotanim")
    val skillcapes_mining_spotanim = spotAnim("skillcapes_mining_spotanim")
    val skillcapes_smithing_spotanim = spotAnim("skillcapes_smithing_spotanim")
    val skillcapes_quest_cape_spotanim = spotAnim("skillcapes_quest_cape_spotanim")
    val skillcapes_runecrafting_spotanim = spotAnim("skillcapes_runecrafting_spotanim")
    val skillcapes_crafting_spotanim = spotAnim("skillcapes_crafting_spotanim")
    val skillcapes_fishing_spotanim = spotAnim("skillcapes_fishing_spotanim")
    val skillcapes_construction_spotanim = spotAnim("skillcapes_construction_spotanim")
    val skillcapes_cooking_spotanim = spotAnim("skillcapes_cooking_spotanim")
    val skillcapes_woodcutting_spotanim = spotAnim("skillcapes_woodcutting_spotanim")
    val skillcape_attack_spotanim = spotAnim("skillcape_attack_spotanim")
    val skillcape_defend_spotanim = spotAnim("skillcape_defend_spotanim")
    val skillcape_farming_spotanim = spotAnim("skillcape_farming_spotanim")
    val skillcape_thieving_spotanim = spotAnim("skillcape_thieving_spotanim")
    val skillcape_slayer_spotanim = spotAnim("skillcape_slayer_spotanim")
    val skillcapes_strength = spotAnim("skillcapes_strength")
    val skillcapes_prayer = spotAnim("skillcapes_prayer")
    val skillcapes_agility = spotAnim("skillcapes_agility")
    val skillcapes_firemaking = spotAnim("skillcapes_firemaking")
    val skillcapes_range = spotAnim("skillcapes_range")
    val skillcapes_hitpoints = spotAnim("skillcapes_hitpoints")
    val skillcapes_herblore = spotAnim("skillcapes_herblore")
    val skillcapes_hunting = spotAnim("skillcapes_hunting")
    val air_guitar_spotanim = spotAnim("air_guitar_spotanim")
    val max_cape = spotAnim("max_cape")
    val briefcase_spotanim = spotAnim("briefcase_spotanim")
    val dinhs_bulwark_glow_idle = spotAnim("dinhs_bulwark_glow_idle")
    val premier_club_emote_spotanim_bronze = spotAnim("premier_club_emote_spotanim_bronze")
    val premier_club_emote_spotanim_silver = spotAnim("premier_club_emote_spotanim_silver")
    val premier_club_emote_spotanim_gold = spotAnim("premier_club_emote_spotanim_gold")
    val league_twisted_relic_unlock_spot = spotAnim("league_twisted_relic_unlock_spot")
    val league_trailblazer_relic_unlock_spot = spotAnim("league_trailblazer_relic_unlock_spot")
    val fx_emote_party01_active = spotAnim("fx_emote_party01_active")
    val hw23_emote_bat_spotanim = spotAnim("hw23_emote_bat_spotanim")

    val ballista_special = spotAnim("ballista_special")

    val darkbow_dragon_head_flying_projanim = spotAnim("darkbow_dragon_head_flying_projanim")
    val darkbow_dragon_head_flying_impact_anim = spotAnim("darkbow_dragon_head_flying_impact_anim")
    val darkbow_generic_smoke_arrow_flight = spotAnim("darkbow_generic_smoke_arrow_flight")
    val darkbow_smoke_arrow_impact = spotAnim("darkbow_smoke_arrow_impact")

    val stunned = spotAnim("stunned")
    val failedspell_impact = spotAnim("failedspell_impact")

    val windstrike_casting = spotAnim("windstrike_casting")
    val windstrike_travel = spotAnim("windstrike_travel")
    val windstrike_impact = spotAnim("windstrike_impact")
    val waterstrike_casting = spotAnim("waterstrike_casting")
    val waterstrike_travel = spotAnim("waterstrike_travel")
    val waterstrike_impact = spotAnim("waterstrike_impact")
    val earthstrike_casting = spotAnim("earthstrike_casting")
    val earthstrike_travel = spotAnim("earthstrike_travel")
    val earthstrike_impact = spotAnim("earthstrike_impact")
    val firestrike_casting = spotAnim("firestrike_casting")
    val firestrike_travel = spotAnim("firestrike_travel")
    val firestrike_impact = spotAnim("firestrike_impact")

    val windbolt_casting = spotAnim("windbolt_casting")
    val windbolt_travel = spotAnim("windbolt_travel")
    val windbolt_impact = spotAnim("windbolt_impact")
    val waterbolt_casting = spotAnim("waterbolt_casting")
    val waterbolt_travel = spotAnim("waterbolt_travel")
    val waterbolt_impact = spotAnim("waterbolt_impact")
    val earthbolt_casting = spotAnim("earthbolt_casting")
    val earthbolt_travel = spotAnim("earthbolt_travel")
    val earthbolt_impact = spotAnim("earthbolt_impact")
    val firebolt_casting = spotAnim("firebolt_casting")
    val firebolt_travel = spotAnim("firebolt_travel")
    val firebolt_impact = spotAnim("firebolt_impact")

    val fireblast_casting = spotAnim("fireblast_casting")
    val fireblast_travel = spotAnim("fireblast_travel")
    val fireblast_impact = spotAnim("fireblast_impact")
    val windblast_casting = spotAnim("windblast_casting")
    val windblast_travel = spotAnim("windblast_travel")
    val windblast_impact = spotAnim("windblast_impact")
    val waterblast_casting = spotAnim("waterblast_casting")
    val waterblast_travel = spotAnim("waterblast_travel")
    val waterblast_impact = spotAnim("waterblast_impact")
    val earthblast_casting = spotAnim("earthblast_casting")
    val earthblast_travel = spotAnim("earthblast_travel")
    val earthblast_impact = spotAnim("earthblast_impact")

    val firewave_casting = spotAnim("firewave_casting")
    val firewave_travel = spotAnim("firewave_travel")
    val firewave_impact = spotAnim("firewave_impact")
    val windwave_casting = spotAnim("windwave_casting")
    val windwave_travel = spotAnim("windwave_travel")
    val windwave_impact = spotAnim("windwave_impact")
    val waterwave_casting = spotAnim("waterwave_casting")
    val waterwave_travel = spotAnim("waterwave_travel")
    val waterwave_impact = spotAnim("waterwave_impact")
    val earthwave_casting = spotAnim("earthwave_casting")
    val earthwave_travel = spotAnim("earthwave_travel")
    val earthwave_impact = spotAnim("earthwave_impact")

    val windsurge_casting = spotAnim("windsurge_casting")
    val windsurge_travel = spotAnim("windsurge_travel")
    val windsurge_impact = spotAnim("windsurge_impact")
    val watersurge_casting = spotAnim("watersurge_casting")
    val watersurge_travel = spotAnim("watersurge_travel")
    val watersurge_impact = spotAnim("watersurge_impact")
    val earthsurge_casting = spotAnim("earthsurge_casting")
    val earthsurge_travel = spotAnim("earthsurge_travel")
    val earthsurge_impact = spotAnim("earthsurge_impact")
    val firesurge_casting = spotAnim("firesurge_casting")
    val firesurge_travel = spotAnim("firesurge_travel")
    val firesurge_impact = spotAnim("firesurge_impact")

    val tumekens_shadow_casting = spotAnim("tumekens_shadow_casting")
    val tumekens_shadow_travel = spotAnim("tumekens_shadow_travel")
    val tumekens_shadow_impact = spotAnim("tumekens_shadow_impact")
}
