@file:Suppress("SpellCheckingInspection", "unused")

package org.rsmod.api.config.refs

import dev.openrune.content

typealias content = BaseContent

object BaseContent {
    val closed_single_door = content("closed_single_door")
    val opened_single_door = content("opened_single_door")
    val closed_left_door = content("closed_left_door")
    val closed_right_door = content("closed_right_door")
    val opened_left_door = content("opened_left_door")
    val opened_right_door = content("opened_right_door")
    val bookcase = content("bookcase")
    val ladder_down = content("ladder_down")
    val ladder_up = content("ladder_up")
    val ladder_option = content("ladder_option")
    val empty_crate = content("empty_crate")
    val empty_chest = content("empty_chest")
    val empty_boxes = content("empty_boxes")
    val empty_sacks = content("empty_sacks")
    val banker = content("banker")
    val bank_booth = content("bank_booth")
    val bank_chest = content("bank_chest")
    val bank_deposit_box = content("bank_deposit_box")
    val person = content("person")
    val dungeonladder_down = content("dungeonladder_down")
    val dungeonladder_up = content("dungeonladder_up")
    val spiralstaircase_down = content("spiralstaircase_down")
    val spiralstaircase_up = content("spiralstaircase_up")
    val spiralstaircase_option = content("spiralstaircase_option")
    val duck = content("duck")
    val duckling = content("duckling")
    val woodcutting_axe = content("woodcutting_axe")
    val closed_left_picketgate = content("closed_left_picketgate")
    val closed_right_picketgate = content("closed_right_picketgate")
    val opened_left_picketgate = content("opened_left_picketgate")
    val opened_right_picketgate = content("opened_right_picketgate")
    val ore = content("ore")
    val tree = content("tree")
    val chicken_outfit = content("chicken_outfit")
    val skill_cape = content("skill_cape")
    val skill_hood = content("skill_hood")
    val max_cape = content("max_cape")
    val max_hood = content("max_hood")
    val food = content("food")
    val potion = content("potion")
    val banker_tutor = content("banker_tutor")
    val sheep = content("sheep")
    val sheared_sheep = content("sheared_sheep")
    val cow = content("cow")
    val dairy_cow = content("dairy_cow")
    val cow_calf = content("cow_calf")
    val pickable_crop = content("pickable_crop")
    val chicken_coop = content("chicken_coop")
}
