@file:Suppress("SpellCheckingInspection", "unused")

package org.rsmod.api.config.refs

import dev.openrune.seq

typealias seqs = BaseSeqs

object BaseSeqs {
    val human_unarmedpunch = seq("human_unarmedpunch")
    val human_unarmedkick = seq("human_unarmedkick")
    val human_unarmedblock = seq("human_unarmedblock")
    val human_bow = seq("human_bow")
    val human_death = seq("human_death")

    val human_ready = seq("human_ready")
    val human_walk_f = seq("human_walk_f")
    val human_walk_b = seq("human_walk_b")
    val human_walk_l = seq("human_walk_l")
    val human_walk_r = seq("human_walk_r")
    val human_turnonspot = seq("human_turnonspot")
    val human_running = seq("human_running")
    val human_pickupfloor = seq("human_pickupfloor")
    val human_reachforladder = seq("human_reachforladder")
    val human_pickuptable = seq("human_pickuptable")
    val human_shearing = seq("human_shearing")
    val milkit = seq("milkit")
    val poh_smash_magic_tablet = seq("poh_smash_magic_tablet")
    val poh_absorb_tablet_teleport = seq("poh_absorb_tablet_teleport")

    val human_caststrike = seq("human_caststrike")
    val human_castwave = seq("human_castwave")
    val human_caststrike_staff = seq("human_caststrike_staff")
    val human_castwave_staff = seq("human_castwave_staff")
    val human_cast_surge = seq("human_cast_surge")
    val toa_sot_cast_b = seq("toa_sot_cast_b")

    val human_woodcutting_bronze_axe = seq("human_woodcutting_bronze_axe")
    val human_woodcutting_iron_axe = seq("human_woodcutting_iron_axe")
    val human_woodcutting_steel_axe = seq("human_woodcutting_steel_axe")
    val human_woodcutting_black_axe = seq("human_woodcutting_black_axe")
    val human_woodcutting_mithril_axe = seq("human_woodcutting_mithril_axe")
    val human_woodcutting_adamant_axe = seq("human_woodcutting_adamant_axe")
    val human_woodcutting_blessed_axe = seq("human_woodcutting_blessed_axe")
    val human_woodcutting_rune_axe = seq("human_woodcutting_rune_axe")
    val human_woodcutting_gilded_axe = seq("human_woodcutting_gilded_axe")
    val human_woodcutting_dragon_axe = seq("human_woodcutting_dragon_axe")
    val human_woodcutting_trailblazer_axe_no_infernal =
        seq("human_woodcutting_trailblazer_axe_no_infernal")
    val human_woodcutting_3a_axe = seq("human_woodcutting_3a_axe")
    val human_woodcutting_infernal_axe = seq("human_woodcutting_infernal_axe")
    val human_woodcutting_trailblazer_axe = seq("human_woodcutting_trailblazer_axe")
    val human_woodcutting_crystal_axe = seq("human_woodcutting_crystal_axe")

    val chatquiz1 = seq("chatquiz1")
    val chatquiz2 = seq("chatquiz2")
    val chatquiz3 = seq("chatquiz3")
    val chatquiz4 = seq("chatquiz4")

    val chatbored1 = seq("chatbored1")
    val chatbored2 = seq("chatbored2")
    val chatbored3 = seq("chatbored3")
    val chatbored4 = seq("chatbored4")

    val shortchatneu1 = seq("shortchatneu1")

    val chathap1 = seq("chathap1")
    val chathap2 = seq("chathap2")
    val chathap3 = seq("chathap3")
    val chathap4 = seq("chathap4")

    val chatshock1 = seq("chatshock1")
    val chatshock2 = seq("chatshock2")
    val chatshock3 = seq("chatshock3")
    val chatshock4 = seq("chatshock4")

    val chatcon1 = seq("chatcon1")
    val chatcon2 = seq("chatcon2")
    val chatcon3 = seq("chatcon3")
    val chatcon4 = seq("chatcon4")

    val chatidleneu1 = seq("chatidleneu1")

    val chatgoblin1 = seq("chatgoblin1")
    val chatgoblin2 = seq("chatgoblin2")
    val chatgoblin3 = seq("chatgoblin3")
    val chatgoblin4 = seq("chatgoblin4")

    val chatneu1 = seq("chatneu1")
    val chatneu2 = seq("chatneu2")
    val chatneu3 = seq("chatneu3")
    val chatneu4 = seq("chatneu4")

    val chatshifty1 = seq("chatshifty1")
    val chatshifty2 = seq("chatshifty2")
    val chatshifty3 = seq("chatshifty3")
    val chatshifty4 = seq("chatshifty4")

    val chatscared1 = seq("chatscared1")
    val chatscared2 = seq("chatscared2")
    val chatscared3 = seq("chatscared3")
    val chatscared4 = seq("chatscared4")

    val chatdrunk1 = seq("chatdrunk1")
    val chatdrunk2 = seq("chatdrunk2")
    val chatdrunk3 = seq("chatdrunk3")
    val chatdrunk4 = seq("chatdrunk4")

    val evilidle1 = seq("evilidle1")

    val chatlaugh1 = seq("chatlaugh1")
    val chatlaugh2 = seq("chatlaugh2")
    val chatlaugh3 = seq("chatlaugh3")
    val chatlaugh4 = seq("chatlaugh4")

    val evillaugh1 = seq("evillaugh1")

    val chatsad1 = seq("chatsad1")
    val chatsad2 = seq("chatsad2")
    val chatsad3 = seq("chatsad3")
    val chatsad4 = seq("chatsad4")

    val chatang1 = seq("chatang1")
    val chatang2 = seq("chatang2")
    val chatang3 = seq("chatang3")
    val chatang4 = seq("chatang4")

    val emote_yes = seq("emote_yes")
    val emote_yes_loop = seq("emote_yes_loop")
    val emote_no = seq("emote_no")
    val emote_no_loop = seq("emote_no_loop")
    val emote_think = seq("emote_think")
    val emote_think_loop = seq("emote_think_loop")
    val emote_bow = seq("emote_bow")
    val emote_bow_loop = seq("emote_bow_loop")
    val emote_angry = seq("emote_angry")
    val emote_angry_loop = seq("emote_angry_loop")
    val emote_cry = seq("emote_cry")
    val emote_cry_loop = seq("emote_cry_loop")
    val emote_laugh = seq("emote_laugh")
    val emote_laugh_loop = seq("emote_laugh_loop")
    val emote_cheer = seq("emote_cheer")
    val emote_cheer_loop = seq("emote_cheer_loop")
    val emote_wave = seq("emote_wave")
    val emote_wave_loop = seq("emote_wave_loop")
    val emote_beckon = seq("emote_beckon")
    val emote_beckon_loop = seq("emote_beckon_loop")
    val emote_clap = seq("emote_clap")
    val emote_clap_loop = seq("emote_clap_loop")
    val emote_dance = seq("emote_dance")
    val emote_dance_loop = seq("emote_dance_loop")
    val emote_run_on_spot = seq("emote_run_on_spot")
    val emote_run_on_spot_loop = seq("emote_run_on_spot_loop")
    val emote_starjump_5 = seq("emote_starjump_5")
    val emote_starjump_5_loop = seq("emote_starjump_5_loop")
    val emote_pushups_5 = seq("emote_pushups_5")
    val emote_pushups_5_loop = seq("emote_pushups_5_loop")
    val emote_situps_5 = seq("emote_situps_5")
    val emote_situps_5_loop = seq("emote_situps_5_loop")
    val emote_glass_wall = seq("emote_glass_wall")
    val emote_glass_wall_loop = seq("emote_glass_wall_loop")
    val emote_mime_lean = seq("emote_mime_lean")
    val emote_mime_lean_loop = seq("emote_mime_lean_loop")
    val emote_climbing_rope = seq("emote_climbing_rope")
    val emote_climbing_rope_loop = seq("emote_climbing_rope_loop")
    val emote_glass_box = seq("emote_glass_box")
    val emote_glass_box_loop = seq("emote_glass_box_loop")
    val emote_blow_kiss = seq("emote_blow_kiss")
    val emote_blow_kiss_loop = seq("emote_blow_kiss_loop")
    val emote_panic = seq("emote_panic")
    val emote_panic_loop = seq("emote_panic_loop")
    val emote_dance_scottish = seq("emote_dance_scottish")
    val emote_dance_scottish_loop = seq("emote_dance_scottish_loop")
    val emote_dance_spin = seq("emote_dance_spin")
    val emote_dance_spin_loop = seq("emote_dance_spin_loop")
    val emote_dance_headbang = seq("emote_dance_headbang")
    val emote_dance_headbang_loop = seq("emote_dance_headbang_loop")
    val emote_jump_with_joy = seq("emote_jump_with_joy")
    val emote_jump_with_joy_loop = seq("emote_jump_with_joy_loop")
    val emote_ya_boo_sucks = seq("emote_ya_boo_sucks")
    val emote_ya_boo_sucks_loop = seq("emote_ya_boo_sucks_loop")
    val emote_yawn = seq("emote_yawn")
    val emote_yawn_loop = seq("emote_yawn_loop")
    val emote_fremmenik_salute = seq("emote_fremmenik_salute")
    val emote_fremmenik_salute_loop = seq("emote_fremmenik_salute_loop")
    val emote_shrug = seq("emote_shrug")
    val emote_shrug_loop = seq("emote_shrug_loop")
    val human_cave_goblin_bow = seq("human_cave_goblin_bow")
    val human_cave_goblin_bow_loop = seq("human_cave_goblin_bow_loop")
    val human_cave_goblin_dance = seq("human_cave_goblin_dance")
    val human_cave_goblin_dance_loop = seq("human_cave_goblin_dance_loop")
    val diary_emote_spotanim = seq("diary_emote_spotanim")
    val diary_emote_playeranim = seq("diary_emote_playeranim")
    val terrified_emote = seq("terrified_emote")
    val terrified_emote_loop = seq("terrified_emote_loop")
    val zombie_dance = seq("zombie_dance")
    val zombie_dance_loop = seq("zombie_dance_loop")
    val zombie_walk_emote = seq("zombie_walk_emote")
    val zombie_walk_emote_loop = seq("zombie_walk_emote_loop")
    val emote_slap_head = seq("emote_slap_head")
    val emote_slap_head_loop = seq("emote_slap_head_loop")
    val emote_lightbulb = seq("emote_lightbulb")
    val emote_lightbulb_loop = seq("emote_lightbulb_loop")
    val emote_stampfeet = seq("emote_stampfeet")
    val emote_stampfeet_loop = seq("emote_stampfeet_loop")
    val emote_panic_flap = seq("emote_panic_flap")
    val emote_panic_flap_loop = seq("emote_panic_flap_loop")
    val hw07_arm_from_the_ground_emote = seq("hw07_arm_from_the_ground_emote")
    val emote_air_guitar = seq("emote_air_guitar")
    val skillcapes_player_fletching_bow = seq("skillcapes_player_fletching_bow")
    val skillcapes_player_magic = seq("skillcapes_player_magic")
    val skillcapes_player_mining = seq("skillcapes_player_mining")
    val skillcapes_player_smithing = seq("skillcapes_player_smithing")
    val skillcapes_player_quest_cape = seq("skillcapes_player_quest_cape")
    val skillcapes_player_runecrafting = seq("skillcapes_player_runecrafting")
    val skillcapes_crafting_player_anim = seq("skillcapes_crafting_player_anim")
    val skillcapes_fishing_player_anim = seq("skillcapes_fishing_player_anim")
    val skillcapes_construction_player_anim = seq("skillcapes_construction_player_anim")
    val skillcapes_cooking_player_anim = seq("skillcapes_cooking_player_anim")
    val skillcapes_woodcutting_player_anim = seq("skillcapes_woodcutting_player_anim")
    val skill_cape_attack = seq("skill_cape_attack")
    val skill_cape_defend = seq("skill_cape_defend")
    val skillcape_farming = seq("skillcape_farming")
    val skill_cape_thieving = seq("skill_cape_thieving")
    val skill_cape_slayer = seq("skill_cape_slayer")
    val skillcapes_human_herblore = seq("skillcapes_human_herblore")
    val skillcapes_human_hitpoints = seq("skillcapes_human_hitpoints")
    val skillcapes_human_range = seq("skillcapes_human_range")
    val skillcapes_human_firemaking = seq("skillcapes_human_firemaking")
    val skillcapes_human_agility = seq("skillcapes_human_agility")
    val skillcapes_human_prayer = seq("skillcapes_human_prayer")
    val skillcapes_human_strength = seq("skillcapes_human_strength")
    val skillcapes_human_hunting = seq("skillcapes_human_hunting")
    val rabbit_emote = seq("rabbit_emote")
    val rabbit_emote_loop = seq("rabbit_emote_loop")
    val vm_natural_historian_monkey_hop = seq("vm_natural_historian_monkey_hop")
    val max_cape_player_anim = seq("max_cape_player_anim")
    val ash_emote = seq("ash_emote")
    val ash_emote_loop = seq("ash_emote_loop")
    val eoc_pick_strength_success = seq("eoc_pick_strength_success")
    val emote_uri_briefcase = seq("emote_uri_briefcase")
    val bday17_bling = seq("bday17_bling")
    val bday17_style = seq("bday17_style")
    val bday17_style_loop = seq("bday17_style_loop")
    val bday17_lasso = seq("bday17_lasso")
    val bday17_lasso_loop = seq("bday17_lasso_loop")
    val premier_club_emote = seq("premier_club_emote")
    val human_relic_unlock = seq("human_relic_unlock")
    val human_relic_unlock_female = seq("human_relic_unlock_female")
    val emote_explore = seq("emote_explore")
    val emote_explore_loop = seq("emote_explore_loop")
    val osb8_skillcape_banana_emote = seq("osb8_skillcape_banana_emote")
    val emote_flex = seq("emote_flex")
    val emote_flex_loop = seq("emote_flex_loop")
    val emote_party = seq("emote_party")
    val emote_party_loop = seq("emote_party_loop")
    val emote_sit = seq("emote_sit")
    val emote_sit_loop = seq("emote_sit_loop")
    val emote_trick = seq("emote_trick")
    val emote_varlamore_salute = seq("emote_varlamore_salute")
    val emote_varlamore_salute_loop = seq("emote_varlamore_salute_loop")

    val cow_update_graze = seq("cow_update_graze")
}
