[[varbit]]
id = "varbit.toolbelt_slot_0"
varp = "varp.toolbelt_slot_0"
startBit = 0
endBit = 15

[[varbit]]
id = "varbit.toolbelt_slot_1"
varp = "varp.toolbelt_slot_1"
startBit = 0
endBit = 15

[[varbit]]
id = "varbit.toolbelt_slot_2"
varp = "varp.toolbelt_slot_2"
startBit = 0
endBit = 15

[[varbit]]
id = "varbit.toolbelt_slot_3"
varp = "varp.toolbelt_slot_3"
startBit = 0
endBit = 15

[[varbit]]
id = "varbit.toolbelt_slot_4"
varp = "varp.toolbelt_slot_4"
startBit = 0
endBit = 15

[[varbit]]
id = "varbit.toolbelt_slot_5"
varp = "varp.toolbelt_slot_5"
startBit = 0
endBit = 15

[[varbit]]
id = "varbit.toolbelt_slot_6"
varp = "varp.toolbelt_slot_6"
startBit = 0
endBit = 15

[[varbit]]
id = "varbit.toolbelt_slot_7"
varp = "varp.toolbelt_slot_7"
startBit = 0
endBit = 15

[[varbit]]
id = "varbit.toolbelt_slot_8"
varp = "varp.toolbelt_slot_8"
startBit = 0
endBit = 15

[[varbit]]
id = "varbit.toolbelt_slot_9"
varp = "varp.toolbelt_slot_9"
startBit = 0
endBit = 15

[[varbit]]
id = "varbit.toolbelt_slot_10"
varp = "varp.toolbelt_slot_10"
startBit = 0
endBit = 15

[[varbit]]
id = "varbit.toolbelt_slot_11"
varp = "varp.toolbelt_slot_11"
startBit = 0
endBit = 15

[[varbit]]
id = "varbit.toolbelt_slot_12"
varp = "varp.toolbelt_slot_12"
startBit = 0
endBit = 15

[[varbit]]
id = "varbit.toolbelt_slot_13"
varp = "varp.toolbelt_slot_13"
startBit = 0
endBit = 15

[[varbit]]
id = "varbit.toolbelt_slot_14"
varp = "varp.toolbelt_slot_14"
startBit = 0
endBit = 15

[[varbit]]
id = "varbit.toolbelt_slot_15"
varp = "varp.toolbelt_slot_15"
startBit = 0
endBit = 15

[[varbit]]
id = "varbit.toolbelt_slot_16"
varp = "varp.toolbelt_slot_16"
startBit = 0
endBit = 15

[[varbit]]
id = "varbit.toolbelt_slot_17"
varp = "varp.toolbelt_slot_17"
startBit = 0
endBit = 15

[[varbit]]
id = "varbit.toolbelt_slot_18"
varp = "varp.toolbelt_slot_18"
startBit = 0
endBit = 15

[[varbit]]
id = "varbit.toolbelt_slot_19"
varp = "varp.toolbelt_slot_19"
startBit = 0
endBit = 15

[[varbit]]
id = "varbit.toolbelt_slot_20"
varp = "varp.toolbelt_slot_20"
startBit = 0
endBit = 15

[[varbit]]
id = "varbit.toolbelt_slot_21"
varp = "varp.toolbelt_slot_21"
startBit = 0
endBit = 15

[[varbit]]
id = "varbit.toolbelt_slot_22"
varp = "varp.toolbelt_slot_22"
startBit = 0
endBit = 15

[[varbit]]
id = "varbit.toolbelt_slot_23"
varp = "varp.toolbelt_slot_23"
startBit = 0
endBit = 15

[[varbit]]
id = "varbit.toolbelt_slot_24"
varp = "varp.toolbelt_slot_24"
startBit = 0
endBit = 15

[[varbit]]
id = "varbit.toolbelt_slot_25"
varp = "varp.toolbelt_slot_25"
startBit = 0
endBit = 15

[[varbit]]
id = "varbit.toolbelt_slot_26"
varp = "varp.toolbelt_slot_26"
startBit = 0
endBit = 15

[[varbit]]
id = "varbit.toolbelt_slot_27"
varp = "varp.toolbelt_slot_27"
startBit = 0
endBit = 15

