[[varp]]
id = "varp.toolbelt_unlocks"
scope = "Perm"

[[varp]]
id = "varp.toolbelt_slot_0"
scope = "Perm"

[[varp]]
id = "varp.toolbelt_slot_1"
scope = "Perm"

[[varp]]
id = "varp.toolbelt_slot_2"
scope = "Perm"

[[varp]]
id = "varp.toolbelt_slot_3"
scope = "Perm"

[[varp]]
id = "varp.toolbelt_slot_4"
scope = "Perm"

[[varp]]
id = "varp.toolbelt_slot_5"
scope = "Perm"

[[varp]]
id = "varp.toolbelt_slot_6"
scope = "Perm"

[[varp]]
id = "varp.toolbelt_slot_7"
scope = "Perm"

[[varp]]
id = "varp.toolbelt_slot_8"
scope = "Perm"

[[varp]]
id = "varp.toolbelt_slot_9"
scope = "Perm"

[[varp]]
id = "varp.toolbelt_slot_10"
scope = "Perm"

[[varp]]
id = "varp.toolbelt_slot_11"
scope = "Perm"

[[varp]]
id = "varp.toolbelt_slot_12"
scope = "Perm"

[[varp]]
id = "varp.toolbelt_slot_13"
scope = "Perm"

[[varp]]
id = "varp.toolbelt_slot_14"
scope = "Perm"

[[varp]]
id = "varp.toolbelt_slot_15"
scope = "Perm"

[[varp]]
id = "varp.toolbelt_slot_16"
scope = "Perm"

[[varp]]
id = "varp.toolbelt_slot_17"
scope = "Perm"

[[varp]]
id = "varp.toolbelt_slot_18"
scope = "Perm"

[[varp]]
id = "varp.toolbelt_slot_19"
scope = "Perm"

[[varp]]
id = "varp.toolbelt_slot_20"
scope = "Perm"

[[varp]]
id = "varp.toolbelt_slot_21"
scope = "Perm"

[[varp]]
id = "varp.toolbelt_slot_22"
scope = "Perm"

[[varp]]
id = "varp.toolbelt_slot_23"
scope = "Perm"

[[varp]]
id = "varp.toolbelt_slot_24"
scope = "Perm"

[[varp]]
id = "varp.toolbelt_slot_25"
scope = "Perm"

[[varp]]
id = "varp.toolbelt_slot_26"
scope = "Perm"

[[varp]]
id = "varp.toolbelt_slot_27"
scope = "Perm"
