[gamevals.dbtable]
poh_furniture =65506

[gamevals.dbrow]
# Parlour
poh_crude_wooden_chair =64130
poh_wooden_chair =64129
poh_rocking_chair =64128
poh_oak_chair =64127
poh_oak_armchair =64126
poh_teak_armchair =64125
poh_mahogany_armchair =64124
poh_wooden_bookcase =64123
poh_oak_bookcase =64122
poh_mahogany_bookcase =64121
poh_clay_fireplace =64120
poh_stone_fireplace =64119
poh_marble_fireplace =64118
poh_torn_curtains =64117
poh_curtains =64116
poh_opulent_curtains =64115
poh_brown_rug =64114
poh_rug =64113
poh_opulent_rug =64112
# Kitchen
poh_firepit =64111
poh_firepit_with_hook =64110
poh_firepit_with_pot =64109
poh_small_oven =64108
poh_large_oven =64107
poh_steel_range =64106
poh_fancy_range =64105
poh_wooden_shelves_1 =64104
poh_wooden_shelves_2 =64103
poh_wooden_shelves_3 =64102
poh_oak_shelves_1 =64101
poh_oak_shelves_2 =64100
poh_teak_shelves_1 =64099
poh_teak_shelves_2 =64098
poh_pump_and_drain =64097
poh_pump_and_tub =64096
poh_kitchen_sink =64095
poh_gold_sink =64094
poh_wooden_larder =64093
poh_oak_larder =64092
poh_teak_larder =64091
poh_beer_barrel =64090
poh_cider_barrel =64089
poh_asgarnian_ale_barrel =64088
poh_greenmans_ale_barrel =64087
poh_dragon_bitter_barrel =64086
poh_chefs_delight_barrel =64085
poh_cat_blanket =64084
poh_cat_basket =64083
poh_cushioned_basket =64082
poh_kitchen_table =64081
poh_oak_kitchen_table =64080
poh_teak_kitchen_table =64079
poh_spice_rack =64078
# Dining room
poh_wood_dining_table =64077
poh_oak_dining_table =64076
poh_carved_oak_table =64075
poh_teak_table =64074
poh_carved_teak_table =64073
poh_mahogany_table =64072
poh_opulent_table =64071
poh_wooden_bench =64070
poh_wooden_bench_2 =64069
poh_oak_bench =64068
poh_oak_bench_2 =64067
poh_carved_oak_bench =64066
poh_carved_oak_bench_2 =64065
poh_teak_dining_bench =64064
poh_teak_dining_bench_2 =64063
poh_carved_teak_bench =64062
poh_carved_teak_bench_2 =64061
poh_mahogany_bench =64060
poh_mahogany_bench_2 =64059
poh_gilded_bench =64058
poh_gilded_bench_2 =64057
poh_rope_bellpull =64056
poh_bellpull =64055
poh_posh_bellpull =64054
poh_greenman_carving =64053
poh_oak_wall_decoration =64052
poh_teak_wall_decoration =64051
poh_gilded_decoration =64050
# Bedroom
poh_wooden_bed =64049
poh_oak_bed =64048
poh_large_oak_bed =64047
poh_teak_bed =64046
poh_large_teak_bed =64045
poh_four_poster =64044
poh_gilded_four_poster =64043
poh_shoe_box =64042
poh_oak_drawers =64041
poh_oak_wardrobe =64040
poh_teak_drawers =64039
poh_teak_wardrobe =64038
poh_mahogany_wardrobe =64037
poh_gilded_wardrobe =64036
poh_shaving_stand =64035
poh_oak_shaving_stand =64034
poh_oak_dresser =64033
poh_teak_dresser =64032
poh_fancy_teak_dresser =64031
poh_mahogany_dresser =64030
poh_gilded_dresser =64029
poh_oak_clock =64028
poh_teak_clock =64027
poh_servants_moneybag =64026
poh_gilded_clock =64025
# Workshop
poh_wooden_workbench =64024
poh_oak_workbench =64023
poh_steel_framed_workbench =64022
poh_bench_with_vice =64021
poh_bench_with_lathe =64020
poh_workshop_tool_store_1 =64019
poh_workshop_tool_store_2 =64018
poh_workshop_tool_store_3 =64017
poh_workshop_tool_store_4 =64016
poh_workshop_tool_store_5 =64015
poh_workshop_crafting_table_1 =64014
poh_workshop_crafting_table_2 =64013
poh_workshop_crafting_table_3 =64012
poh_workshop_crafting_table_4 =64011
poh_repair_bench =64010
poh_whetstone =64009
poh_armour_stand =64008
poh_pluming_stand =64007
poh_shield_easel =64006
poh_banner_easel =64005
# Study
poh_oak_lectern =64004
poh_eagle_lectern =64003
poh_demon_lectern =64002
poh_teak_eagle_lectern =64001
poh_teak_demon_lectern =64000
poh_mahogany_eagle_lectern =63999
poh_mahogany_demon_lectern =63998
poh_marble_lectern =63997
poh_globe =63996
poh_ornamental_globe =63995
poh_lunar_globe =63994
poh_celestial_globe =63993
poh_armillary_sphere =63992
poh_small_orrery =63991
poh_large_orrery =63990
poh_crystal_ball =63989
poh_elemental_sphere =63988
poh_crystal_of_power =63987
poh_oak_telescope =63986
poh_teak_telescope =63985
poh_mahogany_telescope =63984
poh_alchemical_chart =63983
poh_astronomical_chart =63982
poh_infernal_chart =63981
# Chapel
poh_oak_altar =63980
poh_teak_altar =63979
poh_cloth_altar =63978
poh_mahogany_altar =63977
poh_limestone_altar =63976
poh_marble_altar =63975
poh_gilded_altar =63974
poh_steel_torches =63973
poh_wooden_torches =63972
poh_steel_candlesticks =63971
poh_gold_candlesticks =63970
poh_oak_incense_burners =63969
poh_mahogany_incense_burners =63968
poh_marble_incense_burners =63967
poh_saradomin_symbol =63966
poh_zamorak_symbol =63965
poh_guthix_symbol =63964
poh_saradomin_icon =63963
poh_zamorak_icon =63962
poh_guthix_icon =63961
poh_icon_of_bob =63960
poh_chapel_windchimes =63959
poh_chapel_bells =63958
poh_chapel_organ =63957
poh_small_statue =63956
poh_medium_statue =63955
poh_large_statue =63954
poh_shuttered_window =63953
poh_decorative_window =63952
poh_stained_glass =63951
# Throne room
poh_oak_throne =63950
poh_teak_throne =63949
poh_mahogany_throne =63948
poh_gilded_throne =63947
poh_skeleton_throne =63946
poh_crystal_throne =63945
poh_demonic_throne =63944
poh_oak_lever =63943
poh_teak_lever =63942
poh_mahogany_lever =63941
poh_oak_trapdoor =63940
poh_teak_trapdoor =63939
poh_mahogany_trapdoor =63938
poh_floor_decoration =63937
poh_throne_steel_cage =63936
poh_trapdoor_floor =63935
poh_lesser_magic_cage =63934
poh_greater_magic_cage =63933
poh_throne_carved_teak_bench =63932
poh_throne_carved_teak_bench_2 =63931
poh_throne_mahogany_bench =63930
poh_throne_mahogany_bench_2 =63929
poh_throne_gilded_bench =63928
poh_throne_gilded_bench_2 =63927
poh_round_shield =63926
poh_square_shield =63925
poh_kite_shield =63924
# Games room
poh_lesser_magical_balance =63923
poh_medium_magical_balance =63922
poh_greater_magical_balance =63921
poh_jester =63920
poh_treasure_hunt =63919
poh_hangman =63918
poh_oak_prize_chest =63917
poh_teak_prize_chest =63916
poh_mahogany_prize_chest =63915
poh_hoop_and_stick =63914
poh_dartboard =63913
poh_archery_target =63912
poh_clay_attack_stone =63911
poh_limestone_attack_stone =63910
poh_marble_attack_stone =63909
# Combat room
poh_boxing_ring =63908
poh_fencing_ring =63907
poh_combat_ring =63906
poh_ranging_pedestals =63905
poh_boxing_glove_rack =63904
poh_weapons_rack =63903
poh_extra_weapons_rack =63902
poh_combat_dummy_row =63901
poh_undead_combat_dummy =63900
poh_ornate_undead_combat_dummy =63899
# Portal chamber
poh_teak_portal =63898
poh_mahogany_portal =63897
poh_marble_portal =63896
poh_teleport_focus =63895
poh_greater_teleport_focus =63894
poh_scrying_pool =63893
# Costume room
poh_oak_armour_case =63892
poh_teak_armour_case =63891
poh_mahogany_armour_case =63890
poh_oak_cape_rack =63889
poh_teak_cape_rack =63888
poh_mahogany_cape_rack =63887
poh_gilded_cape_rack =63886
poh_marble_cape_rack =63885
poh_magical_cape_rack =63884
poh_oak_fancy_dress_box =63883
poh_teak_fancy_dress_box =63882
poh_mahogany_fancy_dress_box =63881
poh_oak_magic_wardrobe =63880
poh_carved_oak_magic_wardrobe =63879
poh_teak_magic_wardrobe =63878
poh_carved_teak_magic_wardrobe =63877
poh_mahogany_magic_wardrobe =63876
poh_gilded_magic_wardrobe =63875
poh_marble_magic_wardrobe =63874
poh_oak_toy_box =63873
poh_teak_toy_box =63872
poh_mahogany_toy_box =63871
poh_oak_treasure_chest =63870
poh_teak_treasure_chest =63869
poh_mahogany_treasure_chest =63868
# Menagerie
poh_simple_arena =63867
poh_advanced_arena =63866
poh_glorious_arena =63865
poh_grassland_habitat =63864
poh_forest_habitat =63863
poh_desert_habitat =63862
poh_polar_habitat =63861
poh_volcanic_habitat =63860
poh_oak_feeder =63859
poh_teak_feeder =63858
poh_mahogany_feeder =63857
poh_oak_pet_house =63856
poh_teak_pet_house =63855
poh_mahogany_pet_house =63854
poh_consecrated_pet_house =63853
poh_desecrated_pet_house =63852
poh_nature_pet_house =63851
poh_pet_list =63850
poh_oak_scratching_post =63849
poh_teak_scratching_post =63848
poh_mahogany_scratching_post =63847
# Dungeon (shared)
poh_dungeon_skeleton_guard =63846
poh_dungeon_guard_dog =63845
poh_hobgoblin_guard =63844
poh_baby_red_dragon =63843
poh_huge_spider =63842
poh_troll_guard =63841
poh_hellhound_guard =63840
poh_dungeon_spike_trap =63839
poh_dungeon_man_trap =63838
poh_tangle_vine =63837
poh_dungeon_marble_trap =63836
poh_dungeon_teleport_trap =63835
poh_oak_door =63834
poh_oak_door_2 =63833
poh_steel_plated_door =63832
poh_steel_plated_door_2 =63831
poh_marble_door =63830
poh_marble_door_2 =63829
poh_dungeon_candles =63828
poh_dungeon_torches =63827
poh_dungeon_skull_torches =63826
poh_decorative_blood =63825
poh_decorative_pipe =63824
poh_hanging_skeleton =63823
# Oubliette
poh_oubliette_floor_spikes =63822
poh_tentacle_pool =63821
poh_flame_pit =63820
poh_rocnar =63819
poh_oak_cage =63818
poh_oak_and_steel_cage =63817
poh_oubliette_steel_cage =63816
poh_spiked_cage =63815
poh_bone_cage =63814
poh_oak_ladder =63813
poh_teak_ladder =63812
poh_mahogany_ladder =63811
# Treasure room
poh_wooden_crate =63810
poh_oak_chest =63809
poh_teak_chest =63808
poh_mahogany_chest =63807
poh_magic_chest =63806
poh_treasure_demon =63805
poh_treasure_kalphite_soldier =63804
poh_treasure_tok_xil =63803
poh_treasure_dagannoth =63802
poh_treasure_steel_dragon =63801
poh_treasure_rune_dragon =63800
# Skill hall & Quest hall
poh_hall_rug =63799
poh_hall_opulent_rug =63798
poh_oak_staircase =63797
poh_teak_staircase =63796
poh_limestone_spiral_staircase =63795
poh_marble_staircase =63794
poh_marble_spiral =63793
poh_teak_head_display =63792
poh_mahogany_head_display =63791
poh_gilded_head_display =63790
poh_oak_fish_display =63789
poh_teak_fish_display =63788
poh_mahogany_fish_display =63787
poh_mithril_armour =63786
poh_adamantite_armour =63785
poh_runite_armour =63784
poh_red_castlewars_armour =63783
poh_white_castlewars_armour =63782
poh_gold_castlewars_armour =63781
poh_rune_case_1 =63780
poh_rune_case_2 =63779
poh_rune_case_3 =63778
poh_king_arthur_portrait =63777
poh_elena_portrait =63776
poh_giant_dwarf_portrait =63775
poh_miscellanians_portrait =63774
poh_landscape_lumbridge =63773
poh_landscape_desert =63772
poh_landscape_morytania =63771
poh_landscape_karamja =63770
poh_landscape_isafdar =63769
poh_mounted_anti_dragon_shield =63768
poh_mounted_amulet_of_glory =63767
poh_mounted_cape_of_legends =63766
poh_mounted_mythical_cape =63765
poh_mounted_silverlight =63764
poh_mounted_excalibur =63763
poh_mounted_darklight =63762
poh_small_map =63761
poh_medium_map =63760
poh_large_map =63759
# Garden
poh_exit_portal_build =63758
poh_garden_greenman_statue =63757
poh_decorative_rock =63756
poh_pond =63755
poh_imp_statue =63754
poh_dungeon_entrance =63753
poh_tip_jar =63752
poh_garden_dead_tree =63751
poh_garden_nice_tree =63750
poh_garden_oak_tree =63749
poh_garden_willow_tree =63748
poh_garden_maple_tree =63747
poh_garden_yew_tree =63746
poh_garden_magic_tree =63745
poh_garden_fern =63744
poh_garden_bush =63743
poh_garden_tall_plant =63742
poh_garden_short_plant =63741
poh_garden_large_leaf_bush =63740
poh_garden_huge_plant =63739
poh_garden_plant =63738
poh_garden_small_fern =63737
poh_garden_fern_small =63736
poh_garden_dock_leaf =63735
poh_garden_thistle =63734
poh_garden_reeds =63733
# Formal garden
poh_gazebo =63732
poh_small_fountain =63731
poh_large_fountain =63730
poh_posh_fountain =63729
poh_boundary_stones =63728
poh_wooden_fence =63727
poh_stone_wall =63726
poh_iron_railings =63725
poh_picket_fence =63724
poh_garden_fence =63723
poh_marble_wall =63722
poh_thorny_hedge =63721
poh_nice_hedge =63720
poh_small_box_hedge =63719
poh_topiary_hedge =63718
poh_fancy_hedge =63717
poh_tall_fancy_hedge =63716
poh_tall_box_hedge =63715
poh_sunflower =63714
poh_marigolds =63713
poh_roses =63712
poh_rosemary =63711
poh_daffodils =63710
poh_bluebells =63709
# Superior garden
poh_restoration_pool =63708
poh_revitalisation_pool =63707
poh_rejuvenation_pool =63706
poh_fancy_rejuvenation_pool =63705
poh_ornate_rejuvenation_pool =63704
poh_spirit_tree_teleport =63703
poh_obelisk =63702
poh_fairy_ring_teleport =63701
poh_spiritual_fairy_tree =63700
poh_zen_theme =63699
poh_otherworldly_theme =63698
poh_volcanic_theme =63697
poh_topiary_bush =63696
poh_redwood_fence =63695
poh_superior_marble_wall =63694
poh_obsidian_fence =63693
poh_teak_garden_bench =63692
poh_teak_garden_bench_2 =63691
poh_gnome_bench =63690
poh_gnome_bench_2 =63689
poh_marble_bench =63688
poh_marble_bench_2 =63687
poh_obsidian_bench =63686
poh_obsidian_bench_2 =63685
# Achievement gallery
poh_ancient_altar =63684
poh_lunar_altar =63683
poh_dark_altar =63682
poh_occult_altar =63681
poh_occult_altar_2 =63680
poh_occult_altar_3 =63679
poh_mahogany_adventure_log =63678
poh_gilded_adventure_log =63677
poh_marble_adventure_log =63676
poh_boss_lair_display =63675
poh_mounted_emblem =63674
poh_mounted_coins =63673
poh_cape_hanger =63672
poh_basic_jewellery_box =63671
poh_fancy_jewellery_box =63670
poh_ornate_jewellery_box =63669
poh_quest_list =63668
# Portal nexus
poh_marble_portal_nexus =63667
poh_gilded_portal_nexus =63666
poh_crystalline_portal_nexus =63665
poh_mounted_xerics_talisman =63664
poh_mounted_digsite_pendant =63663