package org.rsmod.content.skills.fletching.pack

import dev.openrune.definition.util.VarType
import dev.openrune.tables.production.productionTable

/**
 * Fletching recipes, sourced from the wiki Recipe bucket.
 *
 * XP is stored multiplied by ten. 46 of these recipes have fractional XP — a magic shortbow is 83.3
 * — and the xp column is an int. This matches CombinationRune, which stores tenths the same way.
 * Content divides by ten once, in FletchingDefinitions.
 *
 * Any feather fletches bolts, darts and headless arrows. Only obj.feather appears here; the other
 * seven feather types are substituted in the content layer rather than duplicated as rows.
 *
 * The `tool` column is held, never consumed, so it is not an input. For cutting and gem tips it is
 * also half the trigger: the tool is used on the first input and the remaining materials are taken
 * from the inventory, which is how the wiki describes the interaction — "the wielder will still
 * need a knife in their inventory to use on logs to initiate the cutting"
 * (https://oldschool.runescape.wiki/w/Fletching_knife) — and matches the vanilla cache's own
 * dbtable.fletching_blowpipe_crafting, which splits its inputs into log_resource and
 * secondary_resource. Stringing and attaching are plain item pairs and declare no tool column at
 * all; assembly pairs stock with limbs and holds a hammer.
 *
 * Recipe accounting: 411 raw wiki rows for uses_skill=Fletching reduce to the 204 below.
 * - 33 need a facility Forestry doesn't implement: 32 Vale-totem offerings, 1 repair bench.
 * - 1 has no output; 1 is an exact duplicate; 154 are coloured-feather duplicates that collapse
 *   into these obj.feather rows (any feather fletches bolts, darts and headless arrows).
 * - 18 are deferred one-offs, each a multi-stage assembly or a boss/quest/Forestry-gated build: the
 *   4-stage ballista chain, 6 Greenman mask variants, mith grapple + (unf), lyre, scorching bow,
 *   webweaver bow (u), bone shortbow.
 * - 9 pair a finished arrow with a Seeking headless arrow (e.g. Adamant arrow x150 + Seeking
 *   headless arrow x150). These are included, not dropped: it's the documented bulk-conversion
 *   route that turns 150 finished arrows into their seeking variant in one action.
 *   https://oldschool.runescape.wiki/w/Seeking_headless_arrow
 */
object FletchingTables {

    const val COL_TICKS = 7
    const val COL_TOOL = 8

    private data class Recipe(
        val row: String,
        val inputs: List<Pair<String, Int>>,
        val output: String,
        val outputAmount: Int,
        val level: Int,
        val xp: Double,
        val ticks: Int,
        val crafting: Int? = null,
        /**
         * Held, never consumed, so it is not one of [inputs]. For the knife and chisel families it
         * is also half the trigger: the tool is used on `inputs[0]` and the rest of the materials
         * come from the inventory. Null for the families that need no tool.
         */
        val tool: String? = null,
    )

    private fun productionRows(tableId: String, category: String, recipes: List<Recipe>) =
        productionTable(
            tableId,
            serverOnly = true,
            defaultCategory = category,
            extraColumns = {
                column("ticks", COL_TICKS, VarType.INT)
                // Declared only where it is used, so the two toolless families don't generate a
                // column that no row of theirs could ever fill.
                if (recipes.any { it.tool != null }) column("tool", COL_TOOL, VarType.OBJ)
            },
        ) {
            recipes.forEach { recipe ->
                row(recipe.row) {
                    production {
                        recipe.inputs.forEach { (item, amount) -> input(item, amount) }
                        statReq("stat.fletching", recipe.level)
                        recipe.crafting?.let { statReq("stat.crafting", it) }
                        xp((recipe.xp * 10).toInt())
                        output(recipe.output, recipe.outputAmount)
                    }
                    column(COL_TICKS, recipe.ticks)
                    recipe.tool?.let { columnRSCM(COL_TOOL, it) }
                }
            }
        }

    /**
     * Cutting and gem tips are single-tool families by construction — a recipe belongs to them
     * *because* the wiki lists a knife or a chisel — so the tool is stated once here rather than
     * repeated on all 76 rows. A row that already names a tool keeps it.
     */
    private fun List<Recipe>.withTool(tool: String) = map { it.copy(tool = it.tool ?: tool) }

    fun cutting() =
        productionRows("dbtable.fletching_cutting", "Cut", CUTTING.withTool("obj.knife"))

    fun stringing() = productionRows("dbtable.fletching_stringing", "String", STRINGING)

    fun attaching() = productionRows("dbtable.fletching_attaching", "Make", ATTACHING)

    fun gemTips() =
        productionRows("dbtable.fletching_gem_tips", "Cut", GEM_TIPS.withTool("obj.chisel"))

    // Assembly is mixed: every crossbow and brutal-arrow row needs a hammer, but attaching
    // wolfbone arrowtips to flighted ogre arrows needs none, so the hammer is stated per row.
    fun assembly() = productionRows("dbtable.fletching_assembly", "Make", ASSEMBLY)

    private val CUTTING =
        listOf(
            Recipe(
                "dbrow.fletching_arrow_shaft_from_logs",
                listOf("obj.logs" to 1),
                "obj.arrow_shaft",
                15,
                level = 1,
                xp = 5.0,
                ticks = 2,
            ),
            // Wiki reports 0 ticks for this row - inherited data, not a defaulted blank - so this
            // knife action plays no animation.
            Recipe(
                "dbrow.fletching_brew_scrapey_bark_from_brew_scrapey_logs",
                listOf("obj.brew_scrapey_logs" to 1),
                "obj.brew_scrapey_bark",
                1,
                level = 1,
                xp = 50.0,
                ticks = 0,
            ),
            Recipe(
                "dbrow.fletching_seeking_arrow_shaft_from_sap_treated_logs",
                listOf("obj.sap_treated_logs" to 1),
                "obj.seeking_arrow_shaft",
                15,
                level = 1,
                xp = 5.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_javelin_shaft_from_logs",
                listOf("obj.logs" to 1),
                "obj.javelin_shaft",
                15,
                level = 3,
                xp = 5.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_ogre_arrow_shaft_from_achey_tree_logs",
                listOf("obj.achey_tree_logs" to 1),
                "obj.ogre_arrow_shaft",
                4,
                level = 5,
                xp = 6.4,
                ticks = 3,
            ),
            Recipe(
                "dbrow.fletching_unstrung_shortbow_from_logs",
                listOf("obj.logs" to 1),
                "obj.unstrung_shortbow",
                1,
                level = 5,
                xp = 5.0,
                ticks = 3,
            ),
            Recipe(
                "dbrow.fletching_xbows_crossbow_stock_wood_from_logs",
                listOf("obj.logs" to 1),
                "obj.xbows_crossbow_stock_wood",
                1,
                level = 9,
                xp = 6.0,
                ticks = 3,
            ),
            Recipe(
                "dbrow.fletching_unstrung_longbow_from_logs",
                listOf("obj.logs" to 1),
                "obj.unstrung_longbow",
                1,
                level = 10,
                xp = 10.0,
                ticks = 3,
            ),
            Recipe(
                "dbrow.fletching_arrow_shaft_from_oak_logs",
                listOf("obj.oak_logs" to 1),
                "obj.arrow_shaft",
                30,
                level = 15,
                xp = 10.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_seeking_arrow_shaft_from_sap_treated_oak_logs",
                listOf("obj.sap_treated_oak_logs" to 1),
                "obj.seeking_arrow_shaft",
                30,
                level = 15,
                xp = 10.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_unstrung_oak_shortbow_from_oak_logs",
                listOf("obj.oak_logs" to 1),
                "obj.unstrung_oak_shortbow",
                1,
                level = 20,
                xp = 16.5,
                ticks = 3,
            ),
            Recipe(
                "dbrow.fletching_xbows_crossbow_stock_oak_from_oak_logs",
                listOf("obj.oak_logs" to 1),
                "obj.xbows_crossbow_stock_oak",
                1,
                level = 24,
                xp = 16.0,
                ticks = 3,
            ),
            Recipe(
                "dbrow.fletching_unstrung_oak_longbow_from_oak_logs",
                listOf("obj.oak_logs" to 1),
                "obj.unstrung_oak_longbow",
                1,
                level = 25,
                xp = 25.0,
                ticks = 3,
            ),
            Recipe(
                "dbrow.fletching_oak_shield_from_oak_logs",
                listOf("obj.oak_logs" to 2),
                "obj.oak_shield",
                1,
                level = 27,
                xp = 50.0,
                ticks = 7,
            ),
            Recipe(
                "dbrow.fletching_arrow_shaft_from_willow_logs",
                listOf("obj.willow_logs" to 1),
                "obj.arrow_shaft",
                45,
                level = 30,
                xp = 15.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_seeking_arrow_shaft_from_sap_treated_willow_logs",
                listOf("obj.sap_treated_willow_logs" to 1),
                "obj.seeking_arrow_shaft",
                45,
                level = 30,
                xp = 15.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_unstrung_willow_shortbow_from_willow_logs",
                listOf("obj.willow_logs" to 1),
                "obj.unstrung_willow_shortbow",
                1,
                level = 35,
                xp = 33.3,
                ticks = 3,
            ),
            Recipe(
                "dbrow.fletching_xbows_crossbow_stock_willow_from_willow_logs",
                listOf("obj.willow_logs" to 1),
                "obj.xbows_crossbow_stock_willow",
                1,
                level = 39,
                xp = 22.0,
                ticks = 3,
            ),
            Recipe(
                "dbrow.fletching_unstrung_willow_longbow_from_willow_logs",
                listOf("obj.willow_logs" to 1),
                "obj.unstrung_willow_longbow",
                1,
                level = 40,
                xp = 41.5,
                ticks = 3,
            ),
            Recipe(
                "dbrow.fletching_willow_shield_from_willow_logs",
                listOf("obj.willow_logs" to 2),
                "obj.willow_shield",
                1,
                level = 42,
                xp = 83.0,
                ticks = 7,
            ),
            Recipe(
                "dbrow.fletching_arrow_shaft_from_maple_logs",
                listOf("obj.maple_logs" to 1),
                "obj.arrow_shaft",
                60,
                level = 45,
                xp = 20.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_seeking_arrow_shaft_from_sap_treated_maple_logs",
                listOf("obj.sap_treated_maple_logs" to 1),
                "obj.seeking_arrow_shaft",
                60,
                level = 45,
                xp = 20.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_xbows_crossbow_stock_teak_from_teak_logs",
                listOf("obj.teak_logs" to 1),
                "obj.xbows_crossbow_stock_teak",
                1,
                level = 46,
                xp = 27.0,
                ticks = 3,
            ),
            Recipe(
                "dbrow.fletching_unstrung_maple_shortbow_from_maple_logs",
                listOf("obj.maple_logs" to 1),
                "obj.unstrung_maple_shortbow",
                1,
                level = 50,
                xp = 50.0,
                ticks = 3,
            ),
            Recipe(
                "dbrow.fletching_xbows_crossbow_stock_maple_from_maple_logs",
                listOf("obj.maple_logs" to 1),
                "obj.xbows_crossbow_stock_maple",
                1,
                level = 54,
                xp = 32.0,
                ticks = 3,
            ),
            Recipe(
                "dbrow.fletching_unstrung_maple_longbow_from_maple_logs",
                listOf("obj.maple_logs" to 1),
                "obj.unstrung_maple_longbow",
                1,
                level = 55,
                xp = 58.3,
                ticks = 3,
            ),
            Recipe(
                "dbrow.fletching_maple_shield_from_maple_logs",
                listOf("obj.maple_logs" to 2),
                "obj.maple_shield",
                1,
                level = 57,
                xp = 116.5,
                ticks = 7,
            ),
            Recipe(
                "dbrow.fletching_arrow_shaft_from_yew_logs",
                listOf("obj.yew_logs" to 1),
                "obj.arrow_shaft",
                75,
                level = 60,
                xp = 25.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_seeking_arrow_shaft_from_sap_treated_yew_logs",
                listOf("obj.sap_treated_yew_logs" to 1),
                "obj.seeking_arrow_shaft",
                75,
                level = 60,
                xp = 25.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_xbows_crossbow_stock_mahogany_from_mahogany_logs",
                listOf("obj.mahogany_logs" to 1),
                "obj.xbows_crossbow_stock_mahogany",
                1,
                level = 61,
                xp = 41.0,
                ticks = 3,
            ),
            Recipe(
                "dbrow.fletching_unstrung_yew_shortbow_from_yew_logs",
                listOf("obj.yew_logs" to 1),
                "obj.unstrung_yew_shortbow",
                1,
                level = 65,
                xp = 67.5,
                ticks = 3,
            ),
            Recipe(
                "dbrow.fletching_xbows_crossbow_stock_yew_from_yew_logs",
                listOf("obj.yew_logs" to 1),
                "obj.xbows_crossbow_stock_yew",
                1,
                level = 69,
                xp = 50.0,
                ticks = 3,
            ),
            Recipe(
                "dbrow.fletching_blisterwood_stake_from_blisterwood_logs",
                listOf("obj.blisterwood_logs" to 1),
                "obj.blisterwood_stake",
                5,
                level = 70,
                xp = 0.0,
                ticks = 3,
            ),
            Recipe(
                "dbrow.fletching_unstrung_yew_longbow_from_yew_logs",
                listOf("obj.yew_logs" to 1),
                "obj.unstrung_yew_longbow",
                1,
                level = 70,
                xp = 75.0,
                ticks = 3,
            ),
            Recipe(
                "dbrow.fletching_yew_shield_from_yew_logs",
                listOf("obj.yew_logs" to 2),
                "obj.yew_shield",
                1,
                level = 72,
                xp = 150.0,
                ticks = 7,
            ),
            Recipe(
                "dbrow.fletching_atlatl_dart_shaft_from_ent_branch",
                listOf("obj.ent_branch" to 1),
                "obj.atlatl_dart_shaft",
                100,
                level = 74,
                xp = 30.0,
                ticks = 3,
            ),
            Recipe(
                "dbrow.fletching_arrow_shaft_from_magic_logs",
                listOf("obj.magic_logs" to 1),
                "obj.arrow_shaft",
                90,
                level = 75,
                xp = 30.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_seeking_arrow_shaft_from_sap_treated_magic_logs",
                listOf("obj.sap_treated_magic_logs" to 1),
                "obj.seeking_arrow_shaft",
                90,
                level = 75,
                xp = 30.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_xbows_crossbow_stock_magic_from_magic_logs",
                listOf("obj.magic_logs" to 1),
                "obj.xbows_crossbow_stock_magic",
                1,
                level = 78,
                xp = 70.0,
                ticks = 3,
            ),
            Recipe(
                "dbrow.fletching_unstrung_magic_shortbow_from_magic_logs",
                listOf("obj.magic_logs" to 1),
                "obj.unstrung_magic_shortbow",
                1,
                level = 80,
                xp = 83.3,
                ticks = 3,
            ),
            Recipe(
                "dbrow.fletching_unstrung_magic_longbow_from_magic_logs",
                listOf("obj.magic_logs" to 1),
                "obj.unstrung_magic_longbow",
                1,
                level = 85,
                xp = 91.5,
                ticks = 3,
            ),
            Recipe(
                "dbrow.fletching_magic_shield_from_magic_logs",
                listOf("obj.magic_logs" to 2),
                "obj.magic_shield",
                1,
                level = 87,
                xp = 183.0,
                ticks = 7,
            ),
            Recipe(
                "dbrow.fletching_arrow_shaft_from_redwood_logs",
                listOf("obj.redwood_logs" to 1),
                "obj.arrow_shaft",
                105,
                level = 90,
                xp = 35.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_redwood_hiking_staff_from_redwood_logs",
                listOf("obj.redwood_logs" to 1),
                "obj.redwood_hiking_staff",
                1,
                level = 90,
                xp = 10.5,
                ticks = 3,
            ),
            Recipe(
                "dbrow.fletching_seeking_arrow_shaft_from_sap_treated_redwood_logs",
                listOf("obj.sap_treated_redwood_logs" to 1),
                "obj.seeking_arrow_shaft",
                105,
                level = 90,
                xp = 35.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_redwood_shield_from_redwood_logs",
                listOf("obj.redwood_logs" to 2),
                "obj.redwood_shield",
                1,
                level = 92,
                xp = 216.0,
                ticks = 7,
            ),
            // Unlocked by the tool column: the knife is used on the log named first, and any
            // further material is taken from the inventory. Battlestaff and Root kindling need no
            // second material and were only ever held back alongside these.
            Recipe(
                "dbrow.fletching_unstrung_zogre_bow_from_achey_tree_logs",
                listOf("obj.achey_tree_logs" to 1, "obj.wolf_bones" to 1),
                "obj.unstrung_zogre_bow",
                1,
                level = 30,
                xp = 45.0,
                ticks = 3,
            ),
            Recipe(
                "dbrow.fletching_battlestaff_from_celastrus_wood",
                listOf("obj.celastrus_wood" to 1),
                "obj.battlestaff",
                1,
                level = 40,
                xp = 80.0,
                ticks = 4,
            ),
            Recipe(
                "dbrow.fletching_vmq4_root_kindling_from_vmq4_roots",
                listOf("obj.vmq4_roots" to 1),
                "obj.vmq4_root_kindling",
                4,
                level = 52,
                xp = 10.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_greenman_statue_from_maple_logs",
                listOf("obj.maple_logs" to 1, "obj.ent_branch" to 5, "obj.greenman_mask" to 1),
                "obj.greenman_statue",
                1,
                level = 53,
                xp = 55.0,
                ticks = 4,
            ),
            Recipe(
                "dbrow.fletching_camphor_blowpipe_empty_from_camphor_logs",
                listOf("obj.camphor_logs" to 2, "obj.squid_beak" to 1),
                "obj.camphor_blowpipe_empty",
                1,
                level = 58,
                xp = 140.0,
                ticks = 3,
            ),
            Recipe(
                "dbrow.fletching_blisterwood_sickle_from_blisterwood_logs",
                listOf("obj.blisterwood_logs" to 1, "obj.silver_sickle_ruby_enchanted" to 1),
                "obj.blisterwood_sickle",
                1,
                level = 60,
                xp = 82.0,
                ticks = 1,
            ),
            Recipe(
                "dbrow.fletching_hg_hunter_spear_from_teak_logs",
                listOf(
                    "obj.teak_logs" to 1,
                    "obj.hg_speartip" to 5,
                    "obj.hunting_jerboa_tail" to 5,
                ),
                "obj.hg_hunter_spear",
                5,
                level = 60,
                xp = 9.5,
                ticks = 3,
            ),
            Recipe(
                "dbrow.fletching_blisterwood_sickle_enhanced_from_blisterwood_logs",
                listOf("obj.blisterwood_logs" to 1, "obj.silver_sickle_diamond_enchanted" to 1),
                "obj.blisterwood_sickle_enhanced",
                1,
                level = 70,
                xp = 94.0,
                ticks = 1,
            ),
            Recipe(
                "dbrow.fletching_ironwood_blowpipe_empty_from_ironwood_logs",
                listOf("obj.ironwood_logs" to 2, "obj.squid_beak" to 1),
                "obj.ironwood_blowpipe_empty",
                1,
                level = 72,
                xp = 170.0,
                ticks = 3,
            ),
            Recipe(
                "dbrow.fletching_greenman_wall_decoration_from_yew_logs",
                listOf("obj.yew_logs" to 1, "obj.ent_branch" to 5, "obj.greenman_mask" to 1),
                "obj.greenman_wall_decoration",
                1,
                level = 79,
                xp = 70.0,
                ticks = 2,
            ), // wiki ticks blank
            Recipe(
                "dbrow.fletching_rosewood_blowpipe_empty_from_rosewood_logs",
                listOf("obj.rosewood_logs" to 2, "obj.squid_beak" to 1),
                "obj.rosewood_blowpipe_empty",
                1,
                level = 84,
                xp = 200.0,
                ticks = 3,
            ),
        )

    private val STRINGING =
        listOf(
            Recipe(
                "dbrow.fletching_shortbow_from_bow_string",
                listOf("obj.bow_string" to 1, "obj.unstrung_shortbow" to 1),
                "obj.shortbow",
                1,
                level = 5,
                xp = 5.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_xbows_crossbow_bronze_from_xbows_crossbow_unstrung_bronze",
                listOf("obj.xbows_crossbow_unstrung_bronze" to 1, "obj.xbows_crossbow_string" to 1),
                "obj.xbows_crossbow_bronze",
                1,
                level = 9,
                xp = 6.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_longbow_from_bow_string",
                listOf("obj.bow_string" to 1, "obj.unstrung_longbow" to 1),
                "obj.longbow",
                1,
                level = 10,
                xp = 10.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_oak_shortbow_from_bow_string",
                listOf("obj.bow_string" to 1, "obj.unstrung_oak_shortbow" to 1),
                "obj.oak_shortbow",
                1,
                level = 20,
                xp = 16.5,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_xbows_crossbow_blurite_from_xbows_crossbow_unstrung_blurite",
                listOf(
                    "obj.xbows_crossbow_unstrung_blurite" to 1,
                    "obj.xbows_crossbow_string" to 1,
                ),
                "obj.xbows_crossbow_blurite",
                1,
                level = 24,
                xp = 16.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_oak_longbow_from_bow_string",
                listOf("obj.bow_string" to 1, "obj.unstrung_oak_longbow" to 1),
                "obj.oak_longbow",
                1,
                level = 25,
                xp = 25.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_zogre_bow_from_bow_string",
                listOf("obj.bow_string" to 1, "obj.unstrung_zogre_bow" to 1),
                "obj.zogre_bow",
                1,
                level = 30,
                xp = 45.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_willow_shortbow_from_bow_string",
                listOf("obj.bow_string" to 1, "obj.unstrung_willow_shortbow" to 1),
                "obj.willow_shortbow",
                1,
                level = 35,
                xp = 33.2,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_xbows_crossbow_iron_from_xbows_crossbow_string",
                listOf("obj.xbows_crossbow_string" to 1, "obj.xbows_crossbow_unstrung_iron" to 1),
                "obj.xbows_crossbow_iron",
                1,
                level = 39,
                xp = 22.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_willow_longbow_from_bow_string",
                listOf("obj.bow_string" to 1, "obj.unstrung_willow_longbow" to 1),
                "obj.willow_longbow",
                1,
                level = 40,
                xp = 41.5,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_xbows_crossbow_steel_from_xbows_crossbow_string",
                listOf("obj.xbows_crossbow_string" to 1, "obj.xbows_crossbow_unstrung_steel" to 1),
                "obj.xbows_crossbow_steel",
                1,
                level = 46,
                xp = 27.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_devious_bowsword_from_bow_string",
                listOf("obj.bow_string" to 1, "obj.devious_slenderblade" to 1),
                "obj.devious_bowsword",
                1,
                level = 50,
                xp = 50.0,
                ticks = 2,
            ), // wiki ticks blank
            Recipe(
                "dbrow.fletching_maple_shortbow_from_bow_string",
                listOf("obj.bow_string" to 1, "obj.unstrung_maple_shortbow" to 1),
                "obj.maple_shortbow",
                1,
                level = 50,
                xp = 50.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_xbows_crossbow_mithril_from_xbows_crossbow_string",
                listOf(
                    "obj.xbows_crossbow_string" to 1,
                    "obj.xbows_crossbow_unstrung_mithril" to 1,
                ),
                "obj.xbows_crossbow_mithril",
                1,
                level = 54,
                xp = 32.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_maple_longbow_from_bow_string",
                listOf("obj.bow_string" to 1, "obj.unstrung_maple_longbow" to 1),
                "obj.maple_longbow",
                1,
                level = 55,
                xp = 58.2,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_xbows_crossbow_adamantite_from_xbows_crossbow_unstrung_adamantite",
                listOf(
                    "obj.xbows_crossbow_unstrung_adamantite" to 1,
                    "obj.xbows_crossbow_string" to 1,
                ),
                "obj.xbows_crossbow_adamantite",
                1,
                level = 61,
                xp = 41.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_yew_shortbow_from_bow_string",
                listOf("obj.bow_string" to 1, "obj.unstrung_yew_shortbow" to 1),
                "obj.yew_shortbow",
                1,
                level = 65,
                xp = 67.5,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_xbows_crossbow_runite_from_xbows_crossbow_string",
                listOf("obj.xbows_crossbow_string" to 1, "obj.xbows_crossbow_unstrung_runite" to 1),
                "obj.xbows_crossbow_runite",
                1,
                level = 69,
                xp = 50.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_yew_longbow_from_bow_string",
                listOf("obj.bow_string" to 1, "obj.unstrung_yew_longbow" to 1),
                "obj.yew_longbow",
                1,
                level = 70,
                xp = 75.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_xbows_crossbow_dragon_from_xbows_crossbow_string",
                listOf("obj.xbows_crossbow_string" to 1, "obj.xbows_crossbow_unstrung_dragon" to 1),
                "obj.xbows_crossbow_dragon",
                1,
                level = 78,
                xp = 70.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_magic_shortbow_from_bow_string",
                listOf("obj.bow_string" to 1, "obj.unstrung_magic_shortbow" to 1),
                "obj.magic_shortbow",
                1,
                level = 80,
                xp = 83.3,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_magic_longbow_from_bow_string",
                listOf("obj.bow_string" to 1, "obj.unstrung_magic_longbow" to 1),
                "obj.magic_longbow",
                1,
                level = 85,
                xp = 91.5,
                ticks = 2,
            ),
        )

    private val ATTACHING =
        listOf(
            Recipe(
                "dbrow.fletching_bronze_arrow_from_bronze_arrowheads",
                listOf("obj.bronze_arrowheads" to 15, "obj.headless_arrow" to 15),
                "obj.bronze_arrow",
                15,
                level = 1,
                xp = 19.5,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_headless_arrow_from_arrow_shaft",
                listOf("obj.arrow_shaft" to 15, "obj.feather" to 15),
                "obj.headless_arrow",
                15,
                level = 1,
                xp = 15.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_seeking_adamant_arrow_from_adamant_arrow",
                listOf("obj.adamant_arrow" to 15, "obj.bucket_of_bloodwood_sap" to 1),
                "obj.seeking_adamant_arrow",
                15,
                level = 1,
                xp = 0.0,
                ticks = 1,
            ),
            Recipe(
                "dbrow.fletching_seeking_amethyst_arrow_from_amethyst_arrow",
                listOf("obj.amethyst_arrow" to 15, "obj.bucket_of_bloodwood_sap" to 1),
                "obj.seeking_amethyst_arrow",
                15,
                level = 1,
                xp = 0.0,
                ticks = 1,
            ),
            // Broad arrows/bolts below need an unlocked Slayer reward; that gate does not exist
            // in the codebase yet, so only the stat.fletching level check is enforced.
            Recipe(
                "dbrow.fletching_seeking_slayer_broad_arrows_from_slayer_broad_arrows",
                listOf("obj.slayer_broad_arrows" to 15, "obj.bucket_of_bloodwood_sap" to 1),
                "obj.seeking_slayer_broad_arrows",
                15,
                level = 1,
                xp = 0.0,
                ticks = 1,
            ),
            Recipe(
                "dbrow.fletching_seeking_bronze_arrow_from_bronze_arrowheads",
                listOf("obj.bronze_arrowheads" to 15, "obj.seeking_headless_arrow" to 15),
                "obj.seeking_bronze_arrow",
                15,
                level = 1,
                xp = 19.5,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_seeking_bronze_arrow_from_bronze_arrow",
                listOf("obj.bronze_arrow" to 15, "obj.bucket_of_bloodwood_sap" to 1),
                "obj.seeking_bronze_arrow",
                15,
                level = 1,
                xp = 0.0,
                ticks = 1,
            ),
            Recipe(
                "dbrow.fletching_seeking_dragon_arrow_from_bucket_of_bloodwood_sap",
                listOf("obj.bucket_of_bloodwood_sap" to 1, "obj.dragon_arrow" to 15),
                "obj.seeking_dragon_arrow",
                15,
                level = 1,
                xp = 0.0,
                ticks = 1,
            ),
            Recipe(
                "dbrow.fletching_seeking_headless_arrow_from_feather",
                listOf("obj.feather" to 15, "obj.seeking_arrow_shaft" to 15),
                "obj.seeking_headless_arrow",
                15,
                level = 1,
                xp = 15.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_seeking_iron_arrow_from_bucket_of_bloodwood_sap",
                listOf("obj.bucket_of_bloodwood_sap" to 1, "obj.iron_arrow" to 15),
                "obj.seeking_iron_arrow",
                15,
                level = 1,
                xp = 0.0,
                ticks = 1,
            ),
            Recipe(
                "dbrow.fletching_seeking_mithril_arrow_from_bucket_of_bloodwood_sap",
                listOf("obj.bucket_of_bloodwood_sap" to 1, "obj.mithril_arrow" to 15),
                "obj.seeking_mithril_arrow",
                15,
                level = 1,
                xp = 0.0,
                ticks = 1,
            ),
            Recipe(
                "dbrow.fletching_seeking_rune_arrow_from_bucket_of_bloodwood_sap",
                listOf("obj.bucket_of_bloodwood_sap" to 1, "obj.rune_arrow" to 15),
                "obj.seeking_rune_arrow",
                15,
                level = 1,
                xp = 0.0,
                ticks = 1,
            ),
            Recipe(
                "dbrow.fletching_seeking_steel_arrow_from_bucket_of_bloodwood_sap",
                listOf("obj.bucket_of_bloodwood_sap" to 1, "obj.steel_arrow" to 15),
                "obj.seeking_steel_arrow",
                15,
                level = 1,
                xp = 0.0,
                ticks = 1,
            ),
            Recipe(
                "dbrow.fletching_bronze_javelin_from_bronze_javelin_head",
                listOf("obj.bronze_javelin_head" to 15, "obj.javelin_shaft" to 15),
                "obj.bronze_javelin",
                15,
                level = 3,
                xp = 15.0,
                ticks = 1,
            ),
            Recipe(
                "dbrow.fletching_ogre_headless_arrow_from_feather",
                listOf("obj.feather" to 24, "obj.ogre_arrow_shaft" to 6),
                "obj.ogre_headless_arrow",
                6,
                level = 5,
                xp = 5.4,
                ticks = 2,
            ),
            // The wiki Recipe bucket lists ticks=0 for the ten feather + bolts(unf) -> bolts
            // rows in this family, but its own mechanics page disagrees: "Fletching arrows (all
            // steps) or feathering bolts: 2 ticks per set of 15 arrows/10 bolts" -
            // https://oldschool.runescape.wiki/w/Game_tick/Action_lengths. Corrected to 2 below;
            // the dart rows here are unaffected and correctly stay at 0 (up to 10 dart sets can
            // queue per tick, which is why darts are the fastest fletching xp in the game).
            Recipe(
                "dbrow.fletching_bolt_from_xbows_crossbow_bolts_bronze_unfeathered",
                listOf("obj.xbows_crossbow_bolts_bronze_unfeathered" to 10, "obj.feather" to 10),
                "obj.bolt",
                10,
                level = 9,
                xp = 5.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_bronze_dart_from_bronze_dart_tip",
                listOf("obj.bronze_dart_tip" to 10, "obj.feather" to 10),
                "obj.bronze_dart",
                10,
                level = 10,
                xp = 18.0,
                ticks = 0,
            ),
            Recipe(
                "dbrow.fletching_thprotodart_from_feather",
                listOf("obj.feather" to 10, "obj.thprotodarttip" to 1),
                "obj.thprotodart",
                1,
                level = 10,
                xp = 10.0,
                ticks = 2,
            ), // wiki ticks blank
            Recipe(
                "dbrow.fletching_opal_bolt_from_bolt",
                listOf("obj.bolt" to 10, "obj.opal_bolttips" to 10),
                "obj.opal_bolt",
                10,
                level = 11,
                xp = 16.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_iron_arrow_from_headless_arrow",
                listOf("obj.headless_arrow" to 15, "obj.iron_arrowheads" to 15),
                "obj.iron_arrow",
                15,
                level = 15,
                xp = 37.5,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_seeking_iron_arrow_from_iron_arrowheads",
                listOf("obj.iron_arrowheads" to 15, "obj.seeking_headless_arrow" to 15),
                "obj.seeking_iron_arrow",
                15,
                level = 15,
                xp = 37.5,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_seeking_steel_arrow_from_seeking_headless_arrow",
                listOf("obj.seeking_headless_arrow" to 15, "obj.steel_arrowheads" to 15),
                "obj.seeking_steel_arrow",
                15,
                level = 15,
                xp = 37.5,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_iron_javelin_from_iron_javelin_head",
                listOf("obj.iron_javelin_head" to 15, "obj.javelin_shaft" to 15),
                "obj.iron_javelin",
                15,
                level = 17,
                xp = 30.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_iron_dart_from_feather",
                listOf("obj.feather" to 10, "obj.iron_dart_tip" to 10),
                "obj.iron_dart",
                10,
                level = 22,
                xp = 38.0,
                ticks = 0,
            ),
            Recipe(
                "dbrow.fletching_xbows_crossbow_bolts_blurite_from_xbows_crossbow_bolts_blurite_unfeathered",
                listOf("obj.xbows_crossbow_bolts_blurite_unfeathered" to 10, "obj.feather" to 10),
                "obj.xbows_crossbow_bolts_blurite",
                10,
                level = 24,
                xp = 10.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_xbows_crossbow_bolts_blurite_tipped_jade_from_xbows_crossbow_bolts_blurite",
                listOf("obj.xbows_crossbow_bolts_blurite" to 10, "obj.xbows_bolt_tips_jade" to 10),
                "obj.xbows_crossbow_bolts_blurite_tipped_jade",
                10,
                level = 26,
                xp = 24.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_steel_arrow_from_headless_arrow",
                listOf("obj.headless_arrow" to 15, "obj.steel_arrowheads" to 15),
                "obj.steel_arrow",
                15,
                level = 30,
                xp = 75.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_steel_javelin_from_javelin_shaft",
                listOf("obj.javelin_shaft" to 15, "obj.steel_javelin_head" to 15),
                "obj.steel_javelin",
                15,
                level = 32,
                xp = 75.0,
                ticks = 1,
            ),
            Recipe(
                "dbrow.fletching_steel_dart_from_feather",
                listOf("obj.feather" to 10, "obj.steel_dart_tip" to 10),
                "obj.steel_dart",
                10,
                level = 37,
                xp = 75.0,
                ticks = 0,
            ),
            Recipe(
                "dbrow.fletching_xbows_crossbow_bolts_iron_from_feather",
                listOf("obj.feather" to 10, "obj.xbows_crossbow_bolts_iron_unfeathered" to 10),
                "obj.xbows_crossbow_bolts_iron",
                10,
                level = 39,
                xp = 15.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_pearl_bolt_from_xbows_crossbow_bolts_iron",
                listOf("obj.xbows_crossbow_bolts_iron" to 10, "obj.pearl_bolttips" to 10),
                "obj.pearl_bolt",
                10,
                level = 41,
                xp = 32.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_xbows_crossbow_bolts_silver_from_feather",
                listOf("obj.feather" to 10, "obj.xbows_crossbow_bolts_silver_unfeathered" to 10),
                "obj.xbows_crossbow_bolts_silver",
                10,
                level = 43,
                xp = 25.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_mithril_arrow_from_headless_arrow",
                listOf("obj.headless_arrow" to 15, "obj.mithril_arrowheads" to 15),
                "obj.mithril_arrow",
                15,
                level = 45,
                xp = 112.5,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_seeking_mithril_arrow_from_mithril_arrowheads",
                listOf("obj.mithril_arrowheads" to 15, "obj.seeking_headless_arrow" to 15),
                "obj.seeking_mithril_arrow",
                15,
                level = 45,
                xp = 112.5,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_xbows_crossbow_bolts_steel_from_feather",
                listOf("obj.feather" to 10, "obj.xbows_crossbow_bolts_steel_unfeathered" to 10),
                "obj.xbows_crossbow_bolts_steel",
                10,
                level = 46,
                xp = 35.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_mithril_javelin_from_javelin_shaft",
                listOf("obj.javelin_shaft" to 15, "obj.mithril_javelin_head" to 15),
                "obj.mithril_javelin",
                15,
                level = 47,
                xp = 120.0,
                ticks = 1,
            ),
            Recipe(
                "dbrow.fletching_xbows_crossbow_bolts_steel_tipped_redtopaz_from_xbows_crossbow_bolts_steel",
                listOf(
                    "obj.xbows_crossbow_bolts_steel" to 10,
                    "obj.xbows_bolt_tips_redtopaz" to 10,
                ),
                "obj.xbows_crossbow_bolts_steel_tipped_redtopaz",
                10,
                level = 48,
                xp = 39.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_barbed_bolt_from_barbed_bolttips",
                listOf("obj.barbed_bolttips" to 10, "obj.bolt" to 10),
                "obj.barbed_bolt",
                10,
                level = 51,
                xp = 95.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_slayer_broad_arrows_from_slayer_broad_arrowhead",
                listOf("obj.slayer_broad_arrowhead" to 15, "obj.headless_arrow" to 15),
                "obj.slayer_broad_arrows",
                15,
                level = 52,
                xp = 150.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_mithril_dart_from_feather",
                listOf("obj.feather" to 10, "obj.mithril_dart_tip" to 10),
                "obj.mithril_dart",
                10,
                level = 52,
                xp = 112.0,
                ticks = 0,
            ),
            Recipe(
                "dbrow.fletching_seeking_slayer_broad_arrows_from_slayer_broad_arrowhead",
                listOf("obj.slayer_broad_arrowhead" to 15, "obj.seeking_headless_arrow" to 15),
                "obj.seeking_slayer_broad_arrows",
                15,
                level = 52,
                xp = 150.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_xbows_crossbow_bolts_mithril_from_feather",
                listOf("obj.feather" to 10, "obj.xbows_crossbow_bolts_mithril_unfeathered" to 10),
                "obj.xbows_crossbow_bolts_mithril",
                10,
                level = 54,
                xp = 50.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_slayer_broad_bolt_from_feather",
                listOf("obj.feather" to 10, "obj.slayer_broad_bolt_unfinished" to 10),
                "obj.slayer_broad_bolt",
                10,
                level = 55,
                xp = 30.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_xbows_crossbow_bolts_mithril_tipped_sapphire_from_xbows_crossbow_bolts_mithril",
                listOf(
                    "obj.xbows_crossbow_bolts_mithril" to 10,
                    "obj.xbows_bolt_tips_sapphire" to 10,
                ),
                "obj.xbows_crossbow_bolts_mithril_tipped_sapphire",
                10,
                level = 56,
                xp = 47.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_xbows_crossbow_bolts_mithril_tipped_emerald_from_xbows_bolt_tips_emerald",
                listOf(
                    "obj.xbows_bolt_tips_emerald" to 10,
                    "obj.xbows_crossbow_bolts_mithril" to 10,
                ),
                "obj.xbows_crossbow_bolts_mithril_tipped_emerald",
                10,
                level = 58,
                xp = 55.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_adamant_arrow_from_adamant_arrowheads",
                listOf("obj.adamant_arrowheads" to 15, "obj.headless_arrow" to 15),
                "obj.adamant_arrow",
                15,
                level = 60,
                xp = 150.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_seeking_adamant_arrow_from_adamant_arrowheads",
                listOf("obj.adamant_arrowheads" to 15, "obj.seeking_headless_arrow" to 15),
                "obj.seeking_adamant_arrow",
                15,
                level = 60,
                xp = 150.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_xbows_crossbow_bolts_adamantite_from_xbows_crossbow_bolts_adamantite_unfeathered",
                listOf(
                    "obj.xbows_crossbow_bolts_adamantite_unfeathered" to 10,
                    "obj.feather" to 10,
                ),
                "obj.xbows_crossbow_bolts_adamantite",
                10,
                level = 61,
                xp = 70.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_adamant_javelin_from_adamant_javelin_head",
                listOf("obj.adamant_javelin_head" to 15, "obj.javelin_shaft" to 15),
                "obj.adamant_javelin",
                15,
                level = 62,
                xp = 150.0,
                ticks = 1,
            ),
            Recipe(
                "dbrow.fletching_xbows_crossbow_bolts_adamantite_tipped_ruby_from_xbows_crossbow_bolts_adamantite",
                listOf(
                    "obj.xbows_crossbow_bolts_adamantite" to 10,
                    "obj.xbows_bolt_tips_ruby" to 10,
                ),
                "obj.xbows_crossbow_bolts_adamantite_tipped_ruby",
                10,
                level = 63,
                xp = 63.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_xbows_crossbow_bolts_adamantite_tipped_diamond_from_xbows_crossbow_bolts_adamantite",
                listOf(
                    "obj.xbows_crossbow_bolts_adamantite" to 10,
                    "obj.xbows_bolt_tips_diamond" to 10,
                ),
                "obj.xbows_crossbow_bolts_adamantite_tipped_diamond",
                10,
                level = 65,
                xp = 70.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_adamant_dart_from_adamant_dart_tip",
                listOf("obj.adamant_dart_tip" to 10, "obj.feather" to 10),
                "obj.adamant_dart",
                10,
                level = 67,
                xp = 150.0,
                ticks = 0,
            ),
            Recipe(
                "dbrow.fletching_xbows_crossbow_bolts_runite_from_feather",
                listOf("obj.feather" to 10, "obj.xbows_crossbow_bolts_runite_unfeathered" to 10),
                "obj.xbows_crossbow_bolts_runite",
                10,
                level = 69,
                xp = 100.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_xbows_crossbow_bolts_runite_tipped_dragonstone_from_xbows_bolt_tips_dragonstone",
                listOf(
                    "obj.xbows_bolt_tips_dragonstone" to 10,
                    "obj.xbows_crossbow_bolts_runite" to 10,
                ),
                "obj.xbows_crossbow_bolts_runite_tipped_dragonstone",
                10,
                level = 71,
                xp = 82.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_xbows_crossbow_bolts_runite_tipped_onyx_from_xbows_bolt_tips_onyx",
                listOf("obj.xbows_bolt_tips_onyx" to 10, "obj.xbows_crossbow_bolts_runite" to 10),
                "obj.xbows_crossbow_bolts_runite_tipped_onyx",
                10,
                level = 73,
                xp = 94.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_atlatl_dart_from_atlatl_dart_tips",
                listOf("obj.atlatl_dart_tips" to 20, "obj.headless_atlatl_dart" to 20),
                "obj.atlatl_dart",
                20,
                level = 74,
                xp = 30.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_headless_atlatl_dart_from_atlatl_dart_shaft",
                listOf("obj.atlatl_dart_shaft" to 20, "obj.feather" to 20),
                "obj.headless_atlatl_dart",
                20,
                level = 74,
                xp = 20.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_rune_arrow_from_headless_arrow",
                listOf("obj.headless_arrow" to 15, "obj.rune_arrowheads" to 15),
                "obj.rune_arrow",
                15,
                level = 75,
                xp = 187.5,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_seeking_rune_arrow_from_rune_arrowheads",
                listOf("obj.rune_arrowheads" to 15, "obj.seeking_headless_arrow" to 15),
                "obj.seeking_rune_arrow",
                15,
                level = 75,
                xp = 187.5,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_slayer_broad_bolt_amethyst_from_xbows_bolt_tips_amethyst",
                listOf("obj.xbows_bolt_tips_amethyst" to 10, "obj.slayer_broad_bolt" to 10),
                "obj.slayer_broad_bolt_amethyst",
                10,
                level = 76,
                xp = 106.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_rune_javelin_from_javelin_shaft",
                listOf("obj.javelin_shaft" to 15, "obj.rune_javelin_head" to 15),
                "obj.rune_javelin",
                15,
                level = 77,
                xp = 187.5,
                ticks = 1,
            ),
            Recipe(
                "dbrow.fletching_rune_dart_from_feather",
                listOf("obj.feather" to 10, "obj.rune_dart_tip" to 10),
                "obj.rune_dart",
                10,
                level = 81,
                xp = 188.0,
                ticks = 0,
            ),
            Recipe(
                "dbrow.fletching_amethyst_arrow_from_amethyst_arrowheads",
                listOf("obj.amethyst_arrowheads" to 15, "obj.headless_arrow" to 15),
                "obj.amethyst_arrow",
                15,
                level = 82,
                xp = 202.5,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_seeking_amethyst_arrow_from_amethyst_arrowheads",
                listOf("obj.amethyst_arrowheads" to 15, "obj.seeking_headless_arrow" to 15),
                "obj.seeking_amethyst_arrow",
                15,
                level = 82,
                xp = 202.5,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_amethyst_javelin_from_amethyst_javelin_head",
                listOf("obj.amethyst_javelin_head" to 15, "obj.javelin_shaft" to 15),
                "obj.amethyst_javelin",
                15,
                level = 84,
                xp = 202.5,
                ticks = 1,
            ),
            Recipe(
                "dbrow.fletching_dragon_bolts_unenchanted_diamond_from_xbows_bolt_tips_diamond",
                listOf("obj.xbows_bolt_tips_diamond" to 10, "obj.dragon_bolts" to 10),
                "obj.dragon_bolts_unenchanted_diamond",
                10,
                level = 84,
                xp = 70.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_dragon_bolts_from_dragon_bolts_unfeathered",
                listOf("obj.dragon_bolts_unfeathered" to 10, "obj.feather" to 10),
                "obj.dragon_bolts",
                10,
                level = 84,
                xp = 120.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_dragon_bolts_unenchanted_dragonstone_from_dragon_bolts",
                listOf("obj.dragon_bolts" to 10, "obj.xbows_bolt_tips_dragonstone" to 10),
                "obj.dragon_bolts_unenchanted_dragonstone",
                10,
                level = 84,
                xp = 82.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_dragon_bolts_unenchanted_emerald_from_dragon_bolts",
                listOf("obj.dragon_bolts" to 10, "obj.xbows_bolt_tips_emerald" to 10),
                "obj.dragon_bolts_unenchanted_emerald",
                10,
                level = 84,
                xp = 55.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_dragon_bolts_unenchanted_jade_from_dragon_bolts",
                listOf("obj.dragon_bolts" to 10, "obj.xbows_bolt_tips_jade" to 10),
                "obj.dragon_bolts_unenchanted_jade",
                10,
                level = 84,
                xp = 24.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_dragon_bolts_unenchanted_onyx_from_dragon_bolts",
                listOf("obj.dragon_bolts" to 10, "obj.xbows_bolt_tips_onyx" to 10),
                "obj.dragon_bolts_unenchanted_onyx",
                10,
                level = 84,
                xp = 94.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_dragon_bolts_unenchanted_opal_from_dragon_bolts",
                listOf("obj.dragon_bolts" to 10, "obj.opal_bolttips" to 10),
                "obj.dragon_bolts_unenchanted_opal",
                10,
                level = 84,
                xp = 16.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_dragon_bolts_unenchanted_pearl_from_dragon_bolts",
                listOf("obj.dragon_bolts" to 10, "obj.pearl_bolttips" to 10),
                "obj.dragon_bolts_unenchanted_pearl",
                10,
                level = 84,
                xp = 32.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_dragon_bolts_unenchanted_ruby_from_dragon_bolts",
                listOf("obj.dragon_bolts" to 10, "obj.xbows_bolt_tips_ruby" to 10),
                "obj.dragon_bolts_unenchanted_ruby",
                10,
                level = 84,
                xp = 63.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_dragon_bolts_unenchanted_sapphire_from_dragon_bolts",
                listOf("obj.dragon_bolts" to 10, "obj.xbows_bolt_tips_sapphire" to 10),
                "obj.dragon_bolts_unenchanted_sapphire",
                10,
                level = 84,
                xp = 47.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_dragon_bolts_unenchanted_topaz_from_dragon_bolts",
                listOf("obj.dragon_bolts" to 10, "obj.xbows_bolt_tips_redtopaz" to 10),
                "obj.dragon_bolts_unenchanted_topaz",
                10,
                level = 84,
                xp = 39.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_amethyst_dart_from_amethyst_dart_tip",
                listOf("obj.amethyst_dart_tip" to 10, "obj.feather" to 10),
                "obj.amethyst_dart",
                10,
                level = 90,
                xp = 210.0,
                ticks = 0,
            ),
            Recipe(
                "dbrow.fletching_dragon_arrow_from_dragon_arrowheads",
                listOf("obj.dragon_arrowheads" to 15, "obj.headless_arrow" to 15),
                "obj.dragon_arrow",
                15,
                level = 90,
                xp = 225.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_seeking_dragon_arrow_from_dragon_arrowheads",
                listOf("obj.dragon_arrowheads" to 15, "obj.seeking_headless_arrow" to 15),
                "obj.seeking_dragon_arrow",
                15,
                level = 90,
                xp = 225.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_dragon_javelin_from_dragon_javelin_head",
                listOf("obj.dragon_javelin_head" to 15, "obj.javelin_shaft" to 15),
                "obj.dragon_javelin",
                15,
                level = 92,
                xp = 225.0,
                ticks = 1,
            ),
            Recipe(
                "dbrow.fletching_dragon_dart_from_dragon_dart_tip",
                listOf("obj.dragon_dart_tip" to 10, "obj.feather" to 10),
                "obj.dragon_dart",
                10,
                level = 95,
                xp = 250.0,
                ticks = 0,
            ),
            // Seeking headless arrows also bulk-convert already-finished arrows to their seeking
            // variant, in sets of 150 - a documented mechanic, not a data error:
            // https://oldschool.runescape.wiki/w/Seeking_headless_arrow
            Recipe(
                "dbrow.fletching_seeking_adamant_arrow_from_adamant_arrow_x150",
                listOf("obj.adamant_arrow" to 150, "obj.seeking_headless_arrow" to 150),
                "obj.seeking_adamant_arrow",
                150,
                level = 1,
                xp = 0.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_seeking_amethyst_arrow_from_amethyst_arrow_x150",
                listOf("obj.amethyst_arrow" to 150, "obj.seeking_headless_arrow" to 150),
                "obj.seeking_amethyst_arrow",
                150,
                level = 1,
                xp = 0.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_seeking_slayer_broad_arrows_from_slayer_broad_arrows_x150",
                listOf("obj.slayer_broad_arrows" to 150, "obj.seeking_headless_arrow" to 150),
                "obj.seeking_slayer_broad_arrows",
                150,
                level = 1,
                xp = 0.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_seeking_bronze_arrow_from_bronze_arrow_x150",
                listOf("obj.bronze_arrow" to 150, "obj.seeking_headless_arrow" to 150),
                "obj.seeking_bronze_arrow",
                150,
                level = 1,
                xp = 0.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_seeking_dragon_arrow_from_dragon_arrow_x150",
                listOf("obj.dragon_arrow" to 150, "obj.seeking_headless_arrow" to 150),
                "obj.seeking_dragon_arrow",
                150,
                level = 1,
                xp = 0.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_seeking_iron_arrow_from_iron_arrow_x150",
                listOf("obj.iron_arrow" to 150, "obj.seeking_headless_arrow" to 150),
                "obj.seeking_iron_arrow",
                150,
                level = 1,
                xp = 0.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_seeking_mithril_arrow_from_mithril_arrow_x150",
                listOf("obj.mithril_arrow" to 150, "obj.seeking_headless_arrow" to 150),
                "obj.seeking_mithril_arrow",
                150,
                level = 1,
                xp = 0.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_seeking_rune_arrow_from_rune_arrow_x150",
                listOf("obj.rune_arrow" to 150, "obj.seeking_headless_arrow" to 150),
                "obj.seeking_rune_arrow",
                150,
                level = 1,
                xp = 0.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_seeking_steel_arrow_from_steel_arrow_x150",
                listOf("obj.steel_arrow" to 150, "obj.seeking_headless_arrow" to 150),
                "obj.seeking_steel_arrow",
                150,
                level = 1,
                xp = 0.0,
                ticks = 2,
            ),
        )

    private val GEM_TIPS =
        listOf(
            Recipe(
                "dbrow.fletching_wolfbone_arrowheads_from_wolf_bones",
                listOf("obj.wolf_bones" to 1),
                "obj.wolfbone_arrowheads",
                4,
                level = 5,
                xp = 10.0,
                ticks = 2,
                crafting = 1,
            ),
            Recipe(
                "dbrow.fletching_opal_bolttips_from_opal",
                listOf("obj.opal" to 1),
                "obj.opal_bolttips",
                12,
                level = 11,
                xp = 1.5,
                ticks = 5,
            ),
            Recipe(
                "dbrow.fletching_xbows_bolt_tips_jade_from_jade",
                listOf("obj.jade" to 1),
                "obj.xbows_bolt_tips_jade",
                12,
                level = 26,
                xp = 2.0,
                ticks = 5,
            ),
            Recipe(
                "dbrow.fletching_huntingbow_bolts_from_huntingbeast_spike",
                listOf("obj.huntingbeast_spike" to 1),
                "obj.huntingbow_bolts",
                12,
                level = 32,
                xp = 5.8,
                ticks = 3,
            ),
            Recipe(
                "dbrow.fletching_pearl_bolttips_from_smalloysterpearls",
                listOf("obj.smalloysterpearls" to 1),
                "obj.pearl_bolttips",
                6,
                level = 41,
                xp = 3.2,
                ticks = 5,
            ),
            Recipe(
                "dbrow.fletching_pearl_bolttips_from_bigoysterpearls",
                listOf("obj.bigoysterpearls" to 1),
                "obj.pearl_bolttips",
                24,
                level = 41,
                xp = 3.2,
                ticks = 5,
            ),
            Recipe(
                "dbrow.fletching_huntingbow_bigbolts_from_huntingbeast_bigspike",
                listOf("obj.huntingbeast_bigspike" to 1),
                "obj.huntingbow_bigbolts",
                12,
                level = 42,
                xp = 7.9,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_xbows_bolt_tips_redtopaz_from_red_topaz",
                listOf("obj.red_topaz" to 1),
                "obj.xbows_bolt_tips_redtopaz",
                12,
                level = 48,
                xp = 3.9,
                ticks = 5,
            ),
            Recipe(
                "dbrow.fletching_xbows_bolt_tips_sapphire_from_sapphire",
                listOf("obj.sapphire" to 1),
                "obj.xbows_bolt_tips_sapphire",
                12,
                level = 56,
                xp = 4.0,
                ticks = 5,
            ),
            Recipe(
                "dbrow.fletching_xbows_bolt_tips_emerald_from_emerald",
                listOf("obj.emerald" to 1),
                "obj.xbows_bolt_tips_emerald",
                12,
                level = 58,
                xp = 5.5,
                ticks = 5,
            ),
            Recipe(
                "dbrow.fletching_sunlight_antelope_bolt_from_hunting_antelopesun_horn",
                listOf("obj.hunting_antelopesun_horn" to 1),
                "obj.sunlight_antelope_bolt",
                12,
                level = 62,
                xp = 10.0,
                ticks = 3,
            ),
            Recipe(
                "dbrow.fletching_xbows_bolt_tips_ruby_from_ruby",
                listOf("obj.ruby" to 1),
                "obj.xbows_bolt_tips_ruby",
                12,
                level = 63,
                xp = 6.3,
                ticks = 5,
            ),
            Recipe(
                "dbrow.fletching_xbows_bolt_tips_diamond_from_diamond",
                listOf("obj.diamond" to 1),
                "obj.xbows_bolt_tips_diamond",
                12,
                level = 65,
                xp = 7.0,
                ticks = 5,
            ),
            Recipe(
                "dbrow.fletching_xbows_bolt_tips_dragonstone_from_dragonstone",
                listOf("obj.dragonstone" to 1),
                "obj.xbows_bolt_tips_dragonstone",
                12,
                level = 71,
                xp = 8.2,
                ticks = 5,
            ),
            Recipe(
                "dbrow.fletching_moonlight_antelope_bolt_from_hunting_antelopemoon_horn",
                listOf("obj.hunting_antelopemoon_horn" to 1),
                "obj.moonlight_antelope_bolt",
                12,
                level = 72,
                xp = 12.1,
                ticks = 3,
            ),
            Recipe(
                "dbrow.fletching_xbows_bolt_tips_onyx_from_onyx",
                listOf("obj.onyx" to 1),
                "obj.xbows_bolt_tips_onyx",
                24,
                level = 73,
                xp = 9.4,
                ticks = 5,
            ),
            Recipe(
                "dbrow.fletching_atlatl_dart_tips_from_custodian_broken_antler",
                listOf("obj.custodian_broken_antler" to 1),
                "obj.atlatl_dart_tips",
                100,
                level = 74,
                xp = 10.0,
                ticks = 4,
            ),
            // Wiki reports 0 ticks for this row - inherited data, not a defaulted blank - so this
            // chisel action plays no animation.
            Recipe(
                "dbrow.fletching_toxic_blowpipe_from_blowpipe_fang",
                listOf("obj.blowpipe_fang" to 1),
                "obj.toxic_blowpipe",
                1,
                level = 78,
                xp = 120.0,
                ticks = 0,
            ),
            // Chiselling the antler with a Hunters' crossbow held upgrades the crossbow, so this
            // shares its trigger - and its make-X menu - with the antler's bolt-tip row above.
            Recipe(
                "dbrow.fletching_hunting_crossbow_sunlight_from_hunting_antelopesun_horn",
                listOf("obj.hunting_antelopesun_horn" to 1, "obj.hunting_crossbow" to 1),
                "obj.hunting_crossbow_sunlight",
                1,
                level = 74,
                xp = 0.0,
                ticks = 0,
            ),
        )

    private val ASSEMBLY =
        listOf(
            Recipe(
                "dbrow.fletching_ogre_arrow_from_ogre_headless_arrow",
                listOf("obj.ogre_headless_arrow" to 6, "obj.wolfbone_arrowheads" to 6),
                "obj.ogre_arrow",
                6,
                level = 5,
                xp = 6.0,
                ticks = 2,
            ),
            Recipe(
                "dbrow.fletching_zogre_brutal_bronze_from_nails_bronze",
                listOf("obj.nails_bronze" to 6, "obj.ogre_headless_arrow" to 6),
                "obj.zogre_brutal_bronze",
                6,
                level = 7,
                xp = 8.4,
                ticks = 2,
                tool = "obj.hammer",
            ),
            Recipe(
                "dbrow.fletching_xbows_crossbow_unstrung_bronze_from_xbows_crossbow_limbs_bronze",
                listOf(
                    "obj.xbows_crossbow_limbs_bronze" to 1,
                    "obj.xbows_crossbow_stock_wood" to 1,
                ),
                "obj.xbows_crossbow_unstrung_bronze",
                1,
                level = 9,
                xp = 12.0,
                ticks = 2,
                tool = "obj.hammer",
            ),
            Recipe(
                "dbrow.fletching_zogre_brutal_iron_from_ogre_headless_arrow",
                listOf("obj.ogre_headless_arrow" to 6, "obj.nails_iron" to 6),
                "obj.zogre_brutal_iron",
                6,
                level = 18,
                xp = 15.6,
                ticks = 2,
                tool = "obj.hammer",
            ),
            Recipe(
                "dbrow.fletching_xbows_crossbow_unstrung_blurite_from_xbows_crossbow_limbs_blurite",
                listOf(
                    "obj.xbows_crossbow_limbs_blurite" to 1,
                    "obj.xbows_crossbow_stock_oak" to 1,
                ),
                "obj.xbows_crossbow_unstrung_blurite",
                1,
                level = 24,
                xp = 32.0,
                ticks = 2,
                tool = "obj.hammer",
            ),
            Recipe(
                "dbrow.fletching_zogre_brutal_steel_from_ogre_headless_arrow",
                listOf("obj.ogre_headless_arrow" to 6, "obj.nails" to 6),
                "obj.zogre_brutal_steel",
                6,
                level = 33,
                xp = 30.6,
                ticks = 2,
                tool = "obj.hammer",
            ),
            Recipe(
                "dbrow.fletching_zogre_brutal_black_from_nails_black",
                listOf("obj.nails_black" to 6, "obj.ogre_headless_arrow" to 6),
                "obj.zogre_brutal_black",
                6,
                level = 38,
                xp = 39.0,
                ticks = 2,
                tool = "obj.hammer",
            ),
            Recipe(
                "dbrow.fletching_xbows_crossbow_unstrung_iron_from_xbows_crossbow_limbs_iron",
                listOf(
                    "obj.xbows_crossbow_limbs_iron" to 1,
                    "obj.xbows_crossbow_stock_willow" to 1,
                ),
                "obj.xbows_crossbow_unstrung_iron",
                1,
                level = 39,
                xp = 44.0,
                ticks = 2,
                tool = "obj.hammer",
            ),
            Recipe(
                "dbrow.fletching_xbows_crossbow_unstrung_steel_from_xbows_crossbow_limbs_steel",
                listOf("obj.xbows_crossbow_limbs_steel" to 1, "obj.xbows_crossbow_stock_teak" to 1),
                "obj.xbows_crossbow_unstrung_steel",
                1,
                level = 46,
                xp = 54.0,
                ticks = 2,
                tool = "obj.hammer",
            ),
            Recipe(
                "dbrow.fletching_zogre_brutal_mithril_from_ogre_headless_arrow",
                listOf("obj.ogre_headless_arrow" to 6, "obj.nails_mithril" to 6),
                "obj.zogre_brutal_mithril",
                6,
                level = 49,
                xp = 45.0,
                ticks = 2,
                tool = "obj.hammer",
            ),
            Recipe(
                "dbrow.fletching_xbows_crossbow_unstrung_mithril_from_xbows_crossbow_stock_maple",
                listOf(
                    "obj.xbows_crossbow_stock_maple" to 1,
                    "obj.xbows_crossbow_limbs_mithril" to 1,
                ),
                "obj.xbows_crossbow_unstrung_mithril",
                1,
                level = 54,
                xp = 64.0,
                ticks = 2,
                tool = "obj.hammer",
            ),
            Recipe(
                "dbrow.fletching_xbows_crossbow_unstrung_adamantite_from_xbows_crossbow_limbs_adamantite",
                listOf(
                    "obj.xbows_crossbow_limbs_adamantite" to 1,
                    "obj.xbows_crossbow_stock_mahogany" to 1,
                ),
                "obj.xbows_crossbow_unstrung_adamantite",
                1,
                level = 61,
                xp = 82.0,
                ticks = 2,
                tool = "obj.hammer",
            ),
            Recipe(
                "dbrow.fletching_zogre_brutal_adamant_from_nails_adamant",
                listOf("obj.nails_adamant" to 6, "obj.ogre_headless_arrow" to 6),
                "obj.zogre_brutal_adamant",
                6,
                level = 62,
                xp = 61.2,
                ticks = 2,
                tool = "obj.hammer",
            ),
            Recipe(
                "dbrow.fletching_xbows_crossbow_unstrung_runite_from_xbows_crossbow_limbs_runite",
                listOf("obj.xbows_crossbow_limbs_runite" to 1, "obj.xbows_crossbow_stock_yew" to 1),
                "obj.xbows_crossbow_unstrung_runite",
                1,
                level = 69,
                xp = 100.0,
                ticks = 2,
                tool = "obj.hammer",
            ),
            Recipe(
                "dbrow.fletching_zogre_brutal_rune_from_ogre_headless_arrow",
                listOf("obj.ogre_headless_arrow" to 6, "obj.nails_rune" to 6),
                "obj.zogre_brutal_rune",
                6,
                level = 77,
                xp = 75.0,
                ticks = 2,
                tool = "obj.hammer",
            ),
            Recipe(
                "dbrow.fletching_xbows_crossbow_unstrung_dragon_from_xbows_crossbow_limbs_dragon",
                listOf(
                    "obj.xbows_crossbow_limbs_dragon" to 1,
                    "obj.xbows_crossbow_stock_magic" to 1,
                ),
                "obj.xbows_crossbow_unstrung_dragon",
                1,
                level = 78,
                xp = 135.0,
                ticks = 2,
                tool = "obj.hammer",
            ),
        )
}
