[gamevals.dbtable]
collection_log_categories=65510

[gamevals.dbrow]
collection_log_category_abyssal_sire=64594
collection_log_category_alchemical_hydra=64593
collection_log_category_amoxliatl=64592
collection_log_category_araxxor=64591
collection_log_category_barrows_chests=64590
collection_log_category_brutus=64589
collection_log_category_bryophyta=64588
collection_log_category_callisto_and_artio=64587
collection_log_category_cerberus=64586
collection_log_category_chaos_elemental=64585
collection_log_category_chaos_fanatic=64584
collection_log_category_commander_zilyana=64583
collection_log_category_corporeal_beast=64582
collection_log_category_crazy_archaeologist=64581
collection_log_category_dagannoth_kings=64580
collection_log_category_deranged_archaeologist=64579
collection_log_category_doom_of_mokhaiotl=64578
collection_log_category_duke_sucellus=64577
collection_log_category_the_fight_caves=64576
collection_log_category_fortis_colosseum=64575
collection_log_category_the_gauntlet=64574
collection_log_category_general_graardor=64573
collection_log_category_giant_mole=64572
collection_log_category_grotesque_guardians=64571
collection_log_category_hespori=64570
collection_log_category_the_hueycoatl=64569
collection_log_category_the_inferno=64568
collection_log_category_kalphite_queen=64567
collection_log_category_king_black_dragon=64566
collection_log_category_kraken=64565
collection_log_category_kree_arra=64564
collection_log_category_k_ril_tsutsaroth=64563
collection_log_category_the_leviathan=64562
collection_log_category_the_mad_angel=64561
collection_log_category_maggot_king=64560
collection_log_category_moons_of_peril=64559
collection_log_category_nex=64558
collection_log_category_the_nightmare=64557
collection_log_category_obor=64556
collection_log_category_phantom_muspah=64555
collection_log_category_royal_titans=64554
collection_log_category_sarachnis=64553
collection_log_category_scorpia=64552
collection_log_category_scurrius=64551
collection_log_category_shellbane_gryphon=64550
collection_log_category_skotizo=64549
collection_log_category_tempoross=64548
collection_log_category_thermonuclear_smoke_devil=64547
collection_log_category_vardorvis=64546
collection_log_category_venenatis_and_spindel=64545
collection_log_category_vet_ion_and_calvar_ion=64544
collection_log_category_vorkath=64543
collection_log_category_the_whisperer=64542
collection_log_category_wintertodt=64541
collection_log_category_yama=64540
collection_log_category_zalcano=64539
collection_log_category_zulrah=64538
collection_log_category_chambers_of_xeric=64537
collection_log_category_theatre_of_blood=64536
collection_log_category_tombs_of_amascut=64535
collection_log_category_beginner_treasure_trails=64534
collection_log_category_easy_treasure_trails=64533
collection_log_category_medium_treasure_trails=64532
collection_log_category_hard_treasure_trails=64531
collection_log_category_elite_treasure_trails=64530
collection_log_category_master_treasure_trails=64529
collection_log_category_hard_treasure_trails_rare=64528
collection_log_category_elite_treasure_trails_rare=64527
collection_log_category_master_treasure_trails_rare=64526
collection_log_category_shared_treasure_trail_rewards=64525
collection_log_category_scroll_cases=64524
collection_log_category_barbarian_assault=64523
collection_log_category_barracuda_trials=64522
collection_log_category_brimhaven_agility_arena=64521
collection_log_category_castle_wars=64520
collection_log_category_fishing_trawler=64519
collection_log_category_giants_foundry=64518
collection_log_category_gnome_restaurant=64517
collection_log_category_guardians_of_the_rift=64516
collection_log_category_hallowed_sepulchre=64515
collection_log_category_last_man_standing=64514
collection_log_category_magic_training_arena=64513
collection_log_category_mahogany_homes=64512
collection_log_category_mastering_mixology=64511
collection_log_category_pest_control=64510
collection_log_category_rogues_den=64509
collection_log_category_shades_of_mort_ton=64508
collection_log_category_soul_wars=64507
collection_log_category_temple_trekking=64506
collection_log_category_tithe_farm=64505
collection_log_category_trouble_brewing=64504
collection_log_category_vale_totems=64503
collection_log_category_volcanic_mine=64502
collection_log_category_aerial_fishing=64501
collection_log_category_all_pets=64500
collection_log_category_boat_paints=64499
collection_log_category_camdozaal=64498
collection_log_category_champion_s_challenge=64497
collection_log_category_chompy_bird_hunting=64496
collection_log_category_colossal_wyrm_agility=64495
collection_log_category_creature_creation=64494
collection_log_category_cyclopes=64493
collection_log_category_elder_chaos_druids=64492
collection_log_category_forestry=64491
collection_log_category_fossil_island_notes=64490
collection_log_category_glough_s_experiments=64489
collection_log_category_hunter_guild=64488
collection_log_category_lost_schematics=64487
collection_log_category_monkey_backpacks=64486
collection_log_category_motherlode_mine=64485
collection_log_category_my_notes=64484
collection_log_category_ocean_encounters=64483
collection_log_category_random_events=64482
collection_log_category_revenants=64481
collection_log_category_rooftop_agility=64480
collection_log_category_sailing_miscellaneous=64479
collection_log_category_sea_treasures=64478
collection_log_category_shayzien_armour=64477
collection_log_category_shooting_stars=64476
collection_log_category_skilling_pets=64475
collection_log_category_slayer=64474
collection_log_category_tormented_demons=64473
collection_log_category_tzhaar=64472
collection_log_category_miscellaneous=64471
