[[varp]]
isServerOnly = true
id = "varp.toa_personal_invocations_a"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.toa_personal_invocations_b"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.toa_personal_invocations_c"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.toa_personal_kc_requirement"
scope = "Perm"
transmit = "Never"

[[inventory]]
isServerOnly = true
id = "inv.gravestone"
inherit = "inv.gravestone"
scope = "Perm"
protect = false

[[varp]]
isServerOnly = true
id = "varp.toa_retrieval_locked"
scope = "Perm"
transmit = "Never"
