[[varp]]
isServerOnly = true
id = "varp.toa_personal_invocations_a"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.toa_personal_invocations_b"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.toa_personal_invocations_c"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.toa_personal_kc_requirement"
scope = "Perm"
transmit = "Never"

[[inventory]]
isServerOnly = true
id = "inv.gravestone"
inherit = "inv.gravestone"
scope = "Perm"
protect = false

[[varp]]
isServerOnly = true
id = "varp.toa_retrieval_locked"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.toa_attempts_entry"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.toa_attempts_normal"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.toa_attempts_expert"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.toa_deaths_entry"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.toa_deaths_normal"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.toa_deaths_expert"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.toa_best_challenge_entry_1"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.toa_best_challenge_entry_2"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.toa_best_challenge_entry_3"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.toa_best_challenge_entry_4"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.toa_best_challenge_entry_5"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.toa_best_challenge_entry_6"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.toa_best_challenge_entry_7"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.toa_best_challenge_entry_8"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.toa_best_overall_entry_1"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.toa_best_overall_entry_2"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.toa_best_overall_entry_3"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.toa_best_overall_entry_4"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.toa_best_overall_entry_5"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.toa_best_overall_entry_6"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.toa_best_overall_entry_7"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.toa_best_overall_entry_8"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.toa_best_challenge_normal_1"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.toa_best_challenge_normal_2"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.toa_best_challenge_normal_3"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.toa_best_challenge_normal_4"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.toa_best_challenge_normal_5"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.toa_best_challenge_normal_6"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.toa_best_challenge_normal_7"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.toa_best_challenge_normal_8"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.toa_best_overall_normal_1"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.toa_best_overall_normal_2"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.toa_best_overall_normal_3"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.toa_best_overall_normal_4"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.toa_best_overall_normal_5"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.toa_best_overall_normal_6"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.toa_best_overall_normal_7"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.toa_best_overall_normal_8"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.toa_best_challenge_expert_1"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.toa_best_challenge_expert_2"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.toa_best_challenge_expert_3"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.toa_best_challenge_expert_4"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.toa_best_challenge_expert_5"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.toa_best_challenge_expert_6"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.toa_best_challenge_expert_7"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.toa_best_challenge_expert_8"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.toa_best_overall_expert_1"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.toa_best_overall_expert_2"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.toa_best_overall_expert_3"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.toa_best_overall_expert_4"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.toa_best_overall_expert_5"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.toa_best_overall_expert_6"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.toa_best_overall_expert_7"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.toa_best_overall_expert_8"
scope = "Perm"
transmit = "Never"
