[gamevals.tables]
fishing_spots=1240
fishing_tools=1241

[gamevals.dbrows]
fishing_shrimps=97001
fishing_sardine=97002
fishing_herring=97003
fishing_anchovies=97004
fishing_mackerel=97005
fishing_trout=97006
fishing_cod=97007
fishing_pike=97008
fishing_salmon=97009
fishing_tuna=97010
fishing_lobster=97011
fishing_bass=97012
fishing_swordfish=97013
fishing_lava_eel=97014
fishing_monkfish=97015
fishing_karambwan=97016
fishing_shark=97017
fishing_infernal_eel=97018
fishing_anglerfish=97019
fishing_dark_crab=97020
fishing_sacred_eel=97021
fishing_tool_small_fishing_net=97050
fishing_tool_fishing_rod=97051
fishing_tool_fly_fishing_rod=97052
fishing_tool_harpoon=97053
fishing_tool_lobster_pot=97054
fishing_tool_big_fishing_net=97055
fishing_tool_dragon_harpoon=97056
fishing_tool_infernal_harpoon=97057
fishing_tool_crystal_harpoon=97058
fishing_tool_barbarian_rod=97059
fishing_tool_karambwan_vessel=97060
fishing_tool_oily_fishing_rod=97061
