[gamevals.tables]
fishing_spots=1240
fishing_tools=1241

[gamevals.dbrows]
fishing_shrimps=98301
fishing_sardine=98302
fishing_herring=98303
fishing_anchovies=98304
fishing_mackerel=98305
fishing_trout=98306
fishing_cod=98307
fishing_pike=98308
fishing_salmon=98309
fishing_tuna=98310
fishing_lobster=98311
fishing_bass=98312
fishing_swordfish=98313
fishing_lava_eel=98314
fishing_monkfish=98315
fishing_karambwan=98316
fishing_shark=98317
fishing_infernal_eel=98318
fishing_anglerfish=98319
fishing_dark_crab=98320
fishing_sacred_eel=98321
fishing_tool_small_fishing_net=98350
fishing_tool_fishing_rod=98351
fishing_tool_fly_fishing_rod=98352
fishing_tool_harpoon=98353
fishing_tool_lobster_pot=98354
fishing_tool_big_fishing_net=98355
fishing_tool_dragon_harpoon=98356
fishing_tool_infernal_harpoon=98357
fishing_tool_crystal_harpoon=98358
fishing_tool_barbarian_rod=98359
fishing_tool_karambwan_vessel=98360
fishing_tool_oily_fishing_rod=98361
