id = "Crystalline Wolf Drops"
npcs = ["npc.crystal_wolf"]

[[guaranteed]]
obj = "obj.gauntlet_crystal_shard"
count = "80..100"

[main]
total = 21
name = "Crystalline Wolf Drops"

[[main.entries]]
weight = 6
nothing = true

[[main.entries]]
weight = 9
obj = "obj.gauntlet_crystal_shard"
count = "7..14"

[[main.entries]]
weight = 3
obj = "obj.gauntlet_raw_food"
count = "2..4"

[[main.entries]]
weight = 2
obj = "obj.gauntlet_herb"
count = 1

[[main.entries]]
weight = 1
obj = "obj.gauntlet_teleport_crystal"
count = 1
