id = "Crystalline Bat Drops"
npcs = ["npc.crystal_bat"]

[[guaranteed]]
obj = "obj.gauntlet_crystal_shard"
count = "20..30"

[main]
total = 24
name = "Crystalline Bat Drops"

[[main.entries]]
weight = 9
nothing = true

[[main.entries]]
weight = 9
obj = "obj.gauntlet_crystal_shard"
count = "3..7"

[[main.entries]]
weight = 3
obj = "obj.gauntlet_raw_food"
count = "1..3"

[[main.entries]]
weight = 2
obj = "obj.gauntlet_herb"
count = 1

[[main.entries]]
weight = 1
obj = "obj.gauntlet_teleport_crystal"
count = 1
