[gamevals.synth]
bigdoor_close = 45
bigdoor_open = 46
bookcase_open_and_close = 42
chicken_into_human = 1564
coffin_open = 54
creakydoor_open = 56
cupboard_open = 58
deadtree_attack = 651
digspade = 1470
ernest_clunk = 1565
ernest_sprinkle = 1566
fish_swim = 2601
iron_door_open = 71
swan_rumble = 1790
unlock = 2419
