[[enum]]
isServerOnly = true
id = "enum.item_pack_contents"
keyType = "OBJ"
valueType = "OBJ"

[enum.values]
"obj.pack_fishing_bait" = "obj.fishing_bait"
"obj.pack_compost" = "obj.bucket_compost"
"obj.pack_plant_pot_compost" = "obj.plantpot_empty"
"obj.pack_sack" = "obj.sack_empty"
"obj.pack_basket" = "obj.basket_empty"
"obj.pack_feather" = "obj.feather"
"obj.pack_bucket" = "obj.bucket_empty"
"obj.pack_jug_empty" = "obj.jug_empty"
"obj.pack_vial_empty" = "obj.vial_empty"
"obj.pack_vial_water" = "obj.vial_water"
"obj.pack_olive_oil" = "obj.oliveoil4"
"obj.pack_slayer_broad_bolt_unfinished" = "obj.slayer_broad_bolt_unfinished"
"obj.pack_slayer_broad_arrowhead" = "obj.slayer_broad_arrowhead"
"obj.pack_softclay" = "obj.softclay"
"obj.pack_amylase" = "obj.amylase"
"obj.pack_airrune" = "obj.airrune"
"obj.pack_airrune_tzhaar" = "obj.airrune"
"obj.pack_waterrune" = "obj.waterrune"
"obj.pack_waterrune_tzhaar" = "obj.waterrune"
"obj.pack_earthrune" = "obj.earthrune"
"obj.pack_earthrune_tzhaar" = "obj.earthrune"
"obj.pack_firerune" = "obj.firerune"
"obj.pack_firerune_tzhaar" = "obj.firerune"
"obj.pack_mindrune" = "obj.mindrune"
"obj.pack_chaosrune" = "obj.chaosrune"
"obj.pack_eye_newt" = "obj.eye_of_newt"
"obj.pack_box_trap" = "obj.hunting_box_trap"
"obj.pack_ojibway_bird_snare" = "obj.hunting_ojibway_bird_snare"
"obj.pack_magic_imp_box" = "obj.magic_imp_box"
"obj.pack_bone_bolt" = "obj.dttd_bone_crossbow_bolt"
"obj.piscarilius_pack_sandworms" = "obj.piscarilius_sandworms"
"obj.shark_lure_pack" = "obj.shark_lure"
