[gamevals.tables]
cooking_recipes=1242

[gamevals.dbrows]
cooking_shrimps=98401
cooking_meat=98402
cooking_chicken=98403
cooking_sardine=98404
cooking_herring=98405
cooking_mackerel=98406
cooking_trout=98407
cooking_cod=98408
cooking_pike=98409
cooking_salmon=98410
cooking_tuna=98411
cooking_lobster=98412
cooking_bass=98413
cooking_swordfish=98414
cooking_monkfish=98415
cooking_shark=98416
cooking_sea_turtle=98417
cooking_anglerfish=98418
cooking_manta_ray=98419
cooking_dark_crab=98420
cooking_bread=98421
cooking_stew=98422
cooking_meat_pie=98423
cooking_redberry_pie=98424
cooking_apple_pie=98425
cooking_plain_pizza=98426
cooking_cake=98427
