[gamevals.timer]
gauntlet_time_limit = 420

[gamevals.dbtable]
gauntlet_room_slots = 56000

[gamevals.dbrow]
gauntlet_slots_middle_0 = 56001
gauntlet_slots_middle_1 = 56002
gauntlet_slots_middle_2 = 56003
gauntlet_slots_middle_3 = 56004
gauntlet_slots_edge_0 = 56005
gauntlet_slots_edge_1 = 56006
gauntlet_slots_edge_2 = 56007
gauntlet_slots_edge_3 = 56008
gauntlet_slots_corner_0 = 56009
gauntlet_slots_corner_1 = 56010
gauntlet_slots_corner_2 = 56011
gauntlet_slots_corner_3 = 56012
