[gamevals.enum]
fletching_anims=65470

[gamevals.dbtable]
fletching_cutting=65501
fletching_stringing=65500
fletching_attaching=65499
fletching_gem_tips=65498
fletching_assembly=65497

[gamevals.queue]
fletching_produce = 61

[gamevals.dbrow]
fletching_arrow_shaft_from_logs=63893
fletching_brew_scrapey_bark_from_brew_scrapey_logs=63892
fletching_seeking_arrow_shaft_from_sap_treated_logs=63891
fletching_javelin_shaft_from_logs=63890
fletching_ogre_arrow_shaft_from_achey_tree_logs=63889
fletching_unstrung_shortbow_from_logs=63888
fletching_xbows_crossbow_stock_wood_from_logs=63887
fletching_unstrung_longbow_from_logs=63886
fletching_arrow_shaft_from_oak_logs=63885
fletching_seeking_arrow_shaft_from_sap_treated_oak_logs=63884
fletching_unstrung_oak_shortbow_from_oak_logs=63883
fletching_xbows_crossbow_stock_oak_from_oak_logs=63882
fletching_unstrung_oak_longbow_from_oak_logs=63881
fletching_oak_shield_from_oak_logs=63880
fletching_arrow_shaft_from_willow_logs=63879
fletching_seeking_arrow_shaft_from_sap_treated_willow_logs=63878
fletching_unstrung_willow_shortbow_from_willow_logs=63877
fletching_xbows_crossbow_stock_willow_from_willow_logs=63876
fletching_unstrung_willow_longbow_from_willow_logs=63875
fletching_willow_shield_from_willow_logs=63874
fletching_arrow_shaft_from_maple_logs=63873
fletching_seeking_arrow_shaft_from_sap_treated_maple_logs=63872
fletching_xbows_crossbow_stock_teak_from_teak_logs=63871
fletching_unstrung_maple_shortbow_from_maple_logs=63870
fletching_xbows_crossbow_stock_maple_from_maple_logs=63869
fletching_unstrung_maple_longbow_from_maple_logs=63868
fletching_maple_shield_from_maple_logs=63867
fletching_arrow_shaft_from_yew_logs=63866
fletching_seeking_arrow_shaft_from_sap_treated_yew_logs=63865
fletching_xbows_crossbow_stock_mahogany_from_mahogany_logs=63864
fletching_unstrung_yew_shortbow_from_yew_logs=63863
fletching_xbows_crossbow_stock_yew_from_yew_logs=63862
fletching_blisterwood_stake_from_blisterwood_logs=63861
fletching_unstrung_yew_longbow_from_yew_logs=63860
fletching_yew_shield_from_yew_logs=63859
fletching_atlatl_dart_shaft_from_ent_branch=63858
fletching_arrow_shaft_from_magic_logs=63857
fletching_seeking_arrow_shaft_from_sap_treated_magic_logs=63856
fletching_xbows_crossbow_stock_magic_from_magic_logs=63855
fletching_unstrung_magic_shortbow_from_magic_logs=63854
fletching_unstrung_magic_longbow_from_magic_logs=63853
fletching_magic_shield_from_magic_logs=63852
fletching_arrow_shaft_from_redwood_logs=63851
fletching_redwood_hiking_staff_from_redwood_logs=63850
fletching_seeking_arrow_shaft_from_sap_treated_redwood_logs=63849
fletching_redwood_shield_from_redwood_logs=63848
fletching_shortbow_from_bow_string=63847
fletching_xbows_crossbow_bronze_from_xbows_crossbow_unstrung_bronze=63846
fletching_longbow_from_bow_string=63845
fletching_oak_shortbow_from_bow_string=63844
fletching_xbows_crossbow_blurite_from_xbows_crossbow_unstrung_blurite=63843
fletching_oak_longbow_from_bow_string=63842
fletching_zogre_bow_from_bow_string=63841
fletching_willow_shortbow_from_bow_string=63840
fletching_xbows_crossbow_iron_from_xbows_crossbow_string=63839
fletching_willow_longbow_from_bow_string=63838
fletching_xbows_crossbow_steel_from_xbows_crossbow_string=63837
fletching_devious_bowsword_from_bow_string=63836
fletching_maple_shortbow_from_bow_string=63835
fletching_xbows_crossbow_mithril_from_xbows_crossbow_string=63834
fletching_maple_longbow_from_bow_string=63833
fletching_xbows_crossbow_adamantite_from_xbows_crossbow_unstrung_adamantite=63832
fletching_yew_shortbow_from_bow_string=63831
fletching_xbows_crossbow_runite_from_xbows_crossbow_string=63830
fletching_yew_longbow_from_bow_string=63829
fletching_xbows_crossbow_dragon_from_xbows_crossbow_string=63828
fletching_magic_shortbow_from_bow_string=63827
fletching_magic_longbow_from_bow_string=63826
fletching_bronze_arrow_from_bronze_arrowheads=63825
fletching_headless_arrow_from_arrow_shaft=63824
fletching_seeking_adamant_arrow_from_adamant_arrow=63823
fletching_seeking_amethyst_arrow_from_amethyst_arrow=63822
fletching_seeking_slayer_broad_arrows_from_slayer_broad_arrows=63821
fletching_seeking_bronze_arrow_from_bronze_arrowheads=63820
fletching_seeking_bronze_arrow_from_bronze_arrow=63819
fletching_seeking_dragon_arrow_from_bucket_of_bloodwood_sap=63818
fletching_seeking_headless_arrow_from_feather=63817
fletching_seeking_iron_arrow_from_bucket_of_bloodwood_sap=63816
fletching_seeking_mithril_arrow_from_bucket_of_bloodwood_sap=63815
fletching_seeking_rune_arrow_from_bucket_of_bloodwood_sap=63814
fletching_seeking_steel_arrow_from_bucket_of_bloodwood_sap=63813
fletching_bronze_javelin_from_bronze_javelin_head=63812
fletching_ogre_headless_arrow_from_feather=63811
fletching_bolt_from_xbows_crossbow_bolts_bronze_unfeathered=63810
fletching_bronze_dart_from_bronze_dart_tip=63809
fletching_thprotodart_from_feather=63808
fletching_opal_bolt_from_bolt=63807
fletching_iron_arrow_from_headless_arrow=63806
fletching_seeking_iron_arrow_from_iron_arrowheads=63805
fletching_seeking_steel_arrow_from_seeking_headless_arrow=63804
fletching_iron_javelin_from_iron_javelin_head=63803
fletching_iron_dart_from_feather=63802
fletching_xbows_crossbow_bolts_blurite_from_xbows_crossbow_bolts_blurite_unfeathered=63801
fletching_xbows_crossbow_bolts_blurite_tipped_jade_from_xbows_crossbow_bolts_blurite=63800
fletching_steel_arrow_from_headless_arrow=63799
fletching_steel_javelin_from_javelin_shaft=63798
fletching_steel_dart_from_feather=63797
fletching_xbows_crossbow_bolts_iron_from_feather=63796
fletching_pearl_bolt_from_xbows_crossbow_bolts_iron=63795
fletching_xbows_crossbow_bolts_silver_from_feather=63794
fletching_mithril_arrow_from_headless_arrow=63793
fletching_seeking_mithril_arrow_from_mithril_arrowheads=63792
fletching_xbows_crossbow_bolts_steel_from_feather=63791
fletching_mithril_javelin_from_javelin_shaft=63790
fletching_xbows_crossbow_bolts_steel_tipped_redtopaz_from_xbows_crossbow_bolts_steel=63789
fletching_barbed_bolt_from_barbed_bolttips=63788
fletching_slayer_broad_arrows_from_slayer_broad_arrowhead=63787
fletching_mithril_dart_from_feather=63786
fletching_seeking_slayer_broad_arrows_from_slayer_broad_arrowhead=63785
fletching_xbows_crossbow_bolts_mithril_from_feather=63784
fletching_slayer_broad_bolt_from_feather=63783
fletching_xbows_crossbow_bolts_mithril_tipped_sapphire_from_xbows_crossbow_bolts_mithril=63782
fletching_xbows_crossbow_bolts_mithril_tipped_emerald_from_xbows_bolt_tips_emerald=63781
fletching_adamant_arrow_from_adamant_arrowheads=63780
fletching_seeking_adamant_arrow_from_adamant_arrowheads=63779
fletching_xbows_crossbow_bolts_adamantite_from_xbows_crossbow_bolts_adamantite_unfeathered=63778
fletching_adamant_javelin_from_adamant_javelin_head=63777
fletching_xbows_crossbow_bolts_adamantite_tipped_ruby_from_xbows_crossbow_bolts_adamantite=63776
fletching_xbows_crossbow_bolts_adamantite_tipped_diamond_from_xbows_crossbow_bolts_adamantite=63775
fletching_adamant_dart_from_adamant_dart_tip=63774
fletching_xbows_crossbow_bolts_runite_from_feather=63773
fletching_xbows_crossbow_bolts_runite_tipped_dragonstone_from_xbows_bolt_tips_dragonstone=63772
fletching_xbows_crossbow_bolts_runite_tipped_onyx_from_xbows_bolt_tips_onyx=63771
fletching_atlatl_dart_from_atlatl_dart_tips=63770
fletching_headless_atlatl_dart_from_atlatl_dart_shaft=63769
fletching_rune_arrow_from_headless_arrow=63768
fletching_seeking_rune_arrow_from_rune_arrowheads=63767
fletching_slayer_broad_bolt_amethyst_from_xbows_bolt_tips_amethyst=63766
fletching_rune_javelin_from_javelin_shaft=63765
fletching_rune_dart_from_feather=63764
fletching_amethyst_arrow_from_amethyst_arrowheads=63763
fletching_seeking_amethyst_arrow_from_amethyst_arrowheads=63762
fletching_amethyst_javelin_from_amethyst_javelin_head=63761
fletching_dragon_bolts_unenchanted_diamond_from_xbows_bolt_tips_diamond=63760
fletching_dragon_bolts_from_dragon_bolts_unfeathered=63759
fletching_dragon_bolts_unenchanted_dragonstone_from_dragon_bolts=63758
fletching_dragon_bolts_unenchanted_emerald_from_dragon_bolts=63757
fletching_dragon_bolts_unenchanted_jade_from_dragon_bolts=63756
fletching_dragon_bolts_unenchanted_onyx_from_dragon_bolts=63755
fletching_dragon_bolts_unenchanted_opal_from_dragon_bolts=63754
fletching_dragon_bolts_unenchanted_pearl_from_dragon_bolts=63753
fletching_dragon_bolts_unenchanted_ruby_from_dragon_bolts=63752
fletching_dragon_bolts_unenchanted_sapphire_from_dragon_bolts=63751
fletching_dragon_bolts_unenchanted_topaz_from_dragon_bolts=63750
fletching_amethyst_dart_from_amethyst_dart_tip=63749
fletching_dragon_arrow_from_dragon_arrowheads=63748
fletching_seeking_dragon_arrow_from_dragon_arrowheads=63747
fletching_dragon_javelin_from_dragon_javelin_head=63746
fletching_dragon_dart_from_dragon_dart_tip=63745
fletching_wolfbone_arrowheads_from_wolf_bones=63744
fletching_opal_bolttips_from_opal=63743
fletching_xbows_bolt_tips_jade_from_jade=63742
fletching_huntingbow_bolts_from_huntingbeast_spike=63741
fletching_pearl_bolttips_from_smalloysterpearls=63740
fletching_pearl_bolttips_from_bigoysterpearls=63739
fletching_huntingbow_bigbolts_from_huntingbeast_bigspike=63738
fletching_xbows_bolt_tips_redtopaz_from_red_topaz=63737
fletching_xbows_bolt_tips_sapphire_from_sapphire=63736
fletching_xbows_bolt_tips_emerald_from_emerald=63735
fletching_sunlight_antelope_bolt_from_hunting_antelopesun_horn=63734
fletching_xbows_bolt_tips_ruby_from_ruby=63733
fletching_xbows_bolt_tips_diamond_from_diamond=63732
fletching_xbows_bolt_tips_dragonstone_from_dragonstone=63731
fletching_moonlight_antelope_bolt_from_hunting_antelopemoon_horn=63730
fletching_xbows_bolt_tips_onyx_from_onyx=63729
fletching_atlatl_dart_tips_from_custodian_broken_antler=63728
fletching_toxic_blowpipe_from_blowpipe_fang=63727
fletching_ogre_arrow_from_ogre_headless_arrow=63726
fletching_zogre_brutal_bronze_from_nails_bronze=63725
fletching_xbows_crossbow_unstrung_bronze_from_xbows_crossbow_limbs_bronze=63724
fletching_zogre_brutal_iron_from_ogre_headless_arrow=63723
fletching_xbows_crossbow_unstrung_blurite_from_xbows_crossbow_limbs_blurite=63722
fletching_zogre_brutal_steel_from_ogre_headless_arrow=63721
fletching_zogre_brutal_black_from_nails_black=63720
fletching_xbows_crossbow_unstrung_iron_from_xbows_crossbow_limbs_iron=63719
fletching_xbows_crossbow_unstrung_steel_from_xbows_crossbow_limbs_steel=63718
fletching_zogre_brutal_mithril_from_ogre_headless_arrow=63717
fletching_xbows_crossbow_unstrung_mithril_from_xbows_crossbow_stock_maple=63716
fletching_xbows_crossbow_unstrung_adamantite_from_xbows_crossbow_limbs_adamantite=63715
fletching_zogre_brutal_adamant_from_nails_adamant=63714
fletching_xbows_crossbow_unstrung_runite_from_xbows_crossbow_limbs_runite=63713
fletching_zogre_brutal_rune_from_ogre_headless_arrow=63712
fletching_xbows_crossbow_unstrung_dragon_from_xbows_crossbow_limbs_dragon=63711
fletching_seeking_adamant_arrow_from_adamant_arrow_x150=63710
fletching_seeking_amethyst_arrow_from_amethyst_arrow_x150=63709
fletching_seeking_slayer_broad_arrows_from_slayer_broad_arrows_x150=63708
fletching_seeking_bronze_arrow_from_bronze_arrow_x150=63707
fletching_seeking_dragon_arrow_from_dragon_arrow_x150=63706
fletching_seeking_iron_arrow_from_iron_arrow_x150=63705
fletching_seeking_mithril_arrow_from_mithril_arrow_x150=63704
fletching_seeking_rune_arrow_from_rune_arrow_x150=63703
fletching_seeking_steel_arrow_from_steel_arrow_x150=63702
fletching_unstrung_zogre_bow_from_achey_tree_logs=63701
fletching_battlestaff_from_celastrus_wood=63700
fletching_vmq4_root_kindling_from_vmq4_roots=63699
fletching_greenman_statue_from_maple_logs=63698
fletching_camphor_blowpipe_empty_from_camphor_logs=63697
fletching_blisterwood_sickle_from_blisterwood_logs=63696
fletching_hg_hunter_spear_from_teak_logs=63695
fletching_blisterwood_sickle_enhanced_from_blisterwood_logs=63694
fletching_ironwood_blowpipe_empty_from_ironwood_logs=63693
fletching_greenman_wall_decoration_from_yew_logs=63692
fletching_rosewood_blowpipe_empty_from_rosewood_logs=63691
fletching_hunting_crossbow_sunlight_from_hunting_antelopesun_horn=63690
